/* meta_i18n_engine.js — GENERATED by tools/build_meta_split.js.
 * The translateMetaSmart engine (functions only) sliced out of
 * meta_i18n_ext.js. The per-UI data it reads (META_I18N / META_I18N_ATOMS)
 * comes from wordmap_meta_lite.js + meta_i18n/<ui>.js. DO NOT EDIT — edit
 * meta_i18n_ext.js and regenerate. */
/*
 * meta_i18n_ext.js — Smart composite translator for language metadata.
 *
 * Background: META_I18N (in wordmap_meta.js) holds full pre-composed
 * translations like "Niger-Congo (Bantu, Nguni)" → "ニジェール・コンゴ語族（…）".
 * It only contains strings the maintainers have hand-translated, so the long
 * tail of compound metadata (family / countries / official / script) falls
 * through to English.
 *
 * This module adds two layers on top:
 *   1. ATOMS — per-UI-language dictionary of *base* terms (country names,
 *      sub-family branches, geographic adjectives, script names, status
 *      qualifiers). Composing these covers the vast majority of compound
 *      strings without having to hand-translate every variation.
 *   2. translateMetaSmart() — recursive translator that decomposes a string
 *      via top-level commas, slashes, and parentheses, translating each piece
 *      using META_I18N first (exact match), then ATOMS (atomic match), and
 *      recombining with locale-appropriate separators.
 *
 * Conflict-free with parallel work: this is a NEW file. wordmap_meta.js is
 * not touched.
 */

// === Smart composite translator ============================================

// Split a string on `sep` only at the top level (depth 0 of parentheses).
// For commas specifically, also skip thousands separators so "4,000" stays
// one part rather than splitting into ["4", "000"] (which would otherwise
// be rejoined with the ja/zh ideographic comma → "4、000").
function _splitTopLevel(str, sep) {
    const parts = []; let depth = 0, cur = '';
    for (let i = 0; i < str.length; i++) {
        const ch = str[i];
        if (ch === '(') depth++;
        else if (ch === ')') depth--;
        if (ch === sep && depth === 0) {
            if (sep === ',' && i > 0 && i < str.length - 1
                && /\d/.test(str[i - 1]) && /\d/.test(str[i + 1])) {
                cur += ch;
                continue;
            }
            parts.push(cur); cur = '';
            continue;
        }
        cur += ch;
    }
    parts.push(cur);
    return parts;
}

// Strip variable letter/diacritic listings from common script qualifier
// patterns so we can match "with diacritics ḓ ḽ ṅ ṱ" against "with diacritics".
const _STRIP_PATTERNS = [
    /^(with diacritics)\s+\S.*$/,
    /^(with retroflexes)\s+\S.*$/,
    /^(with apostrophes for ejectives)\s.*$/,
    /^(with apostrophes for glottal stop)\s.*$/,
    /^(with apostrophes)\s+\S.*$/,
    /^(with click letters)\s+\S.*$/,
    /^(with click diacritics)\s+\S.*$/,
    /^(with diacritic tones)\s+\S.*$/,
    /^(with extra letters)\s+\S.*$/,
    /^(with tone diacritics)\s+\S.*$/,
];
function _stripQualifier(val) {
    for (const re of _STRIP_PATTERNS) {
        const m = val.match(re);
        if (m) return m[1];
    }
    return null;
}

function _lookup(val, dict, atoms) {
    if (dict[val]) return dict[val];
    if (atoms[val]) return atoms[val];
    const stripped = _stripQualifier(val);
    if (stripped) {
        if (dict[stripped]) return dict[stripped];
        if (atoms[stripped]) return atoms[stripped];
    }
    return null;
}

// Locale-appropriate separators for composed output. CJK use full-width
// parentheses and ideographic comma; everything else uses ASCII.
//
// lparen carries its own leading space. Composition is `left + lparen + inner`
// with left trimmed, so without it every Latin-script UI rendered
// "USA(Wyoming, Oklahoma)" and "~1K(kritisch gefährdet)" — correct text, wrong
// typography, on every composed value. Full-width （ needs no space, and
// Korean convention is deliberately closed up (영어(호주)), so both keep the
// bare form.
const _SEPS_DEFAULT = { lparen: ' (', rparen: ')', comma: ', ' };
const _SEPS = {
    ja:  { lparen: '（', rparen: '）', comma: '、' },
    zh:  { lparen: '（', rparen: '）', comma: '、' },
    yue: { lparen: '（', rparen: '）', comma: '、' },
    ko:  { lparen: '(', rparen: ')', comma: ', ' },
};

function _resolve(val, dict, atoms, seps) {
    if (val == null) return val;
    val = String(val).trim();
    if (!val) return val;

    const direct = _lookup(val, dict, atoms);
    if (direct !== null) return direct;

    // Approximate-date marker: let "~5th-10th c. CE" reuse an atom for
    // "5th-10th c. CE" when present.
    if (val.startsWith('~') && val.length > 1) {
        const rhs = _resolve(val.slice(1).trim(), dict, atoms, seps);
        if (rhs !== val.slice(1).trim()) return '~' + rhs;
    }

    // 1. Top-level comma split (countries: "X, Y, Z")
    const commaParts = _splitTopLevel(val, ',').map(s => s.trim()).filter(Boolean);
    if (commaParts.length > 1) {
        return commaParts.map(p => _resolve(p, dict, atoms, seps)).join(seps.comma);
    }

    // 2. Top-level semicolon split (speaker annotations: "X; Y; Z")
    const semiParts = _splitTopLevel(val, ';').map(s => s.trim()).filter(Boolean);
    if (semiParts.length > 1) {
        return semiParts.map(p => _resolve(p, dict, atoms, seps)).join('; ');
    }

    // 3. Top-level slash split (script alternates: "X / Y / Z")
    const slashParts = _splitTopLevel(val, '/').map(s => s.trim()).filter(Boolean);
    if (slashParts.length > 1) {
        return slashParts.map(p => _resolve(p, dict, atoms, seps)).join(' / ');
    }

    // 3b. Top-level em-dash split (region qualifiers: "X — Y", "X — Y, Z").
    //     Em-dashes separate a region from a sub-region or qualifier
    //     ("Chin State — Hakha township"). Only split when surrounded by
    //     spaces so we don't break "U+AA80–AADF" or "5th-10th c. CE" style
    //     ranges that use figure dashes / hyphens. Recurse on each side and
    //     re-assemble with the same separator.
    if (val.includes(' — ')) {
        const dashParts = _splitTopLevel(val, '—')
            .map((s, i, arr) => i === 0 || i === arr.length - 1 ? s : s)
            .map(s => s.trim())
            .filter(Boolean);
        // _splitTopLevel splits on single-char sep — verify we actually had
        // " — " (space-dash-space) at the top level by checking at least one
        // resulting part doesn't end/begin with a stray space-removed token.
        if (dashParts.length > 1) {
            const translated = dashParts.map(p => _resolve(p, dict, atoms, seps));
            // Only commit to the em-dash split if we translated at least one
            // part (otherwise the verbatim assembly is identical to input).
            const anyChanged = translated.some((t, i) => t !== dashParts[i]);
            if (anyChanged) return translated.join(' — ');
        }
    }

    // 4. Parenthetical: "X (Y)" — only if parens balance and there's exactly
    //    one top-level paren group at the end
    const parenMatch = val.match(/^([^()]+?)\s*\((.+)\)\s*$/);
    if (parenMatch) {
        const left = _resolve(parenMatch[1].trim(), dict, atoms, seps);
        const inner = _resolve(parenMatch[2].trim(), dict, atoms, seps);
        return left + seps.lparen + inner + seps.rparen;
    }

    // 5. Number-prefix peel: "~10 fluent", "1.5M L2 speakers" — strip the
    //    leading numeric quantity, recurse on the descriptor, prepend the
    //    quantity verbatim. Only for clear numeric prefixes; never for
    //    bare-word starts.
    const numPrefix = val.match(/^(~?\d+[\d.,–\-]*\s*[MKB]?\+?)\s+(.+)$/);
    if (numPrefix) {
        const rhs = _resolve(numPrefix[2].trim(), dict, atoms, seps);
        if (rhs !== numPrefix[2].trim()) return numPrefix[1] + ' ' + rhs;
    }

    // 6. Last-resort word composition for short qualifiers and region names
    //    such as "regional-population", "Han characters", or "with extra
    //    letters". Only use it when every substantial Latin word has a known
    //    atom, and at least one substantial word was translated.
    let translatedAny = false;
    let translatedLongWord = false;
    let failedWord = false;
    const wordComposed = val.replace(/[A-Za-z][A-Za-z.'’]*/g, (word) => {
        const hit = _lookup(word, dict, atoms);
        if (hit !== null) {
            translatedAny = true;
            if (word.length >= 3) translatedLongWord = true;
            return hit;
        }
        if (word.length < 3) return word;
        failedWord = true;
        return word;
    });
    if (translatedAny && translatedLongWord && !failedWord) return wordComposed;

    return val;
}

function translateMetaSmart(val, lang) {
    if (!val || lang === 'en') return val;
    const dict = (typeof META_I18N !== 'undefined' && META_I18N[lang]) || {};
    const atoms = (typeof META_I18N_ATOMS !== 'undefined' && META_I18N_ATOMS[lang]) || {};
    const seps = _SEPS[lang] || _SEPS_DEFAULT;
    return _resolve(val, dict, atoms, seps);
}

// === Atomic translation dictionary =========================================

// META_I18N_ATOMS is filled per-UI by meta_i18n/<ui>.js; create the global
// here so translateMetaSmart's bare reference resolves before that loads.
if (typeof window !== "undefined" && typeof window.META_I18N_ATOMS === "undefined") window.META_I18N_ATOMS = {};
if (typeof window !== "undefined") window.translateMetaSmart = translateMetaSmart;
