#!/usr/bin/env node
/*
 * build_lang_names.js — split lang_names.js into one file per UI language.
 *
 * lang_names.js holds translated names for 1,154 language codes in 19 UI
 * languages: ~200 KB gzipped, of which a reader uses ONE language (plus the
 * English fallback). Split it, and wordmap.html ships ~21 KB instead.
 *
 * Output: lang_names/<ui>.js, each a single call:
 *     window.__langNamesAdd('ja', { ... });
 * The receiver lives in lang_names_shim.js.
 *
 * lang_names.js itself is left alone — index.html, tree.html and hanmap.html
 * still load it whole. Only wordmap.html uses the split files.
 *
 * Run: node tools/build_lang_names.js           (writes lang_names/)
 *      node tools/build_lang_names.js --check   (prints "stale: N")
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const OUTDIR = path.join(ROOT, 'lang_names');

// lang_names.js declares `const LANG_NAMES = {...}` — pull the value out of the
// eval scope explicitly rather than expecting a global.
// eslint-disable-next-line no-eval
const LANG_NAMES = eval(fs.readFileSync(path.join(ROOT, 'lang_names.js'), 'utf8') + ';LANG_NAMES');

const CHECK = process.argv.includes('--check');
const uis = Object.keys(LANG_NAMES);
let stale = 0;

if (!CHECK) fs.mkdirSync(OUTDIR, { recursive: true });

for (const ui of uis) {
    const body = `/* GENERATED by tools/build_lang_names.js from lang_names.js. Do not edit. */\n`
        + `window.__langNamesAdd(${JSON.stringify(ui)}, ${JSON.stringify(LANG_NAMES[ui])});\n`;
    const out = path.join(OUTDIR, `${ui}.js`);
    if (CHECK) {
        const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
        if (cur !== body) { stale++; console.error(`stale: lang_names/${ui}.js`); }
    } else {
        fs.writeFileSync(out, body);
    }
}

// Anything left over from a removed UI language would silently keep serving.
if (fs.existsSync(OUTDIR)) {
    for (const f of fs.readdirSync(OUTDIR)) {
        const ui = f.replace(/\.js$/, '');
        if (!uis.includes(ui)) {
            if (CHECK) { stale++; console.error(`stale: lang_names/${f} has no counterpart in lang_names.js`); }
            else fs.unlinkSync(path.join(OUTDIR, f));
        }
    }
}

if (CHECK) { console.log(`stale: ${stale}`); process.exit(0); }
console.log(`lang_names/: ${uis.length} files written (${uis.join(', ')})`);
