/**
 * Indo-European never settled on a single word for 'bird': English bird descends from Old English bridd (originally 'young bird, nestling'), German keeps Vogel, while Latin avis fed the Romance ave/pájaro/uccello tangle and Slavic runs on ptica/ptak — a striking case of a basic, universal concept built from wholly divergent roots. Elsewhere the picture is tidier: Sino-Tibetan centres on 鳥/niǎo, Austronesian reflexes trace to *manuk (though Malay has burung), and Bantu spreads *-nyʊnɪ (Zulu inyoni, Kikuyu nyoni), with Swahili's ndege an innovation.
 */
WORDS.bird = {
  emoji: "🐦",
  label: {
    en: "Bird",
    ja: "鳥",
    ko: "새",
    zh: "鸟",
    yue: "鳥",
    vi: "Chim",
    th: "นก",
    id: "Burung",
    hi: "पक्षी",
    de: "Vogel",
    fr: "Oiseau",
    it: "Uccello",
    es: "Pájaro",
    es_eu: "Pájaro",
    es_mx: "Pájaro",
    pt: "Pássaro",
    pt_eu: "Pássaro",
    pt_br: "Pássaro",
    ru: "Птица",
    uk: "Птах",
    ar: "طائر",
    he: "ציפור",
    sw: "Ndege",
  },
  definition: {
    en: "Bird — a feathered, winged, egg-laying animal (the general category); not a specific species.",
    ja: "鳥 — 羽毛と翼をもち、卵を産む動物の総称。特定の種ではなく、カテゴリー全体を指す。",
    ko: "새 — 깃털과 날개가 있고 알을 낳는 동물의 총칭. 특정 종이 아니라 전체 부류를 가리킨다.",
    zh: "鸟 — 有羽毛和翅膀、会下蛋的动物的总称；指整个类别，而非某一特定物种。",
    yue: "鳥 — 有羽毛同翼、會生蛋嘅動物嘅統稱；指成個類別，唔係某一種雀。",
    vi: "Chim — loài động vật có lông vũ, có cánh và đẻ trứng (phạm trù chung); không phải một loài cụ thể.",
    th: "นก — สัตว์มีขน มีปีก และออกไข่ (หมวดหมู่ทั่วไป) ไม่ใช่ชนิดใดชนิดหนึ่งโดยเฉพาะ",
    id: "Burung — hewan berbulu, bersayap, dan bertelur (kategori umum); bukan spesies tertentu.",
    hi: "पक्षी — पंख और डैनों वाला, अंडे देने वाला प्राणी (सामान्य श्रेणी); कोई विशिष्ट प्रजाति नहीं।",
    de: "Vogel — ein gefiedertes, geflügeltes, eierlegendes Tier (die allgemeine Kategorie); keine bestimmte Art.",
    fr: "Oiseau — animal à plumes, ailé et pondeur d'œufs (la catégorie générale) ; pas une espèce en particulier.",
    it: "Uccello — animale con piume, alato e che depone uova (la categoria generale); non una specie particolare.",
    es: "Pájaro — animal con plumas, alas y que pone huevos (la categoría general); no una especie concreta.",
    es_eu: "Pájaro — animal con plumas, alas y que pone huevos (la categoría general); no una especie concreta.",
    es_mx: "Pájaro — animal con plumas, alas y que pone huevos (la categoría general); no una especie en concreto.",
    pt: "Pássaro — animal com penas, asas e que põe ovos (a categoria geral); não uma espécie específica.",
    pt_eu: "Pássaro — animal com penas, asas e que põe ovos (a categoria geral); não uma espécie específica.",
    pt_br: "Pássaro — animal com penas, asas e que põe ovos (a categoria geral); não uma espécie específica.",
    ru: "Птица — покрытое перьями крылатое животное, откладывающее яйца (общая категория); не конкретный вид.",
    uk: "Птах — вкрита пір'ям крилата тварина, що відкладає яйця (загальна категорія); не конкретний вид.",
    ar: "طائر — حيوان مكسوّ بالريش، له جناحان ويبيض (الفئة العامة)؛ وليس نوعًا بعينه.",
    he: "ציפור — בעל חיים מכוסה נוצות ובעל כנפיים שמטיל ביצים (הקטגוריה הכללית); לא מין מסוים.",
    sw: "Ndege — mnyama mwenye manyoya na mabawa anayetaga mayai (jamii ya jumla); si spishi maalum.",
  },
  data: {
    es_cr: ["pájaro", "ˈpaxaɾo"],
    es_hn: ["pájaro", "ˈpaxaɾo"],
    es_ni: ["pájaro", "ˈpaxaɾo"],
    es_sv: ["pájaro", "ˈpaxaɾo"],
    pt_mo: ["pássaro", "ˈpasaɾu"],
    lb: ["Vugel", "ˈvuɡəl"],
    gcr: ["zwazo", "zwazo"],
    acf: ["zwezo", "zwezo"],
    ik: ["tiŋmiaq", "tiŋmiaq"],
    es_bo: ["pájaro", "ˈpaxaɾo"],
    es_py: ["pájaro", "ˈpaxaɾo"],
    es_pa: ["pájaro", "ˈpaxaɾo"],
    en_my: ["bird", "bɜːd"],
    es_pr: ["pájaro", "ˈpaxaɾo"],
    es_do: ["pájaro", "ˈpaxaɾo"],
    es_gt: ["pájaro", "ˈpaxaɾo"],
    es_ec: ["pájaro", "ˈpaxaɾo"],
    es_uy: ["pájaro", "ˈpaxaɾo"],
    en_ng: ["bird", "bɜːd"],
    en_ph: ["bird", "bɜːd"],
    en_ke: ["bird", "bɜːd"],
    pt_mz: ["pássaro", "ˈpasaɾu"],
    nl_be: ["vogel", "ˈvoːɣəl"],
    en_us: ["bird", "bɝd"],
    en_ca: ["bird", "bɝd"],
    en_za: ["bird", "bɜːd"],
    de_ch: ["Vogel", "ˈfoːɡl̩"],
    pt_ao: ["pássaro", "ˈpasaɾu"],
    es_ve: ["pájaro", "ˈpaxaɾo"],
    ca_va: ["ocell", "oˈseʎ"],
    ja: ["鳥", "toɾi"],
    ja_osa: ["鳥", "toɾi"],
    ja_aom: ["鳥", "toɾi"],
    ja_oki: ["鳥", "tui"],
    ja_hak: ["鳥", "toɾi"],
    ja_kyo: ["鳥", "toɾi"],
    ja_hir: ["鳥", "toɾi"],
    ko: ["새", "sɛ"],
    ko_kp: ["새", "sɛ"],
    ko_bus: ["새", "sɛ"],
    ko_yb: ["새", "sɛ"],
    zh: ["鸟", "niau²¹⁴"],
    yue: ["鳥", "niːu²³"],
    nan: ["鳥", "tsiau⁵³"],
    zh_tw: ["鳥", "niau²¹⁴"],
    vi: ["chim", "cim"],
    vi_c: ["chim", "cim"],
    vi_s: ["chim", "cim"],
    th: ["นก", "nók"],
    id: ["burung", "buruŋ"],
    ms: ["burung", "buruŋ"],
    hi: ["पक्षी", "pəkʂiː"],
    bn: ["পাখি", "pakʰi"],
    ur: ["پرندہ", "parɪndaː"],
    ta: ["பறவை", "paɾavai"],
    en: ["bird", "bɜːrd"],
    de: ["Vogel", "ˈfoːɡl̩"],
    fr: ["oiseau", "wazo"],
    it: ["uccello", "utˈtʃɛllo"],
    es: ["pájaro", "ˈpaxaɾo"],
    es_mx: ["pájaro", "ˈpaxaɾo"],
    pt: ["pássaro", "ˈpasɐɾu"],
    pt_br: ["pássaro", "ˈpasaɾu"],
    ru: ["птица", "ˈptʲitsə"],
    ar: ["طائر", "tˤaːʔir"],
    he: ["ציפור", "tsiˈpoʁ"],
    tr: ["kuş", "kuʃ"],
    fa: ["پرنده", "parande"],
    prs: ["پرنده", "parinda"],
    sw: ["ndege", "ndeɡe"],
    tl: ["ibon", "ʔiˈbon"],
    mn: ["шувуу", "ʃuwuː"],
    tyv: ["куш", "kuʃ"],
    alt: ["куш", "kuʃ"],
    cv: ["кайăк", "kajək"],
    bxr: ["шубуун", "ʃubuːn"],
    my: ["ငှက်", "ɲɛʔ"],
    lo: ["ນົກ", "nok"],
    yo: ["ẹyẹ", "ɛjɛ"],
    zu: ["inyoni", "iˈɲoni"],
    am: ["ወፍ", "wəf"],
    mg: ["vorona", "ˈvurunə"],
    ain: ["cikap", "tʃikap"],
    fi: ["lintu", "ˈlintu"],
    hu: ["madár", "ˈmɒdaːr"],
    el: ["πουλί", "puˈli"],
    nl: ["vogel", "ˈvoːɣəl"],
    pl: ["ptak", "ptak"],
    szl: ["ptok", "ptɔk"],
    uk: ["птах", "ptɑx"],
    sv: ["fågel", "ˈfoːɡɛl"],
    no: ["fugl", "fʉːɡl"],
    da: ["fugl", "ˈfuˀl"],
    ro: ["pasăre", "ˈpasəre"],
    ga: ["éan", "eːnˠ"],
    cy: ["aderyn", "aˈdɛrɨn"],
    ka: ["ჩიტი", "tʃʰitʰi"],
    hy: ["թռչուն", "tʰərtʃʰun"],
    hyw: ["թռչուն", "tʰərtʃʰun"],
    nv: ["tsídii", "tsídiː"],
    haw: ["manu", "ˈmanu"],
    mi: ["manu", "ˈmanu"],
    bo: ["བྱ", "tʃʰa"],
    th_isan: ["นก", "nók"],
    th_n: ["นก", "nók"],
    th_s: ["นก", "nók"],
    jv: ["manuk", "manʊʔ"],
    jvn: ["manuk", "manʊʔ"],
    su: ["manuk", "manuk"],
    ceb: ["langgam", "laŋˈɡam"],
    ilo: ["billit", "bilˈlit"],
    sd: ["پکي", "pəkʰiː"],
    pa: ["ਪੰਛੀ", "pəntʃʰiː"],
    ne: ["चरा", "tsʌra"],
    mr: ["पक्षी", "pəkʂiː"],
    gu: ["પક્ષી", "pəkʂiː"],
    si: ["කුරුල්ලා", "kurulːaː"],
    dv: ["ދޫނި", "ɖuːni"],
    te: ["పక్షి", "pakʂi"],
    kn: ["ಹಕ್ಕಿ", "hakːi"],
    ml: ["പക്ഷി", "pakʂi"],
    tg: ["паранда", "paranda"],
    ku: ["balinde", "balinde"],
    ckb: ["باڵنده", "baːɫɪnde"],
    az: ["quş", "ɡuʃ"],
    azb: ["قوش", "ɡuʃ"],
    gag: ["kuş", "kuʃ"],
    ug: ["قۇش", "quʃ"],
    kk: ["құс", "qus"],
    ky: ["куш", "kuʃ"],
    uz: ["qush", "quʃ"],
    tk: ["guş", "ɡuʃ"],
    ar_eg: ["عصفور", "ʕasˤfuːr"],
    ti: ["ዑፍ", "ʕuf"],
    mt: ["għasfur", "aːsˈfur"],
    ig: ["nnụnụ", "nːʊnʊ"],
    ha: ["tsuntsu", "tsúntsúː"],
    wo: ["picc", "pitʃ"],
    so: ["shimbir", "ʃimbir"],
    om: ["simbirroo", "simbirroː"],
    rw: ["inyoni", "iˈɲoni"],
    rn: ["inyoni", "iˈɲoni"],
    xh: ["intaka", "inˈtaka"],
    sn: ["shiri", "ʃiri"],
    ln: ["ndeke", "ndɛkɛ"],
    ny: ["mbalame", "mɓaˈlame"],
    en_aave: ["bird", "bɜːd"],
    en_nz: ["bird", "bɜːd"],
    en_au: ["bird", "bɜːd"],
    sco: ["bird", "bɪrd"],
    af: ["voël", "fuəl"],
    de_at: ["Vogel", "ˈfoːɡl̩"],
    nds: ["Vagel", "ˈfaːɣəl"],
    is: ["fugl", "fʏɣl̥"],
    gd: ["eun", "ian"],
    br: ["evn", "ẽːvn"],
    nap: ["auciello", "auˈtʃiɛllə"],
    scn: ["aceddu", "aˈtʃɛɖːu"],
    co: ["uccellu", "utˈtʃɛllu"],
    ca: ["ocell", "uˈseʎ"],
    gl: ["paxaro", "ˈpaʃaɾo"],
    oc: ["aucèl", "auˈsɛl"],
    be: ["птушка", "ˈptuʂka"],
    cs: ["pták", "ptaːk"],
    sk: ["vták", "ftaːk"],
    sl: ["ptica", "ˈptiːtsa"],
    bg: ["птица", "ˈptitsɐ"],
    lt: ["paukštis", "ˈpɐuːkʃtɪs"],
    lv: ["putns", "ˈputns"],
    sq: ["zog", "zɔɡ"],
    et: ["lind", "linˑd"],
    ht: ["zwazo", "zwazo"],
    pap: ["para", "ˈpara"],
    tpi: ["pisin", "ˈpisin"],
    se: ["loddi", "ˈlottiː"],
    gn: ["guyra", "ɡʷɨɾa"],
    chr: ["ᏥᏍᏆ", "tʃisɡʷa"],
    as: ["চৰাই", "sɔɹai"],
    or: ["ପକ୍ଷୀ", "pɔkʰːiː"],
    bho: ["चिरई", "tʃirɛi"],
    en_in: ["bird", "bɜːd"],
    en_ie: ["bird", "bɜːd"],
    en_sg: ["bird", "bɜːd"],
    fy: ["fûgel", "ˈfuːɡəl"],
    nn: ["fugl", "fʉːɡl"],
    fo: ["fuglur", "ˈfuːlʊɹ"],
    fr_qc: ["oiseau", "wazo"],
    fr_be: ["oiseau", "wazo"],
    fr_ch: ["oiseau", "wazo"],
    es_co: ["pájaro", "ˈpaxaɾo"],
    es_cl: ["pájaro", "ˈpaxaɾo"],
    es_ar: ["pájaro", "ˈpaxaɾo"],
    es_cu: ["pájaro", "ˈpaxaɾo"],
    es_pe: ["pájaro", "ˈpaxaɾo"],
    es_an: ["pájaro", "ˈpaxaɾo"],
    rm: ["utschè", "uˈtʃɛ"],
    iu: ["ᑎᖕᒥᐊᖅ", "tiŋmiaq"],
    nhe: ["tototl", "ˈtototɬ"],
    ngu: ["tototl", "ˈtototɬ"],
    eo: ["birdo", "ˈbirdo"],
    vo: ["böd", "bød"],
    ia: ["ave", "ˈave"],
    tok: ["waso", "ˈwaso"],
    jbo: ["cipni", "ˈʃipni"],
    mai: ["चिड़ै", "tʃiɽɛː"],
    hil: ["pispis", "pisˈpis"],
    ak: ["anoma", "aˈnoma"],
    mk: ["птица", "ˈptitsa"],
    lg: ["ennyonyi", "eɲːoˈɲi"],
    ki: ["nyoni", "ˈɲoni"],
    tn: ["nonyane", "nɔˈɲanɛ"],
    st: ["nonyana", "nʊˈɲana"],
    ts: ["xinyenyana", "ʃiɲeˈɲana"],
    kg: ["nuni", "ˈnuni"],
    ff: ["sonndu", "sonndu"],
    bm: ["kɔnɔ", "kɔnɔ"],
    yua: ["chʼíichʼ", "tʃʼiːtʃʼ"],
    ay: ["jamachʼi", "hamatʃʼi"],
    kl: ["timmiaq", "timmiaq"],
    os: ["маргъ", "marʁ"],
    ty: ["manu", "ˈmanu"],
    mh: ["bao", "pˠɑoː"],
    ch: ["paluma", "paˈluma"],
    tet: ["manu", "manu"],
    dz: ["བྱ", "bja"],
    min: ["buruang", "buruaŋ"],
    ban: ["kedis", "kədis"],
    fur: ["ucel", "uˈtʃel"],
    ast: ["páxaru", "ˈpaʃaɾu"],
    mhr: ["кайык", "kajək"],
    crh: ["quş", "quʃ"],
    tt: ["кош", "qoʃ"],
    ba: ["ҡош", "qoʃ"],
    ee: ["xevi", "xeʋi"],
    gv: ["ushag", "ʊʒaɡ"],
    hr: ["ptica", "ptitsa"],
    bs: ["ptica", "ptitsa"],
    umb: ["onjila", "oˈɲila"],
    xal: ["шовун", "ʃowun"],
    mfe: ["zwazo", "zwazo"],
    srn: ["fowru", "ˈfoːru"],
    kaa: ["qus", "qus"],
    quc: ["tzʼikin", "tsʼikin"],
    cak: ["tzʼikin", "tsʼikin"],
    io: ["ucelo", "uˈtselo"],
    gsw: ["Vogel", "ˈfoːɡl̩"],
    yi: ["פֿויגל", "fɔjɡl"],
    pcm: ["bird", "bɛd"],
    sr: ["птица", "ptîtsa"],
    rue: ["птах", "ptax"],
    hsb: ["ptačk", "ptatʃk"],
    aae: ["zog", "zɔɡ"],
    zh_db: ["鸟", "niau²¹⁴"],
    zh_sc: ["鸟", "niau²¹⁴"],
    hak_cn: ["鸟", "tiau⁵³"],
    wuu: ["鸟", "ɲiɔ²³"],
    za: ["roeg", "ɣok⁸"],
    km: ["សត្វស្លាប", "sɑt slaːp"],
    hmn: ["noog", "nɔ̃ŋ"],
    sm: ["manu", "ˈmanu"],
    rom: ["čirikli", "tʃirikli"],
    ar_lev: ["عصفور", "ʕasˤfuːr"],
    ar_sy: ["عصفور", "ʕasˤfuːr"],
    ar_lb: ["عصفور", "ʕasˤfuːr"],
    ar_ps: ["عصفور", "ʕasˤfuːr"],
    ar_jo: ["عصفور", "ʕasˤfuːr"],
    eu: ["txori", "tʃoɾi"],
    lkt: ["ziŋtkála", "zĩˈtkala"],
    qu: ["pisqu", "pisqu"],
    fr_lu: ["oiseau", "wazo"],
    fr_cm: ["oiseau", "wazo"],
    fr_sn: ["oiseau", "wazo"],
    fr_ci: ["oiseau", "wazo"],
    fr_ht: ["oiseau", "wazo"],
    fr_af: ["oiseau", "wazo"],
    en_sco: ["bird", "bɝd"],
    en_south: ["bird", "bɝd"],
    en_app: ["bird", "bɝd"],
    en_wls: ["bird", "bɜːd"],
    en_ng2: ["bird", "bɜːd"],
    en_yk: ["bird", "bɜːd"],
    en_ck: ["bird", "bɜːd"],
    en_scouse: ["bird", "bɜːd"],
    en_geordie: ["bird", "bɜːd"],
    en_brum: ["bird", "bɜːd"],
    en_manc: ["bird", "bɜːd"],
    en_wc: ["bird", "bɜːd"],
    en_est: ["bird", "bɜːd"],
    en_jam: ["bird", "bɜːd"],
    de_lu: ["Vogel", "foːɡl̩"],
    swg: ["Vogel", "foːɡl̩"],
    bar: ["Vogl", "foːɡl̩"],
    vmf: ["Vogel", "foːɡl̩"],
    ksh: ["Vugel", "fʊɡəl"],
    pdc: ["Voggel", "fɔɡəl"],
    pdt: ["Voagel", "foəɡəl"],
    li: ["veugel", "ˈvøːɣəl"],
    vls: ["veugel", "vøːɣəl"],
    pt_cv: ["pássaro", "pasɐɾu"],
    vec: ["oxeło", "ozeło"],
    sc: ["pilloni", "pilːɔni"],
    lij: ["öxello", "øʒelu"],
    pms: ["osel", "uˈzɛl"],
    an: ["paxaro", "paʃaɾo"],
    lad: ["pásharo", "paʃaɾo"],
    csb: ["ptôch", "ptɔx"],
    dsb: ["ptaška", "ptaʂka"],
    sgs: ["paukštis", "paukʃtis"],
    ltg: ["putns", "putns"],
    smj: ["lådde", "lɔtɛ"],
    krl: ["lintu", "lintu"],
    olo: ["lindu", "lindu"],
    vep: ["lind", "lind"],
    fit: ["lintu", "lintu"],
    fkv: ["lintu", "lintu"],
    pnt: ["πουλίν", "pulin"],
    kw: ["edhen", "ɛðɛn"],
    aln: ["zog", "zɔɡ"],
    haz: ["پرنده", "paɾanda"],
    ps: ["مرغه", "marɣa"],
    sah: ["көтөр", "køtør"],
    pnb: ["پنچھی", "pəntʃʰiː"],
    ja_kg: ["鳥", "toɾi"],
    ja_sd: ["鳥", "toɾi"],
    ko_hg: ["새", "sɛ"],
    ko_jl: ["새", "sɛ"],
    ko_jeju: ["생이", "sɛŋi"],
    rki: ["ငှက်", "ŋaɪʔ"],
    bjn: ["burung", "buruŋ"],
    bew: ["burung", "buruŋ"],
    iba: ["burung", "buruŋ"],
    mad: ["mano'", "manoʔ"],
    ace: ["cicém", "tʃitʃem"],
    cbk: ["pajaro", "paxaɾo"],
    niu: ["manu", "manu"],
    tvl: ["manu", "manu"],
    tkl: ["manu", "manu"],
    rap: ["manu", "manu"],
    rar: ["manu", "manu"],
    mrq: ["manu", "manu"],
    wls: ["manu", "manu"],
    fud: ["manu", "manu"],
    pkp: ["manu", "manu"],
    to: ["manupuna", "manupuna"],
    gil: ["mannikiba", "mannikiba"],
    fj: ["manumanu", "manumanu"],
    ssw: ["inyoni", "iɲoni"],
    nd: ["inyoni", "iɲoni"],
    nbl: ["inyoni", "iɲoni"],
    nso: ["nonyana", "nʊɲana"],
    ndc: ["shiri", "ʃiri"],
    mxc: ["shiri", "ʃiri"],
    luo: ["winyo", "wiɲo"],
    sg: ["ndeke", "ndeke"],
    dyu: ["kɔnɔ", "kɔnɔ"],
    emk: ["kɔnɔ", "kɔnɔ"],
    mwk: ["kɔnɔ", "kɔnɔ"],
    mlq: ["kɔnɔ", "kɔnɔ"],
    mnk: ["kunoo", "kunoː"],
    ce: ["олхазар", "olxazar"],
    dak: ["zitkána", "zitˈkana"],
    oj: ["bineshiinh", "binɛʃiːnʲ"],
    mic: ["sisip", "sisip"],
    hop: ["tsiro", "tsiro"],
    nhx: ["tototl", "tototɬ"],
    nch: ["tototl", "tototɬ"],
    nhw: ["tototl", "tototɬ"],
    ppl: ["tutut", "tutut"],
    mixtec: ["saa", "saa"],
    mix: ["saa", "saa"],
    mxv: ["saa", "saa"],
    quz: ["pisqu", "pisqu"],
    quy: ["pisqu", "pisqu"],
    gun: ["guyra", "ɡwɨɾa"],
    yrl: ["wirá", "wiˈɾa"],
    arn: ["üñüm", "ɯɲɯm"],
    jiv: ["chinki", "tʃiŋki"],
    acu: ["chinki", "tʃiŋki"],
    gcf: ["zwazo", "zwazo"],
    crs: ["zwazo", "zwazo"],
    rcf: ["zwazo", "zwazo"],
    kea: ["pásaru", "pasaɾu"],
    kri: ["bɛd", "bɛd"],
    bi: ["pijin", "pidʒin"],
    ho: ["manu", "manu"],
    tlh: ["bo'Degh", "boʔɖɛɣ"],
    ar_ma: ["طير", "tˤiːr"],
    arq: ["طير", "tˤiːr"],
    ayl: ["طير", "tˤiːr"],
    ar_sd: ["طير", "tˤiːr"],
    rup: ["pulj", "ˈpuʎu"],
    frr: ["fögel", "ˈføːɡəl"],
    hwc: ["bird", "bɜd"],
    sma: ["ledtie", "ˈleːtie"],
    vot: ["lintu", "ˈlintu"],
    liv: ["lind", "lind"],
    kpv: ["лэбач", "lɛbatɕ"],
    udm: ["тылобурдо", "tɨloburdo"],
    myv: ["нармунь", "narmunʲ"],
    mdf: ["нармонь", "narmonʲ"],
    kjh: ["хус", "xus"],
    kum: ["къуш", "quʃ"],
    mn_cn: ["ᠰᠢᠪᠠᠭᠤ", "ʃʊwuː"],
    mnc: ["ᡤᠠᠰᡥᠠ", "ɢasχa"],
    sjo: ["ᡤᠠᠰᡥᠠ", "ɢasχa"],
    zh_jh: ["鸟", "niau"],
    zh_tj: ["鸟", "niau"],
    zh_lz: ["鸟", "niau"],
    zh_wh: ["鸟", "niau"],
    zh_zz: ["鸟", "niau"],
    zh_cq: ["鸟", "niau"],
    zh_jn: ["鸟", "niau"],
    zh_km: ["鸟", "niau"],
    zh_xa: ["鸟", "niau"],
    zh_cd: ["鸟", "niau"],
    zh_hf: ["鸟", "niau"],
    zh_kf: ["鸟", "niau"],
    zh_nj: ["鸟", "niau"],
    cjy: ["鸟", "niau"],
    cjy_lv: ["鸟", "niau"],
    cjy_xz: ["鸟", "niau"],
    hsn: ["鸟", "niau"],
    nan_pn: ["鳥", "tsiau"],
    nan_qz: ["鳥", "tsiau"],
    nan_xm: ["鳥", "tsiau"],
    nan_zz: ["鳥", "tsiau"],
    nan_hai: ["鸟", "tsiau"],
    nan_te: ["鸟", "tsiau"],
    cdo: ["鸟", "tsiau"],
    mnp: ["鸟", "tsiau"],
    cpx: ["鸟", "tsiau"],
    hak_tw: ["鳥", "tiau"],
    hak_hl: ["鳥", "tiau"],
    wuu_nb: ["鸟", "ɲiɔ"],
    wuu_sz: ["鸟", "ɲiɔ"],
    wuu_hz: ["鸟", "ɲiɔ"],
    wuu_jh: ["鸟", "ɲiɔ"],
    wuu_jx: ["鸟", "ɲiɔ"],
    wuu_wz: ["鸟", "ȵau"],
    shn: ["ၼူၵ်ႉ", "nok"],
    kok: ["सुकणें", "sukɳẽ"],
    syl: ["পাখি", "paxi"],
    bgc: ["चिड़िया", "tʃiɽija"],
    tcy: ["ಪಕ್ಕಿ", "pakːi"],
    aii: ["ܛܲܝܪܵܐ", "tˤajra"],
    tzm: ["agḍiḍ", "aɡdˤidˤ"],
    nyn: ["ekinyonyi", "ekiɲoɲi"],
    efi: ["inuen", "inuen"],
    ibb: ["inuen", "inuen"],
    inh: ["оалхазар", "walxazar"],
    ady: ["бзыу", "bzəw"],
    kbd: ["бзу", "bzu"],
    tzo: ["mut", "mut"],
    tzh: ["mut", "mut"],
    win: ["wanįk", "wanĩk"],
    pmt: ["manu", "ˈmanu"],
    meu: ["manu", "ˈmanu"],
    abs: ["burung", "buruŋ"],
    max: ["burung", "buruŋ"],
    mui: ["burung", "buruŋ"],
    pmy: ["burung", "buruŋ"],
    bbc: ["pidong", "pidoŋ"],
    lus: ["sava", "sava"],
    grt: ["doʼo", "doʔo"],
    mni: ["ꯎꯆꯦꯛ", "utʃek"],
  },
};
