/**
 * cuckoo — see docs/words/CONTRIBUTING.md for editing guidance.
 * PARTIAL WORD (WORDS.cuckoo.partial === true): plotted only where a real,
 * sourced form exists. The common cuckoo's range is Eurasia + Africa, so
 * coverage thins out in the Americas and the remote Pacific by design — the
 * map shows the bird's range.
 */
WORDS.cuckoo = {
  partial: true,
  label: {
    en: "Cuckoo", ja: "カッコウ", ko: "뻐꾸기", zh: "布谷鸟", yue: "布穀鳥",
    vi: "Chim cu cu", th: "นกคัคคู", id: "Burung kangkok", hi: "कोयल",
    de: "Kuckuck", fr: "Coucou", it: "Cuculo", es: "Cuco", es_eu: "Cuco",
    es_mx: "Cuco", pt: "Cuco", pt_eu: "Cuco", pt_br: "Cuco",
    ru: "Кукушка", uk: "Зозуля", ar: "وقواق", he: "קוקייה", sw: "Kekeo",
  },
  definition: {
    en: "The common cuckoo (Cuculus canorus) or a bird of the cuckoo family (Cuculidae) — the grey bird whose two-note call names it in many languages. NOT the cuckoo clock and NOT 'crazy'. Where a language distinguishes the common cuckoo from the koel, prefer the common-cuckoo word.",
    ja: "カッコウ (Cuculus canorus) またはカッコウ科 (Cuculidae) の鳥。その二音の鳴き声が多くの言語で名前の由来となった灰色の鳥。鳩時計や「頭がおかしい」の意味ではない。",
    ko: "뻐꾸기 (Cuculus canorus) 또는 두견이과 (Cuculidae)의 새. 두 음절 울음소리가 여러 언어에서 이름의 유래가 된 회색 새.",
    zh: "大杜鹃／布谷鸟 (Cuculus canorus) 或杜鹃科 (Cuculidae) 的鸟——其两音节叫声在许多语言中成为名称来源的灰色鸟。不是布谷鸟钟，也不是「疯」。",
    yue: "大杜鵑／布穀鳥 (Cuculus canorus) 或杜鵑科嘅雀——牠兩個音嘅叫聲喺好多語言入面成為名稱嘅來源。唔係布穀鳥鐘，亦唔係「癲」。",
    vi: "Chim cu cu (Cuculus canorus) hay loài thuộc họ Cuculidae — loài chim xám mà tiếng kêu hai nốt đặt tên cho nó trong nhiều ngôn ngữ. KHÔNG phải đồng hồ, KHÔNG phải 'điên'.",
    th: "นกคัคคูหรือนกดุเหว่า (Cuculus canorus) วงศ์ Cuculidae — นกสีเทาที่เสียงร้องสองพยางค์เป็นที่มาของชื่อในหลายภาษา ไม่ใช่นาฬิกา ไม่ใช่ 'บ้า'",
    id: "Burung kangkok (Cuculus canorus) atau anggota suku Cuculidae — burung kelabu yang bunyi dua-nada-nya menjadi asal namanya di banyak bahasa. BUKAN jam, BUKAN 'gila'.",
    hi: "कोयल/कुक्कू (Cuculus canorus) या Cuculidae कुल का पक्षी — जिसकी दो-स्वर बोली से अनेक भाषाओं में इसका नाम बना। घड़ी या 'पागल' नहीं।",
    de: "Der Kuckuck (Cuculus canorus) oder ein Vogel der Familie Cuculidae — der Vogel, dessen zweitöniger Ruf ihm in vielen Sprachen den Namen gab. NICHT die Uhr, NICHT 'verrückt'.",
    fr: "Le coucou gris (Cuculus canorus) ou un oiseau de la famille des Cuculidae — l'oiseau dont le cri à deux notes lui donne son nom dans de nombreuses langues. PAS l'horloge, PAS 'fou'.",
    it: "Il cuculo (Cuculus canorus) o un uccello della famiglia Cuculidae — l'uccello il cui richiamo a due note gli dà il nome in molte lingue. NON l'orologio, NON 'matto'.",
    es: "El cuco común (Cuculus canorus) o un ave de la familia Cuculidae — cuyo canto de dos notas le da nombre en muchas lenguas. NO el reloj, NO 'loco'.",
    es_eu: "El cuco común (Cuculus canorus) o un ave de la familia Cuculidae — cuyo canto de dos notas le da nombre en muchas lenguas. NO el reloj, NO 'loco'.",
    es_mx: "El cuco común (Cuculus canorus) o un ave de la familia Cuculidae — cuyo canto de dos notas le da nombre en muchas lenguas. NO el reloj, NO 'loco'.",
    pt: "O cuco-canoro (Cuculus canorus) ou uma ave da família Cuculidae — cujo canto de duas notas lhe dá o nome em muitas línguas. NÃO o relógio, NÃO 'louco'.",
    pt_eu: "O cuco-canoro (Cuculus canorus) ou uma ave da família Cuculidae — cujo canto de duas notas lhe dá o nome em muitas línguas. NÃO o relógio, NÃO 'louco'.",
    pt_br: "O cuco (Cuculus canorus) ou uma ave da família Cuculidae — cujo canto de duas notas lhe dá o nome em muitas línguas. NÃO o relógio, NÃO 'louco'.",
    ru: "Обыкновенная кукушка (Cuculus canorus) или птица семейства кукушковых (Cuculidae) — серая птица, чей двусложный крик дал ей имя во многих языках. НЕ часы, НЕ 'сумасшедший'.",
    uk: "Зозуля звичайна (Cuculus canorus) або птах родини зозулевих (Cuculidae) — сірий птах, чий двоскладовий крик дав йому назву в багатьох мовах. НЕ годинник, НЕ 'божевільний'.",
    ar: "الوَقْوَاق (Cuculus canorus) أو طائر من فصيلة الوقواقيات (Cuculidae) — الطائر الرمادي الذي سمّاه صوته ذو النغمتين في كثير من اللغات. ليس ساعة ولا 'مجنون'.",
    he: "הקוקייה (Cuculus canorus) או ציפור ממשפחת הקוקיים (Cuculidae) — הציפור האפורה שקריאתה בת שני הצלילים העניקה לה את שמה בשפות רבות. לא שעון ולא 'מטורף'.",
    sw: "Kekeo (Cuculus canorus) au ndege wa familia ya Cuculidae — ndege wa kijivu ambaye mlio wake wa noti mbili ulimpa jina katika lugha nyingi. SIYO saa wala 'kichaa'.",
  },
  data: {
    es_cr: ["tijo", "ˈtixo"],
    es_hn: ["tijul", "tiˈxul"],
    es_ni: ["tijul", "tiˈhul"],
    es_sv: ["cuco", "ˈkuko"],
    ar_jo: ["وَقْوَاق", "waqˈwaːq"],
    ar_ps: ["وَقْوَاق", "waqˈwaːq"],
    fr_lu: ["coucou", "kuku"],
    fr_cm: ["coucou", "kuku"],
    de_lu: ["Kuckuck", "ˈkʊkʊk"],
    en_ng2: ["cuckoo", "ˈkʊkuː"],
    pt_mo: ["cuco", "ˈkuku"],
    lb: ["Guckuck", "ˈɡukuk"],
    hop: ["hospoa", "hosˈpoa"],
    com: ["—", "—"],
    es_bo: ["serere", "seˈɾeɾe"],
    es_py: ["piririta", "piɾiˈɾita"],
    es_pa: ["garrapatero", "ɡarapaˈteɾo"],
    en_my: ["cuckoo", "ˈkʊkuː"],
    khw: ["کاکو", "ˈkaːku"],
    ake: ["pika", "piˈka"],
    aoc: ["pika", "ˈpika"],
    ayl: ["وَقْوَاق", "waqˈwaːq"],
    abv: ["وَقْوَاق", "waqˈwaːq"],
    afb: ["وَقْوَاق", "waqˈwaːq"],
    acw: ["وَقْوَاق", "waqˈwaːq"],
    slr: ["guguk", "kukux"],
    cjs: ["кӧӧк", "køːk"],
    es_pr: ["pájaro bobo", "ˈpahaɾo ˈβoβo"],
    es_do: ["pájaro bobo", "ˈpaxaɾo ˈβoβo"],
    es_gt: ["pijuy", "piˈxwi"],
    es_ec: ["garrapatero", "ɡarapaˈteɾo"],
    es_uy: ["pirincho", "piˈɾintʃo"],
    ar_sy: ["وَقْوَاق", "waqˈwaːq"],
    ar_ye: ["وَقْوَاق", "waqˈwaːq"],
    ar_sa: ["وَقْوَاق", "waqˈwaːq"],
    ar_lb: ["وَقْوَاق", "waqˈwaːq"],
    en_wls: ["cuckoo", "ˈkʊkuː"],
    en_jam: ["cuckoo", "ˈkʊkuː"],
    en_ng: ["cuckoo", "ˈkʊkuː"],
    en_ph: ["cuckoo", "ˈkʊkuː"],
    en_ke: ["cuckoo", "ˈkʊkuː"],
    fr_sn: ["coucou", "kuku"],
    fr_ci: ["coucou", "kuku"],
    fr_ht: ["coucou", "kuku"],
    pt_mz: ["cuco", "ˈkuku"],
    pt_cv: ["cuco", "ˈkuku"],
    nl_be: ["koekoek", "ˈkukuk"],
    en_us: ["cuckoo", "ˈkʊkuː"],
    en_ca: ["cuckoo", "ˈkʊkuː"],
    en_za: ["cuckoo", "ˈkʊkuː"],
    de_ch: ["Kuckuck", "ˈkʊkʊk"],
    pt_ao: ["cuco", "ˈkuku"],
    es_ve: ["garrapatero", "ɡarapaˈteɾo"],
    ca_va: ["cucut", "kuˈkut"],
    ja: ["カッコウ", "kakːoː"],
    ja_osa: ["カッコウ", "kakːoː"],
    ja_aom: ["カッコウ", "kakːoː"],
    ja_hak: ["カッコウ", "kakːoː"],
    ja_kyo: ["カッコウ", "kakːoː"],
    ja_hir: ["カッコウ", "kakːoː"],
    ko: ["뻐꾸기", "p͈ʌk͈uɡi"],
    ko_kp: ["뻐꾸기", "p͈ʌk͈uɡi"],
    ko_bus: ["부꾹새", "puk͈uk̚s͈ɛ"],
    ko_jeju: ["버꿍새", "pʌk͈uŋsɛ"],
    ko_yb: ["뻐꿍기", "p͈ʌk͈uŋɡi"],
    zh: ["布谷鸟", "pu˥˩ ku˨˩˦ ni̯ɑʊ̯˨˩˦"],
    yue: ["布穀鳥", "pou˧ kʊk̚˥ niːu˩˧"],
    nan: ["杜鵑", "tɔ˧kuan˥"],
    zh_tw: ["布穀鳥", "pu˥˩ ku˨˩˦ ni̯ɑʊ̯˨˩˦"],
    hak_cn: ["伏鸠仔", "pʰʊk̚˥keu˧˥ʋe˧˩"],
    vi: ["cu cu", "ku˧ ku˧"],
    vi_c: ["cu cu", "ku˧ ku˧"],
    vi_s: ["cu cu", "ku˧ ku˧"],
    th: ["นกคัคคู", "nok˦˥ kʰak˦˥kʰuː˧"],
    id: ["kangkok", "ˈkaŋkɔʔ"],
    ms: ["sewah", "ˈsewah"],
    hi: ["कोयल", "koːjal"],
    sa_edu: ["कोकिल", "koːkilɐ"],
    sa: ["कोकिल", "koːkilɐ"],
    bn: ["কোকিল", "koːkil"],
    ur: ["کوئل", "koːjal"],
    ta: ["குயில்", "kujil"],
    en: ["cuckoo", "ˈkʊkuː"],
    de: ["Kuckuck", "ˈkʊkʊk"],
    fr: ["coucou", "kuku"],
    pcd: ["cocou", "kuˈku"],
    nrf: ["coucou", "kuˈku"],
    it: ["cuculo", "ˈkuːkulo"],
    es: ["cuco", "ˈkuko"],
    es_mx: ["pijuy", "piˈxwi"],
    pt: ["cuco", "ˈkuku"],
    pt_br: ["cuco", "ˈkuku"],
    ru: ["кукушка", "kʊˈkuʂkə"],
    ar: ["وَقْوَاق", "waqˈwaːq"],
    he: ["קוּקִיָּה", "kukiˈja"],
    tr: ["guguk", "ɡuˈɡuk"],
    fa: ["کوکو", "kuːˈkuː"],
    prs: ["کوکو", "kuːˈkuː"],
    sw: ["kekeo", "keˈkeo"],
    tl: ["kakok", "kaˈkok"],
    mn: ["хөхөө", "xɵˈxɵː"],
    sah: ["кэҕэ", "keˈɣe"],
    tyv: ["хек", "xek"],
    kjh: ["кӧӧк", "køːk"],
    alt: ["кӱӱк", "kyːk"],
    cv: ["куккук", "kukˈkuk"],
    bxr: ["хүхы", "xyˈxɘ"],
    kca: ["кӓви", "ˈkæwi"],
    ckt: ["ӄэӄӄуӄ", "qəqˈquq"],
    kpy: ["ӄаккук", "qakkuk"],
    itl: ["ӄэӄуӄ", "qəquq"],
    ket: ["ӄоӄпунь", "qɔqˈpunʲ"],
    my: ["ဥသြ", "ʔṵ θɔ́"],
    km: ["តាវៅ", "taː waːw"],
    lo: ["ນົກກັກກູ", "nok˧ kak˧˥ kuː˩˧"],
    zu: ["uphezukomkhono", "upʰɛzukomˈkʰono"],
    am: ["ኩኩ", "kuku"],
    mg: ["kankafotra", "kankaˈfutʂə"],
    ain: ["カッコㇰ", "ˈkakkok"],
    fi: ["käki", "ˈkæki"],
    hu: ["kakukk", "ˈkɒkukː"],
    ohu: ["kakuk", "ˈkɒkuk"],
    el: ["κούκος", "ˈkukos"],
    nl: ["koekoek", "ˈkukuk"],
    pl: ["kukułka", "kuˈkuwka"],
    szl: ["kukawka", "kuˈkafka"],
    uk: ["зозуля", "zoˈzulʲɐ"],
    sv: ["gök", "jøːk"],
    no: ["gjøk", "jøːk"],
    da: ["gøg", "ˈɡøˀj"],
    ro: ["cuc", "kuk"],
    ga: ["cuach", "kuəx"],
    eu: ["kuku", "ˈkuku"],
    cy: ["cog", "koːɡ"],
    ka: ["გუგული", "ɡuɡuli"],
    lzz: ["გუგული", "ɡuɡuli"],
    hy: ["կկու", "kəˈku"],
    hyw: ["կկու", "gəˈgu"],
    nv: ["naatsédlózii", "naːtséˈtɬózìː"],
    mi: ["koekoeā", "kɔɛkɔɛˈaː"],
    qu: ["chikwan", "ˈtʃikwan"],
    zh_db: ["喀咕", "kʰa˦ku˦"],
    bo: ["ཁུ་བྱུག", "kʰú tɕúʔ"],
    hni: ["xú bū", "xú bū"],
    th_isan: ["นกคัคคู", "nok˦˥ kʰak˦˥kʰuː˧"],
    th_n: ["นกคัคคู", "nok˦˥ kʰak˦˥kʰuː˧"],
    th_s: ["นกคัคคู", "nok˦˥ kʰak˦˥kʰuː˧"],
    za: ["roegdinghgeng", "ɣok˧ tiŋ˧ keːŋ˨˦"],
    jv: ["kedhasih", "kəˈɖasih"],
    su: ["manuk uncuing", "manʊk uɲˈtʃuiŋ"],
    ceb: ["kukok", "ˈkukok"],
    sm: ["aleva", "aˈleva"],
    sd: ["ڪوئل", "koːil"],
    pa: ["ਕੋਇਲ", "koil"],
    pnb: ["کوئل", "koːɪl"],
    ne: ["कोइली", "koili"],
    mr: ["कोकीळ", "koːkiːɭ"],
    gu: ["કોયલ", "koːjal"],
    si: ["කොහා", "kohaː"],
    dv: ["ކޮވެލި", "koʋeli"],
    te: ["కోయిల", "koːjila"],
    kn: ["ಕೋಗಿಲೆ", "koːɡile"],
    ml: ["കുയിൽ", "kujil"],
    tg: ["куку", "kuˈku"],
    ku: ["pepûk", "pɛˈpuːk"],
    ckb: ["پەپووک", "pɛˈpuːk"],
    az: ["ququ", "ɡuˈɡu"],
    azb: ["گوگوک", "ɡuˈɡuk"],
    ug: ["كاككۇك", "kɑkˈkuk"],
    kk: ["көкек", "kœˈkek"],
    ky: ["күкүк", "kyˈkyk"],
    uz: ["kakku", "kɑkˈku"],
    tk: ["ikatäk", "ikɑˈtæk"],
    mn_cn: ["ᠬᠦᠬᠦᠭᠡ", "kɵkɵˈɡe"],
    ar_eg: ["وَقْوَاق", "waqˈwaːq"],
    ar_lev: ["وَقْوَاق", "waqˈwaːq"],
    ar_gulf: ["وَقْوَاق", "waqˈwaːq"],
    ar_iq: ["وَقْوَاق", "waqˈwaːq"],
    ar_ma: ["وَقْوَاق", "waqˈwaːq"],
    arq: ["وَقْوَاق", "waqˈwaːq"],
    mey: ["وَقْوَاق", "waqˈwaːq"],
    ar_tn: ["وَقْوَاق", "waqˈwaːq"],
    ar_sd: ["وَقْوَاق", "waqˈwaːq"],
    mt: ["daqquqa", "dɐʔˈʔuːʔɐ"],
    xh: ["uphezukomkhono", "upʰɛzukomˈkʰono"],
    sn: ["kukudza", "kuˈkudza"],
    en_aave: ["cuckoo", "ˈkʊkuː"],
    en_nz: ["cuckoo", "ˈkʊkuː"],
    en_au: ["cuckoo", "ˈkʊkuː"],
    sco: ["gowk", "ɡʌuk"],
    af: ["koekoek", "ˈkukuk"],
    de_at: ["Kuckuck", "ˈkʊkʊk"],
    gsw: ["Gugger", "ˈɡʊɡər"],
    swg: ["Guckguck", "ˈɡʊkɡʊk"],
    bar: ["Kuckuck", "ˈkʊkʊk"],
    vmf: ["Gutzgauch", "ˈɡʊtsɡaʊx"],
    wae: ["Gugger", "ˈɡʊɡər"],
    nds: ["Kukuk", "ˈkuːkuk"],
    pdt: ["Kuckuck", "ˈkʊkʊk"],
    yi: ["קוקאווקע", "kuˈkavkə"],
    is: ["gaukur", "ˈɡœyːkʏr"],
    gd: ["cuthag", "ˈkʰuhak"],
    br: ["koukoug", "ˈkukuk"],
    nap: ["cucù", "kuˈku"],
    scn: ["cuccu", "ˈkukku"],
    vec: ["cucù", "kuˈku"],
    co: ["cuccu", "ˈkukku"],
    lij: ["cùcco", "ˈkuku"],
    rgn: ["còc", "kɔk"],
    egl: ["còc", "kɔk"],
    frp: ["coucou", "kuˈku"],
    ca: ["cucut", "kuˈkut"],
    gl: ["cuco", "ˈkukʊ"],
    oc: ["cocut", "kuˈkyt"],
    be: ["зязюля", "zʲaˈzʲulʲa"],
    cs: ["kukačka", "ˈkukatʃka"],
    sk: ["kukučka", "ˈkukutʃka"],
    sl: ["kukavica", "ˈkuːkaʋitsa"],
    sr: ["кукавица", "kûkaʋitsa"],
    bg: ["кукувица", "kukuˈvitsɐ"],
    lt: ["gegutė", "ɡʲɛˈɡʊtʲeː"],
    lv: ["dzeguze", "ˈdzɛɡuzɛ"],
    prg: ["geguse", "ɡɛˈɡuːzɛ"],
    sq: ["qyqe", "ˈcycɛ"],
    aae: ["qyqe", "ˈcyce"],
    et: ["kägu", "ˈkæɡu"],
    rom: ["kuko", "ˈkuko"],
    rmy: ["kuko", "ˈkuko"],
    se: ["giehka", "ˈkie̯hka"],
    sma: ["gïeke", "ˈɡie̯ke"],
    smj: ["giehka", "ˈkie̯hka"],
    smn: ["kiehâ", "ˈkie̯hɐ"],
    sms: ["ǩiõkk", "ˈkʲiɔkː"],
    sjd: ["кӣгк", "kiːɡk"],
    vro: ["kägo", "ˈkæɡo"],
    gn: ["anó", "aˈno"],
    yrl: ["anú", "aˈnu"],
    as: ["কুলি", "kuli"],
    or: ["କୋଇଲି", "koili"],
    bho: ["कोइलि", "koili"],
    en_south: ["cuckoo", "ˈkʊkuː"],
    en_app: ["cuckoo", "ˈkʊkuː"],
    en_in: ["cuckoo", "ˈkʊkuː"],
    en_ie: ["cuckoo", "ˈkʊkuː"],
    en_sco: ["cuckoo", "ˈkʊkuː"],
    en_yk: ["cuckoo", "ˈkʊkuː"],
    en_ck: ["cuckoo", "ˈkʊkuː"],
    en_sg: ["cuckoo", "ˈkʊkuː"],
    fy: ["koekoek", "ˈkukuk"],
    frr: ["Kukütj", "kuˈkytj"],
    li: ["kókkók", "ˈkoːkoːk"],
    nn: ["gauk", "ɡæʉk"],
    fo: ["geykur", "ˈtʃɛiːkʊr"],
    fr_qc: ["coucou", "kuku"],
    fr_af: ["coucou", "kuku"],
    fr_be: ["coucou", "kuku"],
    fr_ch: ["coucou", "kuku"],
    es_co: ["garrapatero", "ɡarapaˈteɾo"],
    es_cl: ["cuco", "ˈkuko"],
    es_ar: ["pirincho", "piˈɾintʃo"],
    es_cu: ["arriero", "aˈrjeɾo"],
    es_pe: ["garrapatero", "ɡarapaˈteɾo"],
    es_an: ["cuco", "ˈkuko"],
    rm: ["cucu", "ˈkuku"],
    sc: ["cucu", "ˈkuku"],
    la: ["cucūlus", "kʊˈkuːlʊs"],
    el_grc: ["κόκκυξ", "ˈkok.kyks"],
    el_kath: ["κόκκυξ", "ˈko.ciks"],
    enm: ["cuccu", "ˈkukuː"],
    en_em: ["cuckoo", "ˈkʊkuː"],
    ang: ["ġēac", "jæːɑk"],
    non: ["gaukr", "ˈɡɔukr̩"],
    pi: ["कोकिल", "koːkilɐ"],
    pi_edu: ["kokila", "koːkilɐ"],
    pmh: ["कोइल", "koˑilɐ"],
    nci: ["metlapīltetzotzontzin", "metɬapiːltetsotsoˈtsontsin"],
    p_ine: ["*gʰegʰuǵʰ-", "gʰegʰuǵʰ"],
    pkar: ["*gugul-", "gugul-"],
    zh_song: ["布穀", "puH kuwk"],
    zh_wenyan_edu: ["布穀", "pou˧ kʊk˥"],
    zh_han: ["布穀", "pɑs kok"],
    zh_tang: ["布穀", "puoH kuwk"],
    ja_edo: ["ほととぎす", "hototoɡisɯ"],
    ja_kanbun: ["杜鵑", "hototoɡisɯ"],
    ja_heian: ["ほととぎす", "ɸototoɡisu"],
    ja_chu: ["ほととぎす", "ɸototoɡisu"],
    ko_mid: ["버국새", "pəkuk̚saj"],
    ko_em: ["뻐꾹새", "p͈ʌk͈uk̚s͈ɛ"],
    vi_han: ["布穀", "ɓo˧˥ kok̚˧˥"],
    vi_nom: ["布穀", "ɓo˧˩ ko˧ˀ˥"],
    eo: ["kukolo", "kuˈkolo"],
    ia: ["cucu", "ˈkuku"],
    jbo: ["cipnrkuku", "ʃipn̩rˈkuku"],
    hsn: ["阳雀子", "iæn˩˧tsʰio˨˦tsɹ̩"],
    gan: ["布谷", "pu˦˥kuʔ˥"],
    mai: ["कोइल", "koil"],
    awa: ["कोइल", "koil"],
    bra: ["कोयल", "koːjal"],
    sat: ["ᱠᱚᱭᱮᱞ", "kojel"],
    mk: ["кукавица", "kuˈkavitsa"],
    st: ["ntetekeng", "ntɛtɛˈkɛŋ"],
    ts: ["ngwafalantala", "ŋʷafalanˈtala"],
    kab: ["ṭikkuk", "tˤikˈkuk"],
    cni: ["tsiya", "ˈtsija"],
    agr: ["ikáncham", "iˈkantʃam"],
    car: ["pika", "piˈka"],
    av: ["гагу", "ɡaɡu"],
    lez: ["кукупӀ", "kːukːupʼ"],
    dar: ["гегуг", "ɡeɡuɡ"],
    agx: ["кекку", "kːekːu"],
    ddo: ["куку", "kuku"],
    lbe: ["ччикку", "tʃːikːu"],
    tab: ["кукум", "kːukːum"],
    aqc: ["гикку", "ɡikːu"],
    tkr: ["гукки", "ɡukːi"],
    kum: ["атъёкъ", "atˈjoq"],
    nog: ["коькек", "køˈkek"],
    ady: ["кукуу", "kʷǝkʷǝw"],
    kbd: ["кӏыгуугу", "tʃʼǝɡʷuːɡʷ"],
    ab: ["акәыкәы", "akʷǝkʷǝ"],
    abq: ["квыква", "kʷǝkʷa"],
    uby: ["kʷǝgʷ", "kʷǝɡʷ"],
    xmf: ["გუგული", "ɡuɡuli"],
    os: ["гӕкког", "ɡækˈkoɡ"],
    ty: ["ʻārevareva", "ʔaːɾevaˈɾeva"],
    rar: ["karavia", "kaɾaˈvia"],
    mni: ["ꯀꯣꯀꯤꯜ", "kɔkil"],
    nag: ["Kuli Sorai", "kuli sɔrai"],
    dz: ["ཁུ་བྱུག", "kʰú tɕǔʔ"],
    ban: ["kedasih", "kəˈdasih"],
    mwr: ["कोयल", "koːjal"],
    bgc: ["कोयल", "koːjal"],
    ks: ["کوکو", "kuːkuː"],
    kok: ["कोगूळ", "koɡuːɭ"],
    mnp: ["布谷", "piɔ˧˧ku˨˦"],
    yue_ts: ["布谷鸟", "pu˧ kɵk̚˥ ⁿdiau˨˩"],
    zh_jh: ["布谷鸟", "pu˥˥kuʔ˦niau˦˨"],
    zh_tj: ["喀咕", "kʰa˨˩ ku˨˩"],
    zh_lz: ["布谷鸟", "pu˨˩˧ku˨˩˧niau˦˦˨"],
    dng: ["җунгўчўр", "tʂuŋ˦ku˨˦tʂʰuɻ˨˦"],
    hsb: ["kokula", "ˈkɔkula"],
    csb: ["kùkówka", "kuˈkovka"],
    rue: ["зозуля", "zoˈzulʲa"],
    fur: ["cuc", "kuk"],
    ast: ["cuquiellu", "kuˈkjeʎu"],
    fax: ["cucu", "ˈkuku"],
    an: ["cuculo", "kuˈkulo"],
    rup: ["cuc", "kuk"],
    ruq: ["cuc", "kuk"],
    wa: ["coucou", "kuˈku"],
    kpv: ["кӧк", "kɵk"],
    koi: ["кӧк", "kɵk"],
    udm: ["кикы", "kiˈkɨ"],
    mhr: ["куку", "ˈkuku"],
    mrj: ["куку", "ˈkuku"],
    myv: ["куко", "ˈkuko"],
    mdf: ["куку", "ˈkuku"],
    krl: ["käki", "ˈkæki"],
    olo: ["kägöi", "ˈkæɡøi"],
    vep: ["kägi", "ˈkæɡi"],
    vot: ["tšäko", "ˈtʃæko"],
    liv: ["kēg", "keːɡ"],
    mzn: ["کوکی", "kuːˈkiː"],
    crh: ["kukuquş", "kukuˈquʃ"],
    tt: ["кәккүк", "kækˈkyk"],
    ba: ["кәкүк", "kæˈkyk"],
    krc: ["гугук", "ɡuˈɡuk"],
    ksw: ["ထိၣ်မိၢ်ဧူ", "tʰò mò ʔù"],
    lhu: ["qú-pu", "qú pu"],
    lis: ["kwá py̱", "kʷá py̰"],
    shn: ["ၼူၵ်ႉတွင်ႉလေႃး", "nok˦˨ˀ tɔŋ˦˨ˀ lɔ˥"],
    ssw: ["phezukwemkhono", "pʰɛzukwɛmˈkʰono"],
    nd: ["inkanku", "iⁿˈkaŋku"],
    rhg: ["kuilá", "kuiˈla"],
    ctg: ["কোগিল", "koˈɡil"],
    mag: ["कोइल", "koil"],
    lmo: ["cùcch", "ˈkuk"],
    pms: ["coco", "ˈkuku"],
    pnt: ["κούκος", "ˈkukos"],
    dsb: ["kukawa", "ˈkukawa"],
    gv: ["cooag", "ˈkuːaɡ"],
    kw: ["koukou", "ˈkukuː"],
    zza: ["Phepug", "pʰɛˈpuɡ"],
    mzh: ["hotsen'i", "hotsenˈʔi"],
    kgp: ["—", "—"],
    tob: ["—", "—"],
    plg: ["—", "—"],
    moc: ["—", "—"],
    mbc: ["—", "—"],
    kpj: ["—", "—"],
    guu: ["—", "—"],
    bwi: ["—", "—"],
    cag: ["—", "—"],
    crt: ["—", "—"],
    tpy: ["—", "—"],
    jup: ["—", "—"],
    kwa: ["—", "—"],
    emp: ["b̶ijũẽ", "ɓiˈhũẽ"],
    bjn: ["bubut", "ˈbubut"],
    mns: ["куккук", "kukˈkuk"],
    tsg: ["saguksuk", "saˈɡuksuk"],
    hr: ["kukavica", "kûkaʋitsa"],
    bs: ["kukavica", "kûkaʋitsa"],
    iba: ["bubut", "ˈbubut"],
    xal: ["көкә", "køˈkæ"],
    fro: ["cucu", "kuˈky"],
    fr_class: ["coucou", "kuˈku"],
    it_dan: ["cucco", "ˈkukko"],
    goh: ["gouh", "ˈɡou̯x"],
    xct_litpr: ["ཁུ་བྱུག", "kʰu bjuɡ"],
    xct: ["ཁུ་བྱུག", "kʰu bjuɡ"],
    kaw: ["ꦏꦺꦴꦏꦶꦭ", "kokila"],
    de_lut: ["gukuk", "ˈɡukuk"],
    gmh: ["gouch", "ˈɡou̯x"],
    es_sgl: ["cuclillo", "kuˈkliʎo"],
    osp: ["cuco", "ˈkuko"],
    sga: ["caí", "kaːi"],
    ium: ["norqc jaangh iuv", "noʔ˨ jaːŋ˧˩ ʔiu˦"],
    mga: ["cúach", "ˈkuːax"],
    xng: ["ᠬᠦᠬᠦᠭᠡ", "kɵkɵˈɡe"],
    ja_kg: ["カッコウ", "kakːoː"],
    ja_sd: ["カッコウ", "kakːoː"],
    pam: ["siabukut", "siˈabukut"],
    tcy: ["ಕೋಗಿಲೆ", "koːɡile"],
    kaa: ["átshók", "ætˈʃøk"],
    orv: ["зегзица", "zʲɛɡˈzitsa"],
    och: ["布穀", "*paːs kloːɡ"],
    ojp: ["ほととぎす", "pototoɡisu"],
    hak_tw: ["杜鵑", "tʰu˥˥kien˨˦"],
    nan_qz: ["豆仔鳥", "tau˨˨a˥˥tsiau˥˥"],
    zh_wh: ["布谷鸟", "pu˧˥ ku˨˩˧ niau˦˨"],
    zh_zz: ["布谷鸟", "pu˧˩˨ku˨˦niau˥˧"],
    hak_hl: ["杜鵑", "tʰu˧˧kien˥˧"],
    cpx: ["布谷", "pɔu˦˨kɒʔ˨˩"],
    tyz: ["khảm khắc", "kʰaːm˨˩˧ kʰak˥"],
    kac: ["kukdun", "kúk dùn"],
    pll: ["pak-tu", "pək tuʔ"],
    hne: ["कोयली", "koːjliː"],
    mnw: ["ကဴဝဴ", "kəwào"],
    bdq: ["jɛːt", "jɛːt"],
    nut: ["khảm khắc", "kʰaːm˨˩˧ kʰak˥"],
    kek: ["ixnam", "iʃˈnam"],
    lld: ["cuch", "kuk"],
    stq: ["Kukuuk", "ˈkukuk"],
    ota: ["غوغوق", "ɡuˈɡuk"],
    cmg: ["ᠬᠦᠬᠦᠭᠡ", "kɵkɵˈɡe"],
    ani: ["гиггу", "ɡiɡːu"],
    bdk: ["гугутӀ", "ɡuɡutʼ"],
    nrf_gg: ["coucou", "kuˈku"],
    fra_jer: ["coucou", "kuˈku"],
    gsw_w: ["Gugger", "ˈɡʊɡər"],
    huz: ["кӀукӀутӀо", "kʼukʼutʼo"],
    khv: ["куку", "kuku"],
    kjj: ["кокку", "kːokːu"],
    kxv: ["kuhu paṭa", "kuɦu paʈa"],
    pao: ["poboyooha'a", "poboˈjoːhaʔa"],
    rut: ["гиггу", "ɡiɡːu"],
    tpn: ["anũ", "ãˈnũ"],
    zh_cq: ["阳雀", "iaŋ˨˩tɕʰio˨˩"],
    zh_jn: ["喀咕", "kʰa˨˩˧ ku˨˩˧"],
    zh_km: ["阳雀", "iã˧˩tɕʰio˧˩"],
    zh_xa: ["布谷鸟", "pu˥˥ ku˨˩ niau˥˧"],
    bbl: ["გუგუტ", "ɡuɡutː"],
    kry: ["гугу", "ɡuɡu"],
    yug: ["хохпынʲ", "χɔχpɨɲ"],
    haj: ["কুলুকুনী", "kuluˈkuni"],
    nan_xm: ["豆仔鳥", "tau˨˨a˥˧tsiau˥˧"],
    nan_zz: ["豆仔鳥", "tau˨˨a˥˧tsiau˥˧"],
    zh_cd: ["阳雀", "iaŋ˨˩tɕʰio˨˩"],
    zh_hf: ["布谷鸟", "pu˥˧kuʔ˥niau˨˩˧"],
    zh_kf: ["布谷鸟", "pu˧˩˨ku˨˦niau˥˥"],
    zh_nj: ["布谷鸟", "pu˦˦kuʔ˥niau˨˩˨"],
    ltg: ["dzagiuze", "ˈdzaɡʲiuzʲæ"],
    ie: ["cucú", "kuˈku"],
    io: ["kukulo", "kuˈkulo"],
    vls: ["koekoek", "ˈkukuk"],
    fkv: ["käki", "ˈkæki"],
    fit: ["käki", "ˈkæki"],
    aln: ["qyqe", "ˈcyce"],
    fud: ["kāleva", "kaːˈleva"],
    lep: ["ᰀᰀᰪᰑᰨ", "kəkɯfo"],
  },
};
