/**
 * Daughter is one of the most stable words Indo-European has: *dʰugh₂tḗr comes through six thousand
 * years almost unchanged in Sanskrit duhitṛ, Greek thugátēr, Gothic dauhtar, Old English dohtor,
 * Lithuanian duktė and Tocharian B tkācer — the last of these sitting in the Tarim Basin, about as
 * far from the others as the family reaches. Reading those forms side by side is close to reading the
 * sound laws directly. What makes it worth a map rather than a table is the exception: Latin threw
 * the word away for fīlia, and Celtic threw it away too (Old Irish ingen, Welsh merch), so the entire
 * western edge of the family has replaced a word the eastern edge kept. Elsewhere the concept is
 * often not a separate word at all — Indonesian and Tagalog say "female child", and Semitic uses the
 * feminine of "son" (Arabic bint, Hebrew bat, Proto-Semitic *bint-).
 *
 * The atlas already has mother and father; this is the third leg, and the one where the sound laws
 * show most cleanly, because *gh₂ landed differently in every branch.
 */
WORDS.daughter = {
  emoji: "👧",
  label: {
    en: "Daughter", ja: "娘", ko: "딸", zh: "女儿", yue: "女", vi: "Con gái", th: "ลูกสาว",
    id: "Anak perempuan", hi: "बेटी", de: "Tochter", fr: "Fille", it: "Figlia", es: "Hija",
    es_eu: "Hija", es_mx: "Hija", pt: "Filha", pt_eu: "Filha", pt_br: "Filha", ru: "Дочь",
    uk: "Дочка", ar: "بنت", he: "בת", sw: "Binti",
  },
  definition: {
    en: "Daughter — one's female child. The Indo-European word is one of the family's most stable, except in Latin and Celtic, which replaced it.",
    ja: "娘 — 自分の女の子。印欧語族で最も安定した語の一つだが、ラテン語とケルト諸語だけがこの語を捨てた。",
    ko: "딸 — 자기의 여자 아이. 인도유럽어에서 가장 안정된 단어 중 하나지만, 라틴어와 켈트어만은 이 말을 버렸다.",
    zh: "女儿 — 自己的女性子女。这是印欧语系最稳定的词之一，唯独拉丁语和凯尔特语把它换掉了。",
    yue: "女 — 自己嘅女性子女。呢個係印歐語系最穩定嘅詞之一，不過拉丁語同凱爾特語就換咗第個詞。",
    vi: "Con gái — con là nữ. Đây là một trong những từ ổn định nhất của ngữ hệ Ấn-Âu, trừ tiếng Latinh và các tiếng Celt đã thay thế nó.",
    th: "ลูกสาว — บุตรที่เป็นหญิง คำนี้เป็นหนึ่งในคำที่มั่นคงที่สุดของตระกูลอินโด-ยูโรเปียน ยกเว้นภาษาละตินและเคลต์ที่เปลี่ยนไปใช้คำอื่น.",
    id: "Anak perempuan — anak yang berjenis kelamin perempuan. Kata Indo-Eropa untuk ini termasuk yang paling stabil, kecuali dalam bahasa Latin dan Kelt yang menggantinya.",
    hi: "बेटी — अपनी स्त्री संतान। भारोपीय परिवार के सबसे स्थिर शब्दों में से एक, सिवाय लातिनी और केल्टिक के, जिन्होंने इसे बदल दिया।",
    de: "Tochter — das weibliche Kind. Eines der stabilsten Wörter der indogermanischen Familie — außer im Lateinischen und Keltischen, die es ersetzt haben.",
    fr: "Fille — l'enfant de sexe féminin. L'un des mots les plus stables de la famille indo-européenne, sauf en latin et en celtique, qui l'ont remplacé.",
    it: "Figlia — la figlia femmina. Una delle parole più stabili della famiglia indoeuropea, tranne in latino e nelle lingue celtiche, che l'hanno sostituita.",
    es: "Hija — el hijo de sexo femenino. Una de las palabras más estables de la familia indoeuropea, salvo en latín y en céltico, que la sustituyeron.",
    es_eu: "Hija — el hijo de sexo femenino. Una de las palabras más estables de la familia indoeuropea, salvo en latín y en céltico, que la sustituyeron.",
    es_mx: "Hija — el hijo de sexo femenino. Una de las palabras más estables de la familia indoeuropea, salvo en latín y en céltico, que la sustituyeron.",
    pt: "Filha — o filho do sexo feminino. Uma das palavras mais estáveis da família indo-europeia, exceto em latim e nas línguas celtas, que a substituíram.",
    pt_eu: "Filha — o filho do sexo feminino. Uma das palavras mais estáveis da família indo-europeia, exceto em latim e nas línguas celtas, que a substituíram.",
    pt_br: "Filha — o filho do sexo feminino. Uma das palavras mais estáveis da família indo-europeia, exceto no latim e nas línguas celtas, que a substituíram.",
    ru: "Дочь — ребёнок женского пола. Одно из самых устойчивых слов индоевропейской семьи — кроме латыни и кельтских, которые его заменили.",
    uk: "Дочка — дитина жіночої статі. Одне з найстійкіших слів індоєвропейської сім'ї — окрім латини та кельтських, які його замінили.",
    ar: "بنت — الولد الأنثى. من أثبت كلمات العائلة الهندية الأوروبية، إلا في اللاتينية والكلتية اللتين استبدلتاها.",
    he: "בת — הילד ממין נקבה. אחת המילים היציבות ביותר במשפחה ההודו-אירופית, פרט ללטינית ולקלטית שהחליפו אותה.",
    sw: "Binti — mtoto wa kike. Ni mojawapo ya maneno imara zaidi katika familia ya Kihindi-Ulaya, isipokuwa Kilatini na lugha za Kikelti zilizolibadilisha.",
  },
  data: {
    // --- UI languages -------------------------------------------------
    en: ["daughter", "ˈdɔːtə"],
    ja: ["娘", "mɯsɯme"],
    ko: ["딸", "t͈al"],
    zh: ["女儿", "ny˨˩˦ ɑɻ˧˥"],
    yue: ["女", "nɵy˩˧"],
    vi: ["con gái", "kɔn˧ ɣaːj˧˥"],
    th: ["ลูกสาว", "luːk̚˥˩ saːw˩˩˦"],
    id: ["anak perempuan", "anak pərəmpuan"],
    hi: ["बेटी", "beːʈiː"],
    de: ["Tochter", "ˈtɔxtɐ"],
    fr: ["fille", "fij"],
    it: ["figlia", "ˈfiʎʎa"],
    es: ["hija", "ˈixa"],
    es_mx: ["hija", "ˈixa"],
    pt: ["filha", "ˈfiʎɐ"],
    pt_br: ["filha", "ˈfiʎɐ"],
    ru: ["дочь", "dotɕ"],
    uk: ["дочка", "dotʃˈka"],
    ar: ["بنت", "bint"],
    he: ["בת", "bat"],
    sw: ["binti", "binti"],

    // --- *dʰugh₂tḗr, branch by branch ---------------------------------
    p_ine: ["*dʰugh₂tḗr", "dʰugh₂téːr"],
    sa: ["दुहितृ", "duhitr̩"],
    h_vedic: ["दुहितृ", "duhitr̩"],
    pi: ["धीता", "dʰiːtaː"],
    pi_edu: ["dhītā", "dʰiːtaː"],
    el_grc: ["θυγάτηρ", "tʰuɡátɛːr"],
    el_kath: ["θυγάτηρ", "θiˈɣatir"],
    got: ["𐌳𐌰𐌿𐌷𐍄𐌰𐍂", "dɔːhtar"],
    ang: ["dohtor", "ˈdoxtor"],
    enm: ["doughter", "ˈdouxtər"],
    non: ["dóttir", "doːttir"],
    osx: ["dohtar", "ˈdoxtar"],
    ofs: ["dochter", "ˈdoxteɾ"],
    goh: ["tohter", "ˈtoxtɛr"],
    gmh: ["tohter", "ˈtoxtər"],
    lt: ["duktė", "dʊkʲˈteː"],
    prg: ["duckti", "duktiː"],
    txb: ["𑀢𑁆𑀓𑀸𑀘𑁂𑀭𑁆", "tkaːtser"],
    xto: ["𑀘𑁆𑀓𑀸𑀘𑀭𑁆", "tskaːtsar"],
    hy_grab: ["դուստր", "dustr"],
    pal: ["𐭣𐭥𐭧𐭲", "duxt"],

    // --- ...and the branches that replaced it -------------------------
    la: ["fīlia", "ˈfiːlia"],
    sga: ["ingen", "ˈinʲɣʲen"],
    mga: ["ingen", "ˈinʲɣʲen"],
    fro: ["fille", "ˈfiʎə"],
    osp: ["fija", "ˈfiʒa"],
    lv: ["meita", "meita"],

    // --- Semitic: the feminine of "son" -------------------------------
    psem: ["*bint-", "bint"],
    hbo: ["בת", "bat"],
    he_mis: ["בת", "bat"],
    ar_qur: ["بنت", "bint"],
    arc: ["ܒܪܬܐ", "bartaː"],
    akk: ["mārtu", "maːrtu"],
    cop: ["ϣⲉⲉⲣⲉ", "ʃeːre"],
    p_dra: ["*makaḷ", "makaɭ"],

    // --- Modern Europe --------------------------------------------------
    nl: ["dochter", "ˈdɔxtər"],
    af: ["dogter", "ˈdɔxtər"],
    sv: ["dotter", "ˈdɔtːɛr"],
    no: ["datter", "ˈdatːər"],
    nn: ["dotter", "ˈdɔtːər"],
    da: ["datter", "ˈdadɐ"],
    is: ["dóttir", "ˈtouhtɪr"],
    de_at: ["Tochter", "ˈtɔxtɐ"],
    pl: ["córka", "ˈtsurka"],
    cs: ["dcera", "ˈdtsɛra"],
    sk: ["dcéra", "ˈdtseːra"],
    sl: ["hči", "xtʃi"],
    hr: ["kći", "ktɕi"],
    sr: ["кћи", "ktɕi"],
    bs: ["kći", "ktɕi"],
    bg: ["дъщеря", "dɤʃtɛˈrʲa"],
    mk: ["ќерка", "ˈcɛrka"],
    be: ["дачка", "ˈdatʃka"],
    el: ["κόρη", "ˈkori"],
    ro: ["fiică", "ˈfijkə"],
    sq: ["bijë", "ˈbijə"],
    ca: ["filla", "ˈfiʎə"],
    gl: ["filla", "ˈfiʎa"],
    oc: ["filha", "ˈfiʎo"],
    hu: ["lány", "laːɲ"],
    fi: ["tytär", "ˈtytær"],
    et: ["tütar", "ˈtytar"],
    eu: ["alaba", "alaba"],
    ga: ["iníon", "ɪˈnʲiːn"],
    cy: ["merch", "mɛrx"],
    gv: ["inneen", "iˈneːn"],
    ka: ["ქალიშვილი", "kʰaliʃvili"],
    hy: ["դուստր", "dustɾ"],

    // --- Asia, Africa, Pacific ------------------------------------------
    fa: ["دختر", "doxˈtæɾ"],
    tg: ["духтар", "duxtar"],
    ps: ["لور", "lur"],
    ur: ["بیٹی", "beːʈiː"],
    bn: ["মেয়ে", "mee"],
    mr: ["मुलगी", "mulɡiː"],
    gu: ["દીકરી", "diːkəɾiː"],
    pa: ["ਧੀ", "d̪ʱiː"],
    ne: ["छोरी", "tʃʰoɾi"],
    si: ["දුව", "duʋa"],
    ta: ["மகள்", "maɡaɭ"],
    te: ["కూతురు", "kuːturu"],
    ml: ["മകൾ", "maɡaɭ"],
    kn: ["ಮಗಳು", "maɡaɭu"],
    my: ["သမီး", "θəmí"],
    km: ["កូនស្រី", "koːn srəj"],
    lo: ["ລູກສາວ", "luːk̚ saːw"],
    tr: ["kız", "kɯz"],
    az: ["qız", "ɡɯz"],
    kk: ["қыз", "qɯz"],
    ky: ["кыз", "qɯz"],
    uz: ["qiz", "qiz"],
    tt: ["кыз", "qɯz"],
    mn: ["охин", "oxin"],
    ms: ["anak perempuan", "anak pərəmpuan"],
    tl: ["anak na babae", "ˈʔanak na baˈbaʔe"],
    haw: ["kaikamahine", "kɐikɐmɐˈhine"],
    mi: ["tamāhine", "tamaːhine"],
    sm: ["afafine", "afafine"],
    zu: ["indodakazi", "indodaˈkazi"],
    xh: ["intombi", "inˈtombi"],
    am: ["ልጅ", "lɨdʒ"],
    ha: ["'ya", "ʔja"],
    yo: ["ọmọbìnrin", "ɔmɔbĩrĩ"],

    // --- English, dialect by dialect ------------------------------------
    en_us: ["daughter", "ˈdɔɾɚ"],
    en_ca: ["daughter", "ˈdɑɾɚ"],
    en_au: ["daughter", "ˈdoːɾə"],
    en_nz: ["daughter", "ˈdɔːtə"],
    en_za: ["daughter", "ˈdɔːtə"],
    en_south: ["daughter", "ˈdɔːɾɚ"],
    en_app: ["daughter", "ˈdɔːɾɚ"],
    en_aave: ["daughter", "ˈdɑːɾɚ"],
    en_ie: ["daughter", "ˈdɒːtəɹ"],
    en_sco: ["daughter", "ˈdɔːtəɹ"],
    en_wls: ["daughter", "ˈdɔːtə"],
    en_yk: ["daughter", "ˈdɔːtə"],
    en_scouse: ["daughter", "ˈdɔːt̪sə"],
    en_geordie: ["daughter", "ˈdɔːtɐ"],
    en_brum: ["daughter", "ˈdɔːtə"],
    en_manc: ["daughter", "ˈdɔːtɐ"],
    en_wc: ["daughter", "ˈdɔːtɚ"],
    en_ck: ["daughter", "ˈdoːʔə"],
    en_est: ["daughter", "ˈdɔːʔə"],
    en_in: ["daughter", "ˈɖɔːʈɚ"],
    en_sg: ["daughter", "ˈdɔːtə"],
    en_my: ["daughter", "ˈdɔːtə"],
    en_ph: ["daughter", "ˈdɔːtə"],
    en_ng: ["daughter", "ˈdɔːtə"],
    en_ng2: ["daughter", "ˈdɔːtə"],
    en_ke: ["daughter", "ˈdɔːtə"],
    en_jam: ["daughter", "ˈdɑːtə"],
    en_em: ["daughter", "ˈdɔːtər"],
    sco: ["dochter", "dɔxtəɹ"],

    // --- Germanic — the *dohtar word held everywhere ---------------------
    nl_be: ["dochter", "dɔxtər"],
    fy: ["dochter", "ˈdɔxtər"],
    vls: ["dochter", "ˈdɔxtər"],
    li: ["dochter", "dɔxtər"],
    nds: ["Dochter", "dɔxtɐ"],
    ksh: ["Dochter", "dɔxtɐ"],
    vmf: ["Dochder", "dɔxdɐ"],
    pdc: ["Dochder", "dɔxdər"],
    lb: ["Duechter", "ˈduəχtɐ"],
    de_ch: ["Tochter", "ˈtɔxtər"],
    de_lu: ["Tochter", "tɔxtɐ"],
    de_lut: ["Tochter", "ˈtɔxtər"],
    gsw: ["Tochter", "toxtər"],
    yi: ["טאָכטער", "ˈtɔxtər"],
    fo: ["dóttir", "ˈdœhtɪɹ"],

    // --- Romance — the fīlia side, plus the rows that lost the l ---------
    es_ar: ["hija", "ixa"],
    es_co: ["hija", "ixa"],
    es_pe: ["hija", "ixa"],
    es_ec: ["hija", "ixa"],
    es_uy: ["hija", "ixa"],
    es_ni: ["hija", "ixa"],
    es_bo: ["hija", "ixa"],
    es_do: ["hija", "ixa"],
    es_py: ["hija", "ˈixa"],
    // Caribbean, Andalusian and Central American rows have /x/ > [h], read off their own "ojo".
    es_pr: ["hija", "iha"],
    es_cu: ["hija", "iha"],
    es_ve: ["hija", "iha"],
    es_an: ["hija", "iha"],
    es_cl: ["hija", "iha"],
    es_gt: ["hija", "iha"],
    es_sv: ["hija", "iha"],
    es_cr: ["hija", "iha"],
    es_hn: ["hija", "iha"],
    es_pa: ["hija", "iha"],
    es_sgl: ["hija", "ˈiʃa"],
    lad: ["ija", "iʒa"],
    pt_ao: ["filha", "ˈfiʎɐ"],
    pt_mz: ["filha", "ˈfiʎɐ"],
    pt_cv: ["filha", "ˈfiʎɐ"],
    pt_mo: ["filha", "ˈfiʎɐ"],
    fr_qc: ["fille", "fij"],
    fr_be: ["fille", "fij"],
    fr_ch: ["fille", "fij"],
    fr_af: ["fille", "fij"],
    fr_lu: ["fille", "fij"],
    fr_cm: ["fille", "fij"],
    fr_sn: ["fille", "fij"],
    fr_ci: ["fille", "fij"],
    fr_ht: ["fille", "fij"],
    fr_class: ["fille", "fiʎ"],
    it_dan: ["figlia", "ˈfiʎʎa"],
    ca_va: ["filla", "ˈfiʎa"],
    an: ["filla", "ˈfiʎa"],
    rm: ["figlia", "ˈfiʎa"],
    ast: ["fía", "ˈfia"],
    mwl: ["filha", "ˈfiʎɐ"],
    lld: ["fia", "ˈfia"],
    fur: ["fie", "ˈfie"],
    nap: ["figlia", "ˈfiʎʎə"],
    scn: ["figghia", "ˈfiɟɟa"],
    lij: ["fìggia", "ˈfiddʒa"],
    vec: ["fioła", "ˈfjɔɫa"],
    lmo: ["fiœula", "ˈfjøːla"],
    pms: ["fija", "ˈfija"],
    cbk: ["hija", "ˈixa"],

    // --- Celtic and Armenian --------------------------------------------
    br: ["merc'h", "mɛrx"],
    kw: ["myrgh", "mɪrx"],
    hyw: ["դուստր", "tustɾ"],

    // --- Slavic and Baltic ----------------------------------------------
    cu: ["дъщи", "dʊʃti"],
    orv: ["дочи", "dotʃi"],
    hsb: ["dźowka", "ˈdʑɔwka"],
    dsb: ["źowka", "ˈʑɔwka"],
    rue: ["донька", "ˈdonʲka"],
    szl: ["cera", "ˈtsɛra"],
    ltg: ["meita", "ˈmeita"],

    // --- Uralic — Finnic *tütär, and a separate Permic/Volga word --------
    krl: ["tytär", "ˈtytær"],
    olo: ["tytär", "ˈtytær"],
    vep: ["tütär", "ˈtytær"],
    vot: ["tütär", "ˈtytær"],
    vro: ["tütär", "tytær"],
    fkv: ["tytär", "ˈtytær"],
    fit: ["tytär", "ˈtytær"],
    se: ["nieida", "ˈnieida"],
    kpv: ["ныв", "nɨv"],
    koi: ["ныв", "nɨv"],
    udm: ["ныл", "nɨl"],
    mhr: ["ӱдыр", "ydər"],
    mrj: ["ӹдӹр", "ɘdɘr"],
    myv: ["тейтерь", "tʲejtʲerʲ"],
    mdf: ["стирь", "stʲirʲ"],

    // --- Turkic — the word is "girl" everywhere --------------------------
    ug: ["قىز", "qiz"],
    tk: ["gyz", "ɡɯz"],
    gag: ["kız", "kɯz"],
    crh: ["qız", "qɯz"],
    kaa: ["qız", "qɯz"],
    kum: ["къыз", "qɯz"],
    nog: ["кыз", "qɯz"],
    krc: ["къыз", "qɯz"],
    ba: ["ҡыҙ", "qɯð"],
    alt: ["кыс", "qɯs"],
    sah: ["кыыс", "kɯːs"],
    dlg: ["кыыс", "kɯːs"],
    cv: ["хӗр", "xɘr"],
    azb: ["قیز", "ɡɯz"],
    qxq: ["qız", "ɡɯz"],
    ota: ["قیز", "kɯz"],
    xqa: ["qız", "qɯz"],

    // --- Mongolic and Tungusic ------------------------------------------
    xal: ["күүкн", "kyːkn"],
    bxr: ["басаган", "basaɡan"],
    cmg: ["ᠥᠬᠢᠨ", "økin"],
    xng: ["ᠥᠬᠢᠨ", "økin"],
    mnc: ["ᠰᠠᡵᡤᠠᠨ ᠵᡠᡳ", "sarɡan dʒui"],

    // --- Semitic — the feminine of "son", continued ----------------------
    ar_eg: ["بنت", "bint"],
    ar_lev: ["بنت", "bint"],
    ar_sy: ["بنت", "bɪnt"],
    ar_lb: ["بنت", "bint"],
    ar_jo: ["بنت", "bint"],
    ar_ps: ["بنت", "bint"],
    ar_iq: ["بنت", "bint"],
    ar_gulf: ["بنت", "bint"],
    afb: ["بنت", "bint"],
    abv: ["بنت", "bint"],
    acw: ["بنت", "bint"],
    ar_sa: ["بنت", "bint"],
    ar_ye: ["بنت", "bint"],
    mey: ["بنت", "bint"],
    ar_ma: ["بنت", "bənt"],
    arq: ["بنت", "bənt"],
    ar_tn: ["بنت", "bənt"],
    ayl: ["بنت", "bint"],
    ar_sd: ["بت", "bitt"],
    mt: ["bint", "bint"],
    syc: ["ܒܪܬܐ", "bartaː"],
    tru: ["ܒܪܬܐ", "barto"],
    aii: ["ܒܪܵܬܵܐ", "ˈbrata"],
    oar: ["ברת", "bart"],
    phn: ["𐤁𐤕", "bat"],
    xpu: ["𐤁𐤕", "bat"],
    uga: ["𐎁𐎚", "bittu"],
    xsa: ["𐩨𐩬𐩩", "bint"],
    gez: ["ወለት", "walat"],
    tig: ["ወለት", "wələt"],
    ti: ["ጓል", "ɡʷal"],

    // --- Berber — daughter is only ever "my daughter" --------------------
    // Berber kin terms are obligatorily possessed; the citation form is the
    // 1sg, exactly as this atlas's Berber rows already cite "yemma" and "baba".
    kab: ["yelli", "jəlli"],
    shy: ["yelli", "jəlli"],
    tzm: ["ⵢⵍⵍⵉ", "jəlli"],
    zgh: ["ⵢⵍⵍⵉ", "jəlli"],
    shi: ["ⵉⵍⵍⵉ", "illi"],

    // --- Iranian — *dugdar held east of the Zagros -----------------------
    ave: ["𐬛𐬎𐬔𐬆𐬛𐬀𐬭", "duɡədar"],
    fa_clas: ["دختر", "duxtar"],
    prs: ["دختر", "duxˈtaɾ"],
    haz: ["دختر", "duxtar"],
    jpr: ["דוכתר", "doxˈtær"],
    xpr: ["duxt", "duxt"],
    os: ["чызг", "tʃəzɡ"],
    ku: ["keç", "kɛtʃ"],
    ckb: ["کچ", "kɪtʃ"],
    zza: ["keyna", "ˈkejna"],

    // --- Indo-Aryan — bēṭī, dhī, and the Prakrit that links them ---------
    pmh: ["धूआ", "dʱuːaː"],
    sa_edu: ["पुत्री", "putriː"],
    pnb: ["دھی", "d̪ʱiː"],
    skr: ["دھی", "d̪ʱiː"],
    hno: ["دھی", "d̪ʱiː"],
    sd: ["ڌيءَ", "d̪ʱiːa"],
    ks: ["کوٗر", "kuːr"],
    kok: ["धूव", "d̪ʱuːʋ"],
    or: ["ଝିଅ", "dʒʱiɔ"],
    bho: ["बेटी", "beːʈiː"],
    mai: ["बेटी", "beʈiː"],
    mag: ["बेटी", "beʈiː"],
    anp: ["बेटी", "beʈiː"],
    awa: ["बेटी", "beʈiː"],
    bra: ["बेटी", "beʈiː"],
    mwr: ["बेटी", "beːʈiː"],
    hne: ["बेटी", "beʈiː"],
    hns: ["beti", "beːʈiː"],
    hif: ["beti", "beːʈiː"],
    bgc: ["छोरी", "tʃʰoɾiː"],
    dty: ["छोरी", "tʃʰoɾiː"],
    rmy: ["čhej", "tʃʰej"],
    rom: ["čhaj", "tʃʰaj"],

    // --- Greek and Italic, the two ancient outliers ----------------------
    // Mycenaean still writes the inherited word; Oscan keeps it where Latin
    // had already gone over to fīlia.
    gmy: ["𐀶𐀏𐀳", "tʰugatɛːr"],
    osc: ["futír", "futiːr"],

    // --- East Asia -------------------------------------------------------
    zh_tw: ["女兒", "ny˨˩˦ ɚ˧˥"],
    zh_db: ["闺女", "kuei˥ ny"],
    zh_sc: ["女儿", "ny˥˧ ɚ˨˩"],
    zh_cd: ["女儿", "ny˥˧ ɚ˨˩"],
    zh_cq: ["女儿", "ny˦˨ ɚ˨˩"],
    yue_zs: ["女", "nɵy˩˧"],
    zh_wenyan_edu: ["女", "nɵy˩˧"],
    zh_tang: ["女", "nrjoX"],
    och: ["女", "*nraʔ"],
    vi_han: ["女", "nɨ˧˥"],
    ja_osa: ["娘", "mɯsɯme"],
    ja_kyo: ["娘", "mɯsɯme"],
    ja_hir: ["娘", "mɯsɯme"],
    ja_hak: ["娘", "mɯsɯme"],
    ja_edo: ["娘", "mɯsɯme"],
    ja_chu: ["娘", "musume"],
    ja_heian: ["娘", "musume"],
    ko_kp: ["딸", "t͈al"],
    ko_bus: ["딸", "t͈al"],
    ko_yb: ["딸", "t͈al"],
    ko_hg: ["딸", "t͈al"],
    ko_jl: ["딸", "t͈al"],
    // ko_jeju: Jeju writes daughter ᄄᆞᆯ, with arae-a — but that needs the Old
    // Hangul jamo U+1104 ᄄ, which is not in the self-hosted subset font (it has
    // 20 glyphs and no tool rebuilds it). It would be tofu on iPhone, so the row
    // is blank rather than broken. Same reason as four.vi_nom.
    ko_mid: ["ᄯᆞᆯ〮", "stʌl"],
    ko_em: ["ᄯᆞᆯ", "t͈ʌl"],
    ain: ["マッネポ", "matnepo"],

    // --- Tibetan bu mo, and the Tibeto-Burman "child + female" pattern ---
    bo: ["བུ་མོ", "pʰumo˥"],
    xct: ["བུ་མོ", "bumo"],
    xct_litpr: ["བུ་མོ", "bumo"],
    dz: ["བུ་མོ", "bumo"],
    bft: ["བུ་མོ", "bumo"],
    lbj: ["བུ་མོ", "bumo"],
    sip: ["བུ་མོ", "bumo"],
    xsr: ["བུ་མོ", "bumo"],
    rki: ["သမီး", "θəmí"],
    lus: ["fanu", "fanu"],
    cnh: ["fanu", "fanu"],

    // --- Mainland Southeast Asia — "child" plus "female" -----------------
    vi_s: ["con gái", "kɔŋ˧ ɣaːj˧˥"],
    vi_c: ["con gái", "kɔŋ˧ ɣaːj˧˥"],
    sukh: ["ลูกสาว", "luːk saːw"],
    kxm: ["កូនស្រី", "koːn srəj"],
    kha: ["khun kynthei", "kʰun kintʰei"],

    // --- Austronesian — very few of these rows have one word for it ------
    // Most say "child" + "female"; Batak boru, Chamorro haga' and the
    // Polynesian tamahine/ʻofefine group are the exceptions.
    bbc: ["boru", "boru"],
    ch: ["haga'", "haɡaʔ"],
    to: ["ʻofefine", "ʔofefine"],
    ty: ["tamahine", "tamahine"],
    rar: ["tamaine", "tamaine"],
    niu: ["tama fifine", "tama fifine"],
    tet: ["oan feto", "oan feto"],
    mg: ["zanaka vavy", "zanaka vavi"],
    jv: ["anak wadon", "anaʔ wadɔn"],
    su: ["anak awéwé", "anak awewe"],
    min: ["anak padusi", "anaʔ padusi"],
    ace: ["aneuk inöng", "aneuʔ inɔŋ"],
    iba: ["anak indu", "anak indu"],
    bew: ["anak perempuan", "anak pərəmpuan"],
    pmy: ["anak perempuan", "anak pərəmpuan"],
    ceb: ["anak nga babaye", "anak ŋa babaje"],
    hil: ["anak nga babayi", "anak ŋa babaji"],
    war: ["anak nga babaye", "anak ŋa babaje"],
    bik: ["aki na babayi", "aki na babaji"],
    ilo: ["anak a babai", "ʔanak a babai"],
    pam: ["anak a babai", "ʔanak a babai"],

    // --- Africa ----------------------------------------------------------
    rn: ["umukobwa", "umukobwa"],
    lg: ["omuwala", "omuwala"],
    ki: ["mwarĩ", "mwaɾɪ"],
    tn: ["morwadi", "morwadi"],
    st: ["morali", "moɾali"],
    nso: ["morwedi", "morwedi"],
    nd: ["indodakazi", "indodakazi"],
    nbl: ["indodakazi", "indodakazi"],
    ln: ["mwana mwasi", "mwana mwasi"],
    ak: ["ɔbabaa", "ɔbabaː"],
    bm: ["denmuso", "dɛnmuso"],
    dyu: ["denmuso", "dɛnmuso"],
    emk: ["denmuso", "dɛnmuso"],
    mnk: ["dimmusoo", "dimːusoː"],
    wo: ["doom ju jigéen", "doːm dʒu dʒiɡeːn"],

    // --- Americas, Caucasus and one very old "female child" --------------
    sux: ["𒌉𒊩", "dumu munus"],
    // Quechua and Aymara have a dedicated word, but Quechua's is a man's
    // daughter — a woman's child of either sex is wawa.
    qu: ["ususi", "uˈsusi"],
    quz: ["ususi", "uˈsusi"],
    quy: ["ususi", "uˈsusi"],
    qwc: ["ususi", "ususi"],
    ay: ["phucha", "pʰutʃa"],
    kl: ["panik", "panik"],
    iu: ["ᐸᓂᒃ", "panik"],
    ik: ["panik", "panik"],
    esu: ["panik", "panik"],
    ady: ["ыпхъу", "əpχʷ"],
    kbd: ["пхъу", "pχʷə"],
    av: ["яс", "jas"],
    lez: ["руш", "ruʃ"],
    lbe: ["душ", "duʃ"],
    dar: ["рурси", "rursi"],

    // --- Constructed and creole ------------------------------------------
    eo: ["filino", "fiˈlino"],
    ia: ["filia", "ˈfilia"],
    ie: ["filia", "ˈfilia"],
    io: ["filiino", "filiˈino"],
    vo: ["daut", "daut"],
    jbo: ["tixnu", "ˈtixnu"],
    tlh: ["puqbe'", "puqbɛʔ"],
    tok: ["jan lili meli", "jan lili meli"],
    ht: ["pitit fi", "pitit fi"],
    pap: ["yu muhé", "ju muhe"],
    jam: ["daata", "dɑːtə"],
    bzj: ["daata", "dɑːtə"],
    bah: ["daughter", "dɑːtə"],
    hwc: ["dawta", "dɑːtə"],
    srn: ["umapikin", "umapikin"],
    kri: ["gyal pikin", "ɡjal pikin"],
    pcm: ["girl pikin", "ɡɛl pikin"],
    tpi: ["pikinini meri", "pikinini meri"],

    // --- A second pass, checked against comparative sources --------------
    pdt: ["Dochta", "ˈdoxta"],
    wym: ["tohter", "ˈtɔxtɐ"],
    frr_amr: ["foomen", "ˈfoːmən"],
    wa: ["feye", "fɛj"],
    rgn: ["fiöla", "ˈfjøːla"],
    sc: ["fiza", "ˈfidza"],
    rup: ["hilje", "ˈhiʎe"],
    ext: ["ija", "ˈiha"],
    dv: ["ދި", "di"],
    mzn: ["دتر", "dəteɾ"],
    rhg: ["zíi", "ziː"],
    tyv: ["кыс", "qɯs"],
    ce: ["йоӏ", "joʕ"],
    tab: ["риш", "riʃ"],
    ani: ["йеши", "jeʃi"],
    kjj: ["риши", "riʃi"],
    ab: ["аԥҳа", "apʰħa"],
    bej: ["oot", "oːt"],
    sid: ["beetto", "beːtːo"],
    wal: ["michchiyo", "mitʃːijo"],
    ee: ["vinyɔnu", "viɲɔnu"],
    pjt: ["uṉṯal", "uɳʈal"],
    vi_nom: ["𡥵𡛔", "kɔn˧ ɣaːj˧˥"],
  },
};
