/**
 * The Proto-Indo-European word for egg, *h₂ōwyóm (probably a derivative of *h₂éwis 'bird'), gave Latin ōvum — whence Romance uovo, œuf, huevo and ovo — and, via Proto-Germanic *ajją, both German Ei and Old Norse egg. English 'egg' is itself a Norse import that displaced the native cognate 'ey' (Old English ǣġ) during the Middle Ages. Slavic *ajьe (Russian яйцо, Ukrainian яйце) shares the same root, while unrelated families supply their own words: Semitic (Arabic bayḍa, Hebrew beitza), Sino-Tibetan (Mandarin 蛋 dàn), and Proto-Austronesian *qateluR behind Malay/Indonesian telur and Tagalog itlog.
 */
WORDS.egg = {
  emoji: "🥚",
  label: {
    en: "Egg",
    ja: "卵",
    ko: "달걀",
    zh: "鸡蛋",
    yue: "雞蛋",
    vi: "Trứng",
    th: "ไข่",
    id: "Telur",
    hi: "अंडा",
    de: "Ei",
    fr: "Œuf",
    it: "Uovo",
    es: "Huevo",
    es_eu: "Huevo",
    es_mx: "Huevo",
    pt: "Ovo",
    pt_eu: "Ovo",
    pt_br: "Ovo",
    ru: "Яйцо",
    uk: "Яйце",
    ar: "بيضة",
    he: "ביצה",
    sw: "Yai",
  },
  definition: {
    en: "Egg — the rounded object laid by a bird (esp. a hen's egg as food); not a verb, not a technical ovum.",
    ja: "卵（たまご）— 鳥（特にニワトリ）が産む丸い殻に包まれたもので、食品となるもの。動詞や生物学用語の「卵子」ではない。",
    ko: "달걀 — 새(특히 암탉)가 낳는 둥근 알로, 음식으로 먹는 것. 동사나 전문 용어 '난자'가 아님.",
    zh: "鸡蛋 — 鸟类（尤指母鸡）所产的圆形带壳之物，可作食物；不是动词，也不是专业术语中的卵子。",
    yue: "雞蛋 — 雀鳥（尤其係雞乸）生嘅圓形有殼嘅嘢，可以食；唔係動詞，亦唔係專業意義嘅卵子。",
    vi: "Trứng — vật hình bầu dục do chim (nhất là gà mái) đẻ ra, dùng làm thức ăn; không phải động từ, không phải noãn theo nghĩa chuyên môn.",
    th: "ไข่ — สิ่งทรงรีที่นก (โดยเฉพาะแม่ไก่) ออกมา ใช้เป็นอาหาร; ไม่ใช่คำกริยา และไม่ใช่เซลล์ไข่ในความหมายทางเทคนิค.",
    id: "Telur — benda bulat lonjong yang dikeluarkan burung (terutama ayam betina), dimakan sebagai makanan; bukan kata kerja, bukan sel telur dalam arti teknis.",
    hi: "अंडा — पक्षी (विशेषकर मुर्गी) द्वारा दिया गया गोल कवचयुक्त पिंड जो भोजन के रूप में खाया जाता है; क्रिया नहीं, न ही तकनीकी अर्थ में डिंब।",
    de: "Ei — das rundliche, von einem Vogel (bes. einer Henne) gelegte Objekt, das als Nahrung dient; kein Verb, keine Eizelle im Fachsinn.",
    fr: "Œuf — objet arrondi pondu par un oiseau (surtout une poule), consommé comme aliment ; pas un verbe, pas l'ovule au sens technique.",
    it: "Uovo — l'oggetto tondeggiante deposto da un uccello (spec. una gallina), usato come alimento; non un verbo, non l'ovulo in senso tecnico.",
    es: "Huevo — objeto redondeado puesto por un ave (esp. una gallina) que se come como alimento; no un verbo, no el óvulo en sentido técnico.",
    es_eu: "Huevo — objeto redondeado puesto por un ave (esp. una gallina) que se come como alimento; no un verbo, no el óvulo en sentido técnico.",
    es_mx: "Huevo — objeto redondeado puesto por un ave (esp. una gallina) que se come como alimento; no un verbo, no el óvulo en sentido técnico.",
    pt: "Ovo — objeto arredondado posto por uma ave (esp. uma galinha), consumido como alimento; não é um verbo nem o óvulo no sentido técnico.",
    pt_eu: "Ovo — objeto arredondado posto por uma ave (esp. uma galinha), consumido como alimento; não é um verbo nem o óvulo no sentido técnico.",
    pt_br: "Ovo — objeto arredondado posto por uma ave (esp. uma galinha), consumido como alimento; não é um verbo nem o óvulo no sentido técnico.",
    ru: "Яйцо — округлый предмет в скорлупе, снесённый птицей (особенно курицей) и употребляемый в пищу; не глагол и не яйцеклетка в специальном смысле.",
    uk: "Яйце — округлий предмет у шкаралупі, знесений птахом (особливо куркою), який їдять як їжу; не дієслово й не яйцеклітина у спеціальному значенні.",
    ar: "بيضة — الجسم المستدير الذي يضعه الطائر (خاصة الدجاجة) ويؤكل طعامًا؛ ليس فعلًا ولا البويضة بالمعنى التقني.",
    he: "ביצה — העצם המעוגל שמטיל עוף (בייחוד תרנגולת) ונאכל כמזון; לא פועל ולא ביצית במובן המדעי.",
    sw: "Yai — kitu cha mviringo kinachotagwa na ndege (hasa kuku), kinacholiwa kama chakula; si kitenzi wala yai la uzazi kwa maana ya kitaalamu.",
  },
  data: {
    es_cr: ["huevo", "ˈweβo"],
    es_hn: ["huevo", "ˈweβo"],
    es_ni: ["huevo", "ˈweβo"],
    es_sv: ["huevo", "ˈweβo"],
    ar_jo: ["بيضة", "ˈbeːdˤa"],
    ar_ps: ["بيضة", "ˈbeːdˤa"],
    fr_lu: ["œuf", "œf"],
    fr_cm: ["œuf", "œf"],
    lb: ["Ee", "eː"],
    es_bo: ["huevo", "ˈweβo"],
    es_py: ["huevo", "ˈweβo"],
    es_pa: ["huevo", "ˈweβo"],
    es_pr: ["huevo", "ˈweβo"],
    es_do: ["huevo", "ˈweβo"],
    es_gt: ["huevo", "ˈweβo"],
    es_ec: ["huevo", "ˈweβo"],
    es_uy: ["huevo", "ˈweβo"],
    ar_sy: ["بيضة", "ˈbeːdˤa"],
    ar_ye: ["بيضة", "ˈbajdˤa"],
    ar_sa: ["بيضة", "ˈbajdˤa"],
    ar_lb: ["بيضة", "ˈbeːdˤa"],
    en_ph: ["egg", "ɛɡ"],
    fr_sn: ["œuf", "œf"],
    fr_ci: ["œuf", "œf"],
    fr_ht: ["œuf", "œf"],
    pt_mz: ["ovo", "ˈovu"],
    nl_be: ["ei", "ɛi"],
    en_us: ["egg", "ɛɡ"],
    en_ca: ["egg", "ɛɡ"],
    en_za: ["egg", "eɡ"],
    de_ch: ["Ei", "aɪ"],
    pt_ao: ["ovo", "ˈovu"],
    es_ve: ["huevo", "ˈweβo"],
    ca_va: ["ou", "ˈɔw"],
    ja: ["卵", "tamaɡo"],
    ja_osa: ["卵", "tamaɡo"],
    ja_hak: ["卵", "tamaɡo"],
    ja_kyo: ["卵", "tamaɡo"],
    ja_hir: ["卵", "tamaɡo"],
    ko: ["달걀", "talɡjal"],
    ko_bus: ["달걀", "talɡjal"],
    nan: ["卵", "nŋ̩"],
    wuu: ["蛋", "dɛ"],
    vi: ["trứng", "ʈɪŋ³⁵"],
    vi_c: ["trứng", "ʈɪŋ³⁵"],
    vi_s: ["trứng", "ʈɪŋ³⁵"],
    th: ["ไข่", "kʰaj²¹"],
    id: ["telur", "təˈlur"],
    ms: ["telur", "təˈlor"],
    hi: ["अंडा", "əɳɖaː"],
    bn: ["ডিম", "ɖim"],
    ur: ["انڈا", "əɳɖaː"],
    ta: ["முட்டை", "muʈːaɪ"],
    en: ["egg", "ɛɡ"],
    de: ["Ei", "aɪ"],
    fr: ["œuf", "œf"],
    it: ["uovo", "ˈwɔːvo"],
    es: ["huevo", "ˈweβo"],
    es_mx: ["huevo", "ˈweβo"],
    pt: ["ovo", "ˈovu"],
    pt_br: ["ovo", "ˈovu"],
    ru: ["яйцо", "jɪjˈtso"],
    ar: ["بيضة", "ˈbajdˤa"],
    he: ["ביצה", "bejˈtsa"],
    tr: ["yumurta", "jumuɾˈta"],
    sw: ["yai", "ˈjai"],
    tl: ["itlog", "ʔɪtˈloɡ"],
    mn: ["өндөг", "ɔndɔɡ"],
    sah: ["сымыыт", "sɨmɨːt"],
    km: ["ពង", "pɔŋ"],
    lo: ["ໄຂ່", "kʰaj²¹"],
    yo: ["ẹyin", "ɛjĩ"],
    zu: ["iqanda", "iǃáːnda"],
    am: ["እንቁላል", "ənkʼulal"],
    mg: ["atody", "aˈtudʲ"],
    fi: ["muna", "ˈmunɑ"],
    hu: ["tojás", "ˈtojaːʃ"],
    el: ["αυγό", "avˈɣo"],
    nl: ["ei", "ɛi"],
    pl: ["jajko", "ˈjajkɔ"],
    uk: ["яйце", "jɐjˈtsɛ"],
    sv: ["ägg", "ɛɡ"],
    no: ["egg", "æɡ"],
    da: ["æg", "ɛːɡ"],
    ro: ["ou", "ow"],
    ga: ["ubh", "ʊv"],
    eu: ["arrautza", "araʊtsa"],
    ka: ["კვერცხი", "kʼvɛrtsxi"],
    hy: ["ձու", "dzu"],
    hyw: ["ձու", "tsʰu"],
    nv: ["ayęęzhii", "ajẽːʒiː"],
    mi: ["hēki", "ˈheːki"],
    qu: ["runtu", "ˈɾuntu"],
    th_isan: ["ไข่", "kʰaj²¹"],
    th_n: ["ไข่", "kʰaj²¹"],
    th_s: ["ไข่", "kʰaj²¹"],
    jv: ["endhog", "ənɖʰɔɡ"],
    su: ["endog", "əndɔɡ"],
    ceb: ["itlog", "ʔitˈloɡ"],
    ilo: ["itlog", "ʔitˈloɡ"],
    sm: ["fuamoa", "fuɑˈmoɑ"],
    pa: ["ਆਂਡਾ", "ãːɖaː"],
    gu: ["ઈંડું", "ĩːɖũː"],
    si: ["බිත්තරය", "bit̪t̪ərəjə"],
    te: ["గుడ్డు", "ɡuɖːu"],
    kn: ["ಮೊಟ್ಟೆ", "moʈːe"],
    ml: ["മുട്ട", "muʈːa"],
    tg: ["тухм", "tuxʰm"],
    ku: ["hêk", "heːk"],
    ckb: ["هێلکە", "heːlka"],
    ps: ["هګۍ", "haɡəi"],
    az: ["yumurta", "jumuɾˈta"],
    gag: ["yumurta", "jumurta"],
    ug: ["تۇخۇم", "tuxum"],
    kk: ["жұмыртқа", "ʒʊmərtˈqa"],
    ky: ["жумуртка", "dʒumurtˈqa"],
    uz: ["tuxum", "tuˈxum"],
    tk: ["ýumurtga", "jumurtġa"],
    ar_eg: ["بيضة", "ˈbeːdˤɑ"],
    ar_lev: ["بيضة", "ˈbeːdˤa"],
    ar_gulf: ["بيضة", "ˈbeːdˤa"],
    ar_iq: ["بيضة", "ˈbeːdˤa"],
    ar_ma: ["بيضة", "ˈbiːdˤa"],
    arq: ["بيضة", "ˈbiːdˤa"],
    ar_tn: ["بيضة", "ˈbiːdˤa"],
    ar_sd: ["بيضة", "ˈbeːdˤa"],
    mt: ["bajda", "ˈbajda"],
    ig: ["àkwá", "àkʷá"],
    ha: ["ƙwai", "kʼʷai"],
    wo: ["nen", "nɛn"],
    so: ["ukun", "ukun"],
    om: ["hanqaaquu", "hanqaːquː"],
    rw: ["igi", "iɡi"],
    rn: ["igi", "iɡi"],
    xh: ["iqanda", "iǃáːnda"],
    sn: ["zai", "zai"],
    ny: ["dzira", "dzira"],
    en_aave: ["egg", "ɛɡ"],
    en_nz: ["egg", "eɡ"],
    en_au: ["egg", "eɡ"],
    sco: ["egg", "ɛɡ"],
    af: ["eier", "ˈɛiər"],
    de_at: ["Ei", "aɪ"],
    gsw: ["Ei", "ei"],
    nds: ["Ei", "ai"],
    is: ["egg", "ɛɡ"],
    gd: ["ugh", "u"],
    br: ["vi", "viː"],
    scn: ["ovu", "ˈɔvu"],
    co: ["ovu", "ˈɔvu"],
    ca: ["ou", "ˈɔw"],
    gl: ["ovo", "ˈɔβo"],
    be: ["яйка", "ˈjajka"],
    cs: ["vejce", "ˈvɛjtsɛ"],
    sk: ["vajce", "ˈʋajtsɛ"],
    sl: ["jajce", "ˈjaːjtsɛ"],
    sr: ["јаје", "ˈjaje"],
    bg: ["яйце", "jajˈtsɛ"],
    lt: ["kiaušinis", "kʲɛʊˈʃʲɪnʲɪs"],
    lv: ["ola", "ˈuɔla"],
    sq: ["vezë", "ˈvɛzə"],
    et: ["muna", "ˈmunɑ"],
    ht: ["ze", "ze"],
    tpi: ["kiau", "kiau"],
    se: ["monni", "ˈmonni"],
    vro: ["muna", "ˈmuna"],
    gn: ["rupiʼa", "ɾupiʔa"],
    as: ["কণী", "kɔni"],
    or: ["ଅଣ୍ଡା", "ɔɳɖaː"],
    en_in: ["egg", "ɛɡ"],
    en_ie: ["egg", "ɛɡ"],
    fy: ["aai", "aːi"],
    nn: ["egg", "æɡ"],
    fo: ["egg", "ɛɡ"],
    fr_qc: ["œuf", "œf"],
    fr_be: ["œuf", "œf"],
    fr_ch: ["œuf", "œf"],
    es_co: ["huevo", "ˈweβo"],
    es_cl: ["huevo", "ˈweβo"],
    es_ar: ["huevo", "ˈweβo"],
    es_cu: ["huevo", "ˈweβo"],
    es_pe: ["huevo", "ˈweβo"],
    lad: ["guevo", "ˈgwevo"],
    rm: ["ov", "ɔf"],
    eo: ["ovo", "ˈovo"],
    ia: ["ovo", "ˈovo"],
    hil: ["itlog", "ʔitˈloɡ"],
    mk: ["јајце", "ˈjajtsɛ"],
    lg: ["eggi", "ˈeɡːi"],
    st: ["lehe", "leɦe"],
    ay: ["k'awna", "kʼawna"],
    kl: ["mannik", "manːik"],
    os: ["айк", "ajk"],
    tet: ["tolun", "tolun"],
    min: ["talua", "talua"],
    ban: ["taluh", "taluh"],
    war: ["itlog", "ʔitˈloɡ"],
    fur: ["ûf", "uːf"],
    ast: ["güevu", "ˈgweβu"],
    kpv: ["кольк", "kolʲk"],
    udm: ["пуз", "puz"],
    mhr: ["муно", "muno"],
    kw: ["oy", "ɔɪ"],
    hr: ["jaje", "ˈjaje"],
    bs: ["jaje", "ˈjaje"],
    pam: ["ebun", "ʔɛbun"],
    io: ["ovo", "ˈovo"],
  },
};
