/**
 * green — the colour of grass, and the "grue" problem.
 * Many languages draw no line between green and blue: one word covers both,
 * the "grue" term. Where a language is like that, the same word given here
 * also appears in the "blue" concept — Vietnamese xanh, Irish glas, Korean
 * 푸르다, Japanese 青 (still the word on a "green" traffic light). Languages
 * that split green off use a dedicated word: Romance verde, Germanic green /
 * grün, Slavic зелёный — all, at root, from a verb meaning "to grow".
 */
WORDS.green = {
  label: {
    en: "Green",
    ja: "緑",
    ko: "초록",
    zh: "绿",
    yue: "綠",
    vi: "Xanh lá",
    th: "เขียว",
    id: "Hijau",
    hi: "हरा",
    de: "Grün",
    fr: "Vert",
    it: "Verde",
    es: "Verde",
    es_eu: "Verde",
    es_mx: "Verde",
    pt: "Verde",
    pt_eu: "Verde",
    pt_br: "Verde",
    ru: "Зелёный",
    uk: "Зелений",
    ar: "أخضر",
    he: "ירוק",
    sw: "Kijani",
  },
  definition: {
    en: "The basic colour term for green — the hue of grass and fresh leaves, lying between yellow and blue. The ordinary colour word; where a language has a single 'grue' term covering both green and blue, that shared word is given here (and also appears under 'blue').",
    ja: "緑の基本色名——草や若葉の色で、黄と青の間にある色相。日常の色語を採り、緑と青を一語でまとめる「grue（青緑）」型の言語では、その共通語をここに載せる（「青」の項にも現れる）。",
    ko: "녹색을 가리키는 기본 색이름 — 풀과 새잎의 빛깔로, 노랑과 파랑 사이의 색조이다. 일상적인 색낱말을 싣되, 초록과 파랑을 한 낱말로 아우르는 'grue'형 언어에서는 그 공통 낱말을 여기에 싣는다('파랑' 항목에도 나타난다).",
    zh: "绿的基本颜色词——草和嫩叶的颜色，位于黄与蓝之间的色相。取日常的颜色词；若语言用一个「grue」词同时涵盖绿与蓝，则在此列出该共用词（它也出现在「蓝」条目中）。",
    yue: "綠嘅基本顏色詞——草同嫩葉嘅顏色，喺黃同藍之間嘅色相。取日常嘅顏色詞；若語言用一個「grue」詞同時涵蓋綠同藍，就喺呢度列出嗰個共用詞（佢亦會出現喺「藍」條目度）。",
    vi: "Từ chỉ màu cơ bản cho màu xanh lá — sắc của cỏ và lá non, nằm giữa vàng và lam. Lấy từ chỉ màu thường ngày; ở những ngôn ngữ có một từ 'grue' bao gồm cả xanh lá lẫn xanh lam, từ dùng chung ấy được ghi ở đây (và cũng xuất hiện ở mục 'xanh lam').",
    th: "คำเรียกสีพื้นฐานสำหรับสีเขียว — สีของหญ้าและใบไม้อ่อน อยู่ระหว่างสีเหลืองกับสีน้ำเงินในสเปกตรัม เอาคำเรียกสีที่ใช้ในชีวิตประจำวัน ภาษาที่มีคำ 'grue' คำเดียวครอบคลุมทั้งเขียวและน้ำเงิน จะลงคำร่วมนั้นไว้ที่นี่ (และปรากฏในหมวด 'น้ำเงิน' ด้วย)",
    id: "Istilah warna dasar untuk hijau — warna rumput dan daun muda, terletak antara kuning dan biru. Kata warna sehari-hari; pada bahasa yang memiliki satu kata 'grue' yang mencakup hijau sekaligus biru, kata bersama itu dicantumkan di sini (dan juga muncul di konsep 'biru').",
    hi: "हरे रंग का मूल रंग-शब्द — घास और नई पत्तियों का रंग, जो पीले और नीले के बीच पड़ता है। रोज़मर्रा का रंग-शब्द; जिन भाषाओं में एक ही 'grue' शब्द हरे और नीले दोनों को समेटता है, वहाँ वही साझा शब्द यहाँ दिया गया है (जो 'नीला' संकल्पना में भी आता है)।",
    de: "Die Grundfarbbezeichnung für Grün — die Farbe von Gras und frischen Blättern, zwischen Gelb und Blau gelegen. Das alltägliche Farbwort; wo eine Sprache ein einziges 'Grue'-Wort für Grün und Blau zugleich hat, steht hier dieses gemeinsame Wort (es erscheint auch beim Konzept 'Blau').",
    fr: "Le terme de couleur fondamental pour le vert — la teinte de l'herbe et des jeunes feuilles, entre le jaune et le bleu. Le mot courant de la couleur ; là où une langue a un seul mot 'grue' couvrant à la fois le vert et le bleu, ce mot commun figure ici (et apparaît aussi au concept 'bleu').",
    it: "Il termine cromatico fondamentale per il verde — il colore dell'erba e delle foglie fresche, tra il giallo e il blu. La parola comune del colore; dove una lingua ha un unico termine 'grue' che copre insieme verde e blu, qui è riportata quella parola condivisa (che compare anche nel concetto 'blu').",
    es: "El término cromático básico para el verde — el color de la hierba y las hojas frescas, entre el amarillo y el azul. La palabra corriente del color; donde una lengua tiene un único término 'grue' que abarca a la vez el verde y el azul, aquí se da esa palabra compartida (que también aparece en el concepto 'azul').",
    es_eu: "El término cromático básico para el verde — el color de la hierba y las hojas frescas, entre el amarillo y el azul. La palabra corriente del color; donde una lengua tiene un único término 'grue' que abarca a la vez el verde y el azul, aquí se da esa palabra compartida (que también aparece en el concepto 'azul').",
    es_mx: "El término cromático básico para el verde — el color de la hierba y las hojas frescas, entre el amarillo y el azul. La palabra corriente del color; donde una lengua tiene un único término 'grue' que abarca a la vez el verde y el azul, aquí se da esa palabra compartida (que también aparece en el concepto 'azul').",
    pt: "O termo cromático básico para o verde — a cor da relva e das folhas frescas, entre o amarelo e o azul. A palavra corrente da cor; onde uma língua tem um único termo 'grue' que abrange verde e azul ao mesmo tempo, dá-se aqui essa palavra partilhada (que também surge no conceito 'azul').",
    pt_eu: "O termo cromático básico para o verde — a cor da relva e das folhas frescas, entre o amarelo e o azul. A palavra corrente da cor; onde uma língua tem um único termo 'grue' que abrange verde e azul ao mesmo tempo, dá-se aqui essa palavra partilhada (que também surge no conceito 'azul').",
    pt_br: "O termo cromático básico para o verde — a cor da grama e das folhas frescas, entre o amarelo e o azul. A palavra corrente da cor; onde uma língua tem um único termo 'grue' que abrange verde e azul ao mesmo tempo, dá-se aqui essa palavra compartilhada (que também aparece no conceito 'azul').",
    ru: "Основное цветообозначение для зелёного — цвет травы и свежей листвы, между жёлтым и синим. Обиходное слово для цвета; там, где в языке есть единое слово-'grue', охватывающее и зелёный, и синий, здесь приводится это общее слово (оно встречается и в понятии 'синий').",
    uk: "Основна назва кольору для зеленого — колір трави та свіжого листя, між жовтим і синім. Повсякденне слово на позначення кольору; там, де мова має єдине слово-'grue', що охоплює і зелений, і синій, тут наведено це спільне слово (воно трапляється й у понятті 'синій').",
    ar: "المصطلح اللوني الأساسي للأخضر — لون العشب والأوراق الغضّة، ويقع بين الأصفر والأزرق. الكلمة اليومية للّون؛ وحيث تملك اللغة كلمة 'grue' واحدة تشمل الأخضر والأزرق معًا، تُذكر هنا تلك الكلمة المشتركة (وتظهر أيضًا في مفهوم 'الأزرق').",
    he: "מונח הצבע הבסיסי לירוק — גון הדשא והעלים הרעננים, שבין הצהוב לכחול. מילת הצבע היומיומית; במקום שבו לשפה יש מילת 'grue' אחת המקיפה גם ירוק וגם כחול, ניתנת כאן אותה מילה משותפת (והיא מופיעה גם במושג 'כחול').",
    sw: "Neno la msingi la rangi ya kijani — rangi ya majani na nyasi mbichi, iliyo kati ya njano na buluu. Neno la kawaida la rangi; pale lugha inapokuwa na neno moja la 'grue' linalojumuisha kijani na buluu pamoja, neno hilo la pamoja hutolewa hapa (nalo hujitokeza pia katika dhana ya 'buluu').",
  },
  data: {
    en: ["green", "ɡɹiːn"],
    de: ["grün", "ɡʁyːn"],
    nl: ["groen", "ɣrun"],
    sv: ["grön", "ɡrøːn"],
    no: ["grønn", "ɡrœnː"],
    da: ["grøn", "ɡʁœˀn"],
    fr: ["vert", "vɛʁ"],
    es: ["verde", "ˈbeɾðe"],
    it: ["verde", "ˈverde"],
    pt: ["verde", "ˈveɾðɨ"],
    pt_br: ["verde", "ˈveʁdʒi"],
    ro: ["verde", "ˈverde"],
    ca: ["verd", "bɛrt"],
    ru: ["зелёный", "zʲɪˈlʲonɨj"],
    uk: ["зелений", "zeˈlɛnɪj"],
    pl: ["zielony", "ʑɛˈlɔnɨ"],
    cs: ["zelený", "ˈzɛlɛniː"],
    el: ["πράσινο", "ˈprasino"],
    ja: ["緑", "midoɾi"],
    ko: ["초록", "tɕʰoɾok̚"],
    zh: ["绿", "ly˥˩"],
    yue: ["綠", "lʊk˨"],
    vi: ["xanh lá", "saɲ˧ laː˧˥"],
    th: ["เขียว", "kʰiaw˩˩˦"],
    id: ["hijau", "ˈhidʒau"],
    ms: ["hijau", "ˈhidʒau"],
    tl: ["berde", "ˈbɛɾde"],
    hi: ["हरा", "ɦəˈraː"],
    bn: ["সবুজ", "ʃobudʒ"],
    ta: ["பச்சை", "patːɕai"],
    te: ["ఆకుపచ్చ", "aːkupatʃːa"],
    fa: ["سبز", "sæbz"],
    tr: ["yeşil", "jeˈʃil"],
    ar: ["أخضر", "ˈʔaxdˤar"],
    he: ["ירוק", "jaˈʁok"],
    sw: ["kijani", "kiˈdʒani"],
    fi: ["vihreä", "ˈʋihreæ"],
    hu: ["zöld", "zøld"],
    eu: ["berde", "ˈbeɾde"],
    ga: ["glas", "ɡlˠasˠ"],
    cy: ["gwyrdd", "ɡwɪrð"],
    af: ["groen", "xrun"],
    fy: ["grien", "ɡriən"],
    lb: ["gréng", "ɡʁɛːŋ"],
    yi: ["גרין", "ɡrin"],
    fo: ["grønur", "ˈɡrøːnʊr"],
    gl: ["verde", "ˈbeɾðe"],
    oc: ["verd", "bet"],
    co: ["verde", "ˈverde"],
    sc: ["birde", "ˈbirde"],
    fur: ["vert", "vɛrt"],
    rm: ["verd", "vɛrt"],
    vec: ["verde", "ˈverde"],
    scn: ["virdi", "ˈvɪrdɪ"],
    ht: ["vèt", "vɛt"],
    be: ["зялёны", "zʲaˈlʲɔnɨ"],
    mk: ["зелен", "ˈzɛlɛn"],
    bs: ["zelen", "zelen"],
    sr: ["зелен", "zelen"],
    hr: ["zelen", "zelen"],
    sl: ["zelen", "zɛˈleːn"],
    sk: ["zelený", "ˈzɛleniː"],
    bg: ["зелен", "zeˈlɛn"],
    lt: ["žalias", "ʒɐˈlʲas"],
    lv: ["zaļš", "zaʎʃ"],
    et: ["roheline", "ˈroheline"],
    gd: ["uaine", "ˈuəɲə"],
    br: ["gwer", "ɡwɛr"],
    az: ["yaşıl", "jaˈʃɯl"],
    kk: ["жасыл", "ʒɑˈsəl"],
    ky: ["жашыл", "dʒaˈʃɯl"],
    uz: ["yashil", "jaˈʃil"],
    tt: ["яшел", "jɑˈʃel"],
    ku: ["kesk", "kɛsk"],
    tg: ["сабз", "sabz"],
    ps: ["شین", "ʃin"],
    pa: ["ਹਰਾ", "ɦəˈɾaː"],
    gu: ["લીલો", "ˈliːlo"],
    mr: ["हिरवा", "ɦiɾʋaː"],
    ne: ["हरियो", "ɦəɾijo"],
    ur: ["ہرا", "ɦəˈraː"],
    si: ["කොළ", "koɭə"],
    or: ["ସବୁଜ", "sɔbudʒɔ"],
    jv: ["ijo", "ˈidʒo"],
    su: ["héjo", "ˈhedʒo"],
    ceb: ["berde", "ˈbɛrde"],
    mi: ["kākāriki", "kaːkaːɾiki"],
    haw: ["ʻōmaʻomaʻo", "ʔoːmaʔomaʔo"],
    mt: ["aħdar", "ˈaħdar"],
    sq: ["jeshil", "jɛˈʃil"],
    hy: ["կանաչ", "kɑˈnɑtʃ"],
    // Mesoamerica, from the ALMG vocabularies and Kaufman & Justeson's PMED.
    // Mayan *raʔx is a grue etymon, and the daughters here still are.
    itz: ["yaʼax", "jaʔaʃ"],   // ALMG's Itzaʼ vocabulary entry 1574 for verde; its Indumentaria volume uses the same word of indigo dye against Spanish "azul", so grue. Itzaʼ chʼoj exists but names the añil plant, not the colour.
    ixl: ["chaʼx", "tʃaʔʃ"],   // ALMG Ixil, Cotzal/Nebaj form (Chajul has tchaʼx), and Kaufman's OKMA form. Blue is undetermined: that vocabulary has no Azul headword at all, so this row's grue status is open rather than settled.
    huv: ["nateaik", "natʲaik"],  // Stairs & Stairs' Huave dictionary, and the World Color Survey has 23 of 25 speakers naming it with green foci. Distinct rather than grue: 24 of 25 gave the Spanish loan azul for blue, and the dictionary has no azul entry. ⟨c⟩ → k and ⟨tea⟩ = /tʲa/ follow this row's own kawak and kiet /kʲet/.
    hch: ["siïraïyeme", "siɨraɨjeme"],  // Lower confidence than the rest: McIntosh & Grimes, Grimes 1981 and the Glosario Wixárika all put this first for 'verde', but it is a long derived form and Grimes also glosses yuavi as "verde, azul de color". A modern speaker source would settle whether this is what one reaches for pointing at grass.
    ka: ["მწვანე", "mtsʼvane"],
    kbd: ["удзыфэ", "wədzəfa"],  // udz 'grass' + фэ 'colour', the same compound as Adyghe уцышъо already in this row; Wiktionary lemmatises both as colour adjectives, so they are lexicalised terms rather than the ad-hoc "leaf-coloured" descriptions this concept declines — the same reading that lets Swahili kijani in.
    am: ["አረንጓዴ", "arənˈɡʷade"],
    ha: ["kore", "ˈkoːre"],
    zu: ["luhlaza", "luˈɬaːza"],
    xh: ["luhlaza", "luˈɬaːza"],
    so: ["cagaar", "ʕaɡaːr"],
    mg: ["maitso", "maˈitsu"],
    rw: ["icyatsi", "iˈtʃaːtsi"],
    qu: ["qʼomer", "qʼomeɾ"],
    gn: ["hovyũ", "hoʋɨˈʔũ"],
    // South America, sourced from CLDF datasets and from Bible translations that
    // pin the sense in context. The first three are grue.
    guc: ["wüitüsü", "wɨitɨsɨ"],   // IDS gives the identical form for its blue (15-670) and green (15-680) entries — about as clean as grue evidence gets. Huber & Reed write a geminate tt; the Wayuunaiki Wikipedia, which has separate articles Wuitüsü 'verde' and Wuitus 'azul' from this root, writes one.
    gum: ["chilga", "tʃilka"],        // Huber & Reed 1992 for VERDE, and the Guambiano NT uses it of grass (Mark 6:39, Rev 8:7) and of hyacinth-blue (Rev 9:17) — so grue, though the blue side rests on that one verse. Huber transcribes lʲ; ʎ follows the atlas's own jallu → xaʎu.
    gun: ["ovy", "ovɨ"],           // Same lexeme as the blue cell already in the row. The Mbyá NT settles it in one translator's hand: nhuũ hovy 'green grass' (Mark 6:39) against jacinto rami hovy va'e 'blue like hyacinth' (Rev 9:17). Not ovyũ.
    guu: ["ɾijə", "ɾijə"],         // Lizot via IDS, and Bowern's hunter-gatherer database citing five independent sources. Distinct from the row's 'blue' uši, which is really 'dark' (near-identical to iši 'black'), but green itself is a real lexeme here.
    gym: ["rerebare", "ɾeɾebaɾe"], // Ngäbere NT, five occurrences, all colour — including Rev 4:3 glossing it against the emerald. Constenla's kare was rejected: the Talking Dictionary that matches this row word for word has kare as the verb 'to sing', with no colour sense.
    jiv: ["sámek", "ˈsamek"],      // Pellizzaro's Chicham dictionary via northperulex; the Shuar NT has numi sameka 'the green tree' at Luke 23:31. Shuar ⟨e⟩ is phonemically [ɨ] and both sources write samɨk, but this row renders ⟨e⟩ as e throughout (penker → peŋkeɾ), so e it is.
    eo: ["verda", "ˈverda"],
    ab: ["аиаҵәа", "ajatsʼʷa"],
    ace: ["ijo", "iɟo"],
    acf: ["vèt", "vɛt"],
    ady: ["уцышъо", "wətsəʂʷa"],
    aii: ["ܝܲܪܘܿܩܵܐ", "jaroqa"],
    ain: ["シウニン", "siwnin"],
    akb: ["rata", "rata"],
    akk: ["𒅊", "warqu"],
    alt: ["јажыл", "ɟaˈʒɯl"],
    an: ["verde", "ˈbeɾde"],
    ang: ["grēne", "ɡreːne"],
    anp: ["हरियर", "ɦərijər"],
    ar_eg: ["أخضر", "ˈʔaxdˤaɾ"],
    ar_ma: ["خضر", "xdˤəɾ"],
    ar_qur: ["أخضر", "ʔaxdˤaru"],
    ar_sd: ["أخضر", "ˈaxdˤar"],
    ar_tn: ["أخضر", "ˈaxdˤaɾ"],
    arn: ["karü", "kaɾɨ"],
    arq: ["خضر", "xdˤaɾ"],
    as: ["সেউজীয়া", "xeuzia"],
    ast: ["verde", "ˈbeɾðe"],
    ay: ["chʼuxña", "tʃʼuxɲa"],
    ayl: ["أخضر", "ˈʔaxdˤar"],
    azb: ["یاشیل", "jaˈʃɯl"],
    ba: ["йәшел", "jæˈʃel"],
    ban: ["gadang", "ɡadaŋ"],
    bar: ["grea", "ɡreɐ"],
    bbc: ["rata", "rata"],
    bew: ["ijo", "ˈidʒo"],
    bgc: ["हरा", "ɦəraː"],
    bho: ["हरियर", "ɦərijər"],
    bi: ["grin", "ɡrin"],
    bik: ["berde", "ˈbɛrde"],
    blt: ["ꪵꪄꪫ", "kʰɛw˨"], // tone: unmarked high-class ꪄ = ˨˦, as ꪼꪎ sai˨˦ (2026-10-02)
    bo: ["ལྗང་ཁུ", "tɕəŋ˩˧ku˥"],
    brx: ["गोथां", "ɡotʰaŋ"],
    bug: ["kudara", "kudara"],
    bxr: ["ногоон", "noˈɡoːŋ"],
    cak: ["räx", "rəʃ"],
    cbk: ["verde", "ˈberde"],
    cdo: ["绿", "luoʔ˥"],
    ce: ["баьццара", "bætsːara"],
    ch: ["betde", "ˈbetde"],
    chr: ["ᎢᏤᏳᏍᏗ", "itsejusdi"],
    cic: ["okchamali", "oktʃamali"],
    cjs: ["чажыл", "tʃaˈʒɯl"],
    cjy: ["绿", "luəʔ˨"],
    ckb: ["سەوز", "sæwz"],
    cmg: ["ᠨᠣᠭᠤᠭᠠᠨ", "noɣuɣan"],
    cnh: ["hring", "hriŋ"],
    cnp: ["綠", "lœk˨˦"],
    cpx: ["绿", "lɒʔ˦"],
    cr: ["ᐊᐢᑭᐦᑕᒁᐤ", "askihtakwaːw"],
    crh: ["yeşil", "jeˈʃil"],
    crk: ["ᐊᐢᑭᐦᑕᒁᐤ", "askihtakwaːw"],
    crs: ["ver", "ver"],
    csb: ["zelony", "zɛˈlɔnɨ"],
    ctu: ["yäjyäx", "jɨhjɨʃ"],
    cu: ["зеленъ", "zelenŭ"],
    cv: ["ешӗл", "jeˈʒɘl"],
    dlg: ["күөк", "kyøk"],
    doi: ["हरा", "ɦəraː"],
    dsb: ["zeleny", "ˈzɛlɛnɨ"],
    dtp: ["otomou", "otomou"],
    dty: ["हरियो", "ɦərijo"],
    dv: ["ފެހި", "fehi"],
    egy: ["𓇅", "waːɟ"],
    el_grc: ["χλωρός", "kʰlɔːrós"],
    el_kath: ["πράσινος", "ˈprasinos"],
    emy: ["yax", "jaʃ"],
    enf: ["pozeraha", "pɔzʲɛraha"],
    enm: ["grene", "ɡreːnə"],
    enq: ["sakapae", "sakapae"],
    ess: ["ӄигуӷмылӈуӄ", "qiɡuɣmɨlŋuq"],
    evn: ["чуларин", "tʃularin"],
    ext: ["verdi", "ˈbeɾði"],
    fa_clas: ["سبز", "sabz"],
    fia: ["bessi", "besːi"],
    fj: ["drokadroka", "ndrokandroka"],
    fro: ["vert", "vɛrt"],
    frr_amr: ["green", "ɡreːn"],
    gaa: ["ŋoli", "ŋoli"],
    gag: ["eşil", "eˈʃil"],
    gan: ["绿", "liuʔ˥"],
    gay: ["ijo", "idʒo"],
    gez: ["ሐመልሚል", "ħamalmiːl"],
    gil: ["mawawa", "mawawa"],
    gld: ["нёӈгиан", "nʲoŋɡian"],
    glk: ["سبز", "sabz"],
    gmh: ["grüene", "ɡryənə"],
    goh: ["gruoni", "ɡruoni"],
    gor: ["moyidu", "mojidu"],
    gsw: ["grüen", "ɡryən"],
    gv: ["glass", "ɡlaːs"],
    h_vedic: ["हरितः", "háritɐɦ"],
    hak_cn: ["绿", "liʊk̚˥"],
    hak_tw: ["綠", "liuk̚˥"],
    haz: ["سبز", "sabz"],
    he_mis: ["ירוק", "jaˈroq"],
    hil: ["berde", "ˈbɛrde"],
    hmn: ["ntsuab", "ᶯdʐua˥"],
    ho: ["gadoka gadoka", "ɡadoka ɡadoka"],
    hop: ["sakwa", "sakʷa"],
    hsb: ["zeleny", "ˈzɛlɛnɨ"],
    hsn: ["绿", "ləu˨˦"],
    huz: ["ничду", "nitʃdu"],
    hy_grab: ["կանաչ", "kɑnɑtʃ"],
    hyw: ["կանաչ", "ɡɑˈnɑtʃ"],
    ia: ["verde", "ˈverde"],
    iba: ["ijau", "idʒau"],
    ie: ["verd", "verd"],
    ik: ["suŋaaqtaaq", "suŋaːqtaːq"],
    ilo: ["berde", "ˈbɛrde"],
    inh: ["баьццара", "bætsːara"],
    io: ["verda", "ˈverda"],
    is: ["grænn", "kraitn̥"],
    itb: ["maharem", "maharɨm"],
    itl: ["фӆлаҳ", "ɸɬlaχ"],
    ivv: ["maarem", "maarɨm"],
    ja_oki: ["おーさん", "oːsaɴ"],
    jam: ["griin", "ɡɹiːn"],  // Was grin, which in Cassidy-JLU spells /ɡrɪn/ — a different word. jam.wikipedia has griin 20 times and grin not once ("Yelo a di kola bitwiin griin ah arinj"); Cassidy writes /iː/ as ⟨ii⟩, as in chrii 'three'.
    gcf: ["vè", "vɛ"],        // Guadeloupe is vè, not the Haitian/St Lucian vèt: the colour table this comes from also gives wouj/blan/nwè/blé, which match this row exactly. Weaker than the others here — Ludwig/Telchid and Tourneux & Barbotin were out of reach.
    gcr: ["vèrt", "vɛʁt"],    // fr.wiktionary's Guianese entry, with Lingua Libre recordings by Cayenne speakers; gcr.wikipedia uses it 33 times (té vèrt, bwa vèrt). Genuinely not a copy of gcf's vè.
    hai: ["sg̱inuwáa", "sɢinuwɑ́ː"],  // Lachler's Dictionary of Alaskan Haida, the same source as this row's ǥadáang, lists it first under 'green' and glosses it green only. Held with a caveat: Haida also has kʼánhlahl 'yellow, green, yellow-green', which carries all the dictionary's green example sentences, so the system may really be a grellow term plus this vivid-green one, which is transparently derived from sǥináaw 'green algae'.
    hup: ["łitsow", "ɬitsow"],  // Grue, and the compounds prove it: tłʼoh-łitsow 'grass' is literally grass-łitsow and miqʼos-łitsow 'mallard' is its-neck-is-łitsow.
    jbo: ["crino", "ˈʃrino"],
    kaa: ["jasıl", "ʒɑˈsɯl"],
    kab: ["azegzaw", "azɡzaw"],
    kaw: ["ꦲꦶꦗꦺꦴ", "hidʒo"],
    kca: ["восты", "ˈwostɪ"],
    kea: ["verdi", "ˈveɾdi"],
    kek: ["rax", "raʃ"],
    ket: ["съʼнь", "səʔnʲ"],
    khb: ["ᦵᦃᧁ", "xeu"],
    khv: ["хъаилӏе", "qʼaiˈlʼe"],
    kjb: ["yax", "jaʂ"],
    kl: ["qorsuk", "qoχsuk"],
    kln: ["nyalil", "ɲalil"],
    km: ["បៃតង", "ɓajtɑːŋ"],
    kmh: ["kmab", "kmab"],
    kn: ["ಹಸಿರು", "hasiru"],
    ko_em: ["푸르다", "puɾɯda"],
    ko_mid: ["프르다", "pʰɨɾɨda"],
    koi: ["веж", "veʒ"],
    kok: ["पाचवो", "paːtʃʋo"],
    kpf: ["gwolâ gwolâ", "ɡwolɐ ɡwolɐ"],
    kpj: ["tyre", "tɨ̃re"],
    kpv: ["веж", "veʒ"],
    krc: ["джашил", "dʒaˈʃil"],
    kri: ["grin", "ɡrin"],
    krl: ["vihanta", "ˈvihanta"],
    ks: ["سَبٕز", "sabɨz"],
    ksh: ["jröön", "jʁøːn"],
    kum: ["яшыл", "jaˈʃɯl"],
    kw: ["gwyrdh", "ɡwɪrð"],   // The artificial-green term, and the one a Cornish colour chart gives for green; glas (already this row's 'blue') is what covers plants and the sea, so Cornish is grue on the natural side and lexicalised on the made side.
    la: ["viridis", "ˈwɪrɪdɪs"],
    lad: ["vedre", "ˈveðɾe"],
    lbe: ["щюлисса", "ɕːjulisːa"],
    lez: ["къацу", "qatsu"],
    lic: ["khi:u1", "kʰiːu˥˧"],   // Grue: IDS gives khi:u.1 for both blue and green in Baoting Hlai, which is why this repeats the cell already in 'blue'.
    lij: ["vèrde", "ˈvɛrde"],
    liv: ["ǭļaz", "ˈoːʎaz"],   // Wiktionary lemmatises it at ǭļaz; NorthEuraLex writes the same word ōļaz, without the ogonek that Livonian orthography needs.
    lkt: ["tȟózi", "ˈtxozi"],   // Literally tȟó 'blue' + zí 'yellow'. Lakota can also say plain tȟó of green things, so this is the specific term inside a grue system, not a separate basic colour.
    lld: ["vërt", "vərt"],
    lmo: ["verd", "vert"],
    lo: ["ຂຽວ", "kʰiːəw˩˧"],
    ltg: ["zaļš", "zaʎʃ"],
    lus: ["hring", "hriŋ"],
    mad: ["bhiru", "bʱiru"],   // Grue, and the same cell as this row's 'blue'. ABVD records Madurese green as biru, without the aspiration mark that distinguishes bh from b — the aspirated spelling is the dictionary one.
    mak: ["moncong bulo", "moɲtʃoŋ bulo"],   // Literally 'bamboo colour', but lemmatised as the colour noun by Wiktionary and elicited as green by ABVD.
    max: ["ijo", "idʒo"],
    mbc: ["rora", "rora"],   // Grue: IDS gives rora for both blue and green in Macushi, matching the cell already in 'blue'.
    mdf: ["пиже", "ˈpiʒe"],
    mdh: ["gadung", "ˈɡaduŋ"],
    meu: ["gadokagadoka", "ɡadokaɡadoka"],
    mfe: ["ver", "vɛr"],
    mh: ["maroro", "mʲɑːrˠɔːrˠɔ"],   // The native term; kūriin is the English loan, used of one flat shade. MEOD glosses maroro as the green of patterned or mottled things, which is what Marshallese reaches for of vegetation.
    mhr: ["ужар", "uˈʒar"],
    min: ["ijau", "idʒau"],
    ml: ["പച്ച", "patʃːə"],
    mlm: ["śau1", "ɕau˦˨"],
    mmd: ["ju1", "ju˦˨"],
    mn: ["ногоон", "nɔɡɔːŋ"],
    mnc: ["ᠨᡳᠣᠸᠠᠩᡤᡳᠶᠠᠨ", "niowaŋɡijan"],
    mns: ["няртпумоспа", "ɲartpumospa"],   // 'Fresh-grass-coloured', but both IDS and NorthEuraLex elicit it as the green term and Mansi dictionaries lemmatise it as an adjective — the same reading that lets Kabardian удзыфэ in above.
    mrj: ["ыжар", "əˈʒar"],
    mrw: ["gadong", "ˈɡadoŋ"],
    mwl: ["berde", "ˈbeɾðɨ"],
    my: ["စိမ်း", "séɪɴ"],
    myv: ["пиже", "ˈpiʒe"],
    mzh: ["watsan", "watsan"],   // Grue: IDS and WOLD both give wa'c̷an / w'atshan for blue and green alike in Wichí, so this repeats the 'blue' cell.
    nan: ["綠", "liɪk˦"],
    nan_pn: ["青色", "tsʰẽ˧˧ sek˧"],
    nan_qz: ["绿", "liak˨˦"],
    nan_te: ["青色", "tsʰẽ˧˧ sek˨"],
    nan_zz: ["绿", "liɪk̚˩˨˩"],
    nap: ["verde", "ˈverdə"],
    naq: ["ǃgam", "ǃɡam"],
    nbl: ["hlaza", "ɬaːza"],   // Nguni luhlaza covers green and blue together; the cell is the same as this row's 'blue', as it is for zu and xh already.
    nci: ["xoxoctic", "ʃoʃoktik"],
    nd: ["luhlaza", "luɬaːza"],
    nds: ["gröön", "ɡrøːn"],
    nij: ["bahijau", "bahidʒau"],
    nn: ["grøn", "ɡrøːn"],
    non: ["grǿnn", "ɡrøːnː"],
    nrf: ["vèrt", "vɛr"],   // Jersey. Guernésiais has its own vaert, left out because no source gives the value of its ⟨ae⟩.
    nso: ["tala", "tala"],   // Grue, same cell as 'blue'.
    nv: ["dootłʼizh", "tòːtɬʼìʒ"],   // Grue: one term across blue, green and turquoise, so the same cell as 'blue'.
    oar: ["ירק", "jraːq"],
    ofs: ["grēne", "ˈɡreːne"],
    oj: ["ozhaawashkwaa", "oʒaːwaʃkwaː"],   // Grue: the inanimate verb 'it is blue/green', identical to this row's 'blue'.
    olo: ["vihandu", "ˈvihandu"],
    om: ["magariisa", "maɡariːsa"],   // Wiktionary files the commoner spelling magarisa as a misspelling of this one.
    orh: ["tʃuturin", "tʃuturin"],
    os: ["цъӕх", "tsʼæx"],   // Grue: IDS and NorthEuraLex both give цъӕх for blue and green alike; кӕрдӕгхуыз 'grass-coloured' is the descriptive green, not the basic term.
    osx: ["grōni", "ˈɡroːni"],
    ota: ["یشیل", "jeˈʃil"],
    pam: ["aluntian", "ʔaluntiˈan"],
    pap: ["bèrdè", "ˈbɛrdɛ"],
    pdc: ["grie", "ɡriː"],
    pdt: ["jreen", "jɾeːn"],
    pkp: ["yengayenga", "ðeŋaðeŋa"],   // Grue: ABVD elicits it for green and it is already this row's 'blue'.
    pms: ["verd", "vɛrt"],
    pnb: ["ہرا", "ɦəraː"],
    pon: ["pohndipw", "poːndipʷ"],
    mhy: ["kakuriŋ", "kakuriŋ"],
    dje: ["bogu", "boɡu"],
    fud: ["moto", "moto"],
    kjg: ["siw", "siw"],
    kos: ["folfol sra", "folfol ʂa"],
    niu: ["lanu laukou", "lanu laukou"],
    peh: ["noɢoŋ", "noɢoŋ"],
    pzh: ["tululik", "tululik"],
    srh: ["sovdz", "sovdz"],
    swi: ["ȶhu1", "ȶhu˩˩"],
    wls: ["moto", "moto"],
    yap: ["giriin", "ɡiriːn"],
    ko_bus: ["초록", "tɕʰoɾok̚"],
    ja_sd: ["緑", "midoɾi"],
    en_ie: ["green", "ɡɹiːn"],
    es_co: ["verde", "ˈbeɾðe"],
    es_an: ["verde", "ˈbeɾðe"],
    shx: ["ka35 pʰɤ54 kʰun31", "ka˧˥ pʰɤ˥˦ kʰun˧˩"],
    agr: ["samɨkbau", "samɨkbau"],
    bjn: ["hijau", "hidʒau"],
    fr_class: ["vert", "vɛʁt"],
    myp: ["ʔahoasai", "ʔahoasai"],
    ko_kp: ["초록", "tɕʰoɾok̚"],
    ko_yb: ["초록", "tɕʰoɾok̚"],
    ko_hg: ["초록", "tɕʰorok̚"],
    ko_jl: ["초록", "tɕʰorok̚"],
    ja_kyo: ["緑", "midoɾi"],
    es_mx: ["verde", "ˈbeɾðe"],
    es_pe: ["verde", "ˈbeɾðe"],
    es_ar: ["verde", "ˈbeɾðe"],
    es_cl: ["verde", "ˈbeɾðe"],
    es_cu: ["verde", "ˈbeɾðe"],
    fr_be: ["vert", "vɛʁ"],
    fr_ch: ["vert", "vɛʁ"],
    es_gt: ["verde", "ˈbeɾðe"],
    es_ec: ["verde", "ˈbeɾðe"],
    es_uy: ["verde", "ˈbeɾðe"],
    fr_sn: ["vert", "vɛʁ"],
    fr_ci: ["vert", "vɛʁ"],
    fr_ht: ["vert", "vɛʁ"],
    fr_af: ["vert", "vɛʁ"],
    nzm: ["kanzaibe", "kanzaibe"],
    tsj: ["jangkhu", "dʑaŋkʰu"],
    acn: ["nʲau55", "nʲau˥˥"],
    yai: ["sabz", "sabz"],
    it_dan: ["verde", "ˈverde"],
    cng: ["ʐɑn ku", "ʐɑn ku"],
    vep: ["vihand", "ˈvihand"],
    es_sgl: ["verde", "ˈbeɾðe"],
    srm: ["guúun", "ɡúːun"],
    clk: ["tiŋ55kɹiɑ55", "tiŋ˥˥kɹiɑ˥˥"],
    prg: ["saligan", "saliɡan"],
    se: ["ruonas", "ˈruonas"],
    jiu: ["a33ny55", "a˧˧ny˥˥"],
    sog: ["zarγōnē", "zarɣoːneː"],
    trv: ["msama", "msama"],
    acu: ["samek", "samek"],
    zh_sc: ["绿", "nu˨˩"],
    wuu: ["绿", "loʔ˩˨"],
    zh_jh: ["绿", "luʔ˥˥"],
    zh_db: ["绿", "ly˥˩"],
    mnp: ["绿", "ly˦˨"],
    zh_tj: ["绿", "ly˥˧"],
    zh_wh: ["绿", "nəu˨˩˧"],
    zh_zz: ["绿", "ly˨˦"],
    sd: ["سائو", "saːio"],
    mwr: ["हरियो", "ɦərijo"],
    ar_iq: ["أخضر", "ˈʔaxðˤar"],
    ar_lev: ["أخضر", "ˈʔaxdˤar"],
    ar_gulf: ["أخضر", "ˈʔaxðˤar"],
    vi_s: ["xanh lá", "san˧ laː˧˥"],
    vi_c: ["xanh lá", "san˥ laː˨˦"],
    th_isan: ["เขียว", "kʰiaw˩˧"],
    za: {
      form: "𫇯",
      ipa:  "heːu˨˦",
      alt: [
        { form: "heu", script: "Latin (Sawcuengh)", source: "1957/1982 official orthography" },
        { form: "𮧃 / 𬰗 / 靘", script: "Sawndip (古壮字)", source: "attested variant glyphs beside the primary form 𫇯 — Sawndip was never standardised" },
      ],
    },
    ug: ["يېشىل", "jeˈʃil"],
    prs: ["سبز", "sabz"],
    mag: ["हरियर", "ɦərijər"],
    hne: ["हरियर", "ɦərijər"],
    bal: ["شونز", "ʃunz"],
    syl: ["কচুয়া", "xɔsua"],
    ctg: ["হোস্যুয়া", "hosːuwa"],
    bhb: ["हरो", "həɾo"],
    rkt: ["সবুজ", "sobudʒ"],
    yo: ["àwọ̀ ewé", "àwɔ̀ ewé"],
    ig: ["ndụndụ", "ndʊndʊ"],
    ny: ["wobiriwira", "wobiriwira"],
    tn: ["tala", "tala"],
    st: ["tala", "tala"],
    bm: ["binkɛnɛman", "binkɛnɛman"],
    wo: ["wert", "wɛrt"],
    sn: ["girini", "ɡirini"],
    ts: ["rihlaza", "riɬaza"],
    dyu: ["binkɛnɛman", "binkɛnɛman"],
    ar_sy: ["أخضر", "ˈʔaxdˤar"],
    ar_lb: ["أخضر", "ˈʔaxdˤar"],
    nl_be: ["groen", "ɣrun"],
    ja_hak: ["緑", "midoɾi"],
    ja_hir: ["緑", "midoɾi"],
    wuu_hz: ["绿", "loʔ˨"],
    wuu_jx: ["绿", "loʔ˥"],
    zh_lz: ["绿", "lu˩˧"],
    wuu_nb: ["绿", "loʔ˩˨"],
    wuu_sz: ["绿", "loʔ˧"],
    wuu_wz: ["绿", "lo˨˩˧"],
    nan_hai: ["绿", "liak˧"],
    ja_osa: ["緑", "midoɾi"],
    tk: ["ýaşyl", "jɑːˈʃɯl"],
    mn_cn: ["ᠨᠣᠭᠤᠭᠠᠨ", "nɔɡɔːŋ"],
    th_n: ["เขียว", "kʰiaw˩˧"],
    th_s: ["เขียว", "kʰiaw˩˧"],
    sat: ["ᱦᱟᱹᱨᱭᱟᱹᱲ", "hərijəɽ"],
    bgq: ["हरियो", "hərijo"],
    mey: ["أخضر", "ˈaxðˤar"],
    ti: ["ቀጠልያ", "qɐtʼɐlja"],
    shi: ["ⴰⵣⴳⵣⴰⵡ", "azɡzaw"],
    rif: ["ⴰⵣⴻⵢⵣⴰ", "azəjza"],
    tzm: ["ⴰⵣⴳⵣⴰⵡ", "azɡzaw"],
    ibb: ["awawa", "awawa"],
    ak: ["ahahammono", "ahahammono"],
    lg: ["kiragala", "tʃiraɡala"],
    ki: ["ngirini", "ŋɡirini"],
    ee: ["gbemumu", "ɡbemumu"],
    kr: ["kəli", "kəli"],
    sg: ["ngûngunzä", "ŋɡuŋɡunza"],
    mos: ["kẽega", "kẽːɡa"],
    vmw: ["ekori ya mathapa", "ekoɾi ja matʰapa"],
    rki: ["စိမ်း", "sɪ́ɴ"],
    efi: ["awawa", "awawa"],
    snk: ["xalle", "xalːe"],
    emk: ["binkɛndɛlama", "binkɛndɛlama"],
    tum: ["biriŵiri", "biɾiβiɾi"],
    kam: ["ngilini", "ŋɡilini"],
    yue_ts: ["绿", "lɵk̚˨˨"],
    czh: ["绿", "liu˩˩"],
    nyn: ["kibabi", "kibabi"],
    cgg: ["kinyaasi", "tʃiɲaːsi"],
    fon: ["amamǔ", "amamǔ"],
    war: ["berde", "ˈbɛrde"],
    pag: ["pasiseng", "paˈsisəŋ"],
    sas: ["ijo", "idʒo"],
    mui: ["ijo", "idʒo"],
    ii: ["ꀈꆧ", "a˥ɬo˨˩"],
    wbm: ["klai", "klai"],
    zza: ["kesk", "kɛsk"],
    sdh: ["سەوز", "sɛwz"],
    rom: ["zeleno", "zeˈleno"],
    mzn: ["سوز", "sævz"],
    gbm: ["हर्यूं", "hərjũː"],
    en_nz: ["green", "ɡɹiːn"],
    en_sg: ["green", "ɡɹiːn"],
    egl: ["vérd", "verd"],
    tpi: ["grinpela", "ɡrinpela"],
    srn: ["grun", "ɡrun"],
    sid: ["hanja", "handʒa"],
    thr: ["हरो", "ɦəro"],
    lmn: ["हरो", "həro"],
    aa: ["anxaxiní", "anɖaɖini"],
    shy: ["azizaw", "azizaw"],
    mnk: ["jambakere", "dʒambakere"],
    quc: ["rax", "raʃ"],
    quz: ["qʼumir", "qʼumir"],
    ja_aom: ["緑", "midoɾi"],
    ksw: ["လါဟ့", "lahe"],
    hni: ["niul", "ɲu˥˥"],
    lis: ["ni-chi", "ni˧˥tʃʰɿ˦˩"],
    khg: ["ལྗང་ཁུ", "ndʑuŋ˩˧kʰu˥˧"],
    mni: ["ꯑꯁꯡꯕ", "asaŋba"],
    bts: ["ratah", "ratah"],
    abs: ["ijo", "idʒo"],
    mas: ["nanyori", "naɲori"],
    ve: ["dala", "dala"],
    fan: ["kuna", "kuna"],
    ach: ["atworo", "atworo"],
    rmy: ["zeleno", "zeˈleno"],
    rhg: ["áil", "ail"],
    tcy: ["ಪಚ್ಚೆ", "pattʃe"],
    drs: ["haanja", "haːndʒa"],
    tig: ["ሰዐርሰዕሮ", "saʕarsaʕəro"],
    sco: ["green", "ɡriːn"],
    rgn: ["vérd", "veːɾd"],
    li: ["greun", "ɡrøːn"],
    av: ["гӏурччинаб", "ʕurtʃːinab"],
    tsg: ["gaddung", "ɡadduŋ"],
    ljp: ["hujau", "hudʒau"],
    unr: ["hariar", "harijar"],
    grt: ["tangsek", "taŋsek"],
    mnw: ["ဍာပ်ဍဴ", "ɗap ɗao"],
    mtq: ["xenh", "sɛɲ"],
    tyz: ["kheo", "kʰɛːw˧˧"],
    nut: ["kheo", "kʰɛːw˧˧"],
    ja_kg: ["緑", "midoɾi"],
    sm: ["lanumeamata", "lanumeamata"],
    tet: ["matak", "matak"],
    new: ["वाउँ", "wãũ"],
    nia: ["owugeʼe", "owuɡeʔe"],
    lhu: ["nɔ́", "nɔ́"],
    kac: ["tsit", "tsit˧˩"],
    pll: ["ɲər", "ɲər"],
    ahk: ["nyoe", "ɲø˧"],
    tji: ["luga", "lu˧˥ka˥˥"],
    sda: ["maido", "maido"],
    yua: ["yaʼax", "jaʔaʃ"],
    tzh: ["yax", "jaʃ"],
    mam: ["txaʼx", "tʃaʔʃ"],
    mixtec: ["kuii", "kʷiː"],
    quy: ["qumir", "qumiɾ"],
    bra: ["हरौ", "ɦəraʊ"],
    tly: ["kavu", "kavu"],
    hak_hl: ["青", "tsʰiaŋ˥˧"],
    ksb: ["manimani", "manimani"],
    bfa: ["loŋem", "loŋem"],
    loz: ["tala", "tala"],
    pcd: ["vert", "vɛʁ"],
    wa: ["vert", "vɛʁ"],
    szl: ["zielōny", "ʑɛˈlonɨ"],
    sgs: ["žalis", "ʒalʲɪs"],
    rue: ["зеленый", "zeˈlenɨj"],
    dar: ["шиниша", "ʃiniʃa"],
    xmf: ["წვანე", "tsʼvane"],
    swg: ["grea", "ɡreə̯"],
    hwc: ["green", "ɡɹiːn"],
    sah: ["күөх", "kyˈøx"],
    tyv: ["ногаан", "noɣaːn"],
    pis: ["grin", "ɡrin"],
    rup: ["veardi", "ˈve̯ardi"],
    udm: ["вож", "voʒ"],
    nch: ["xoxohuic", "ʃoˈʃowik"],
    nhw: ["xoxohuic", "ʃoˈʃowik"],
    nhe: ["xoxohuic", "ʃoˈʃowik"],
    tzo: ["yaxal", "jaʃal"],
    zap: ["naberde", "naberde"],
    mdr: ["mekurarraq", "mekurarːaʔ"],
    nxq: ["herq", "hɚ˨˩"],
    bdq: ["jơk", "ɟəːk"],
    bzj: ["green", "ɡriːn"],
    ty: ["matie", "matie"],
    dz: ["ཧོནམ", "høːm"],
    frp: ["vèrd", "vɛr"],
    kfx: ["हौरा", "hɔraː"],
    usp: ["rax", "raʃ"],
    yrl: ["suikiri", "suikiɾi"],
    sjo: ["ᠨᡳᠣᠸᠠᠩᡤᡳᠶᠠᠨ", "nyŋɲiɑn"],
    ruq: ["veardi", "ˈve̯ardi"],
    tru: ["ܝܪܩܐ", "jaroqo"],
    poh: ["rax", "raʃ"],
    mic: ["stoqonamuʼk", "əstoxonamuːɡ"],
    apw: ["dotłʼizh", "dotɬʼiʒ"],
    smj: ["ruodnat", "ruɔdnɑt"],
    sip: ["ལྗང་ཀུ", "dʑaŋku"],
    ers: ["zizɑ", "zi˥˥zɑ˥˥"],
    xal: ["ноһан", "noˈɣan"],
    nhx: ["xoxoctiꞌ", "ʃoʃoktiʔ"],
    mxv: ["kuii", "kʷiː"],
    xkz: ["’ngunti", "ŋunti"],
    stq: ["gräin", "ɡrɛɪ̯n"],
    frr: ["green", "ɡreːn"],
    abq: ["удзышва", "udzəʃʷa"],
    tcs: ["grin", "ɡrin"],
    bbo: ["saajuu", "saːɟuː"],
    rar: ["matie", "matie"],
    jvn: ["ijo", "idʒo"],
    agx: ["гъазеф", "ʁazef"],
    arp: ["cenéeteeyóó", "tʃenéːteːjóː"],
    bzd: ["tsipátsipà", "tsipátsipa"],
    pwn: ["liljuas", "ɭiʎuas"],
    tok: ["laso", "laso"],
    vro: ["rohilinõ", "rohilinɤ"],
    toj: ["yaʼax", "jaʔaʃ"],
    agu: ["txaʼx", "tʃaʔʃ"],
    pbb: ["çẽy", "çẽj"],
    esu: ["cungagliq", "tʃuŋaɣɬiq"],
    en_ck: ["green", "ɡɹiːn"],
    ppl: ["shushuwik", "ʃuʃuwik"],
    atj: ["ocawackwaw", "oʃawaʃkwaw"],
    tdh: ["गिगिम", "ɡiɡim"],
    zts: ["nga", "ŋa"],
    mix: ["kuii", "kʷiji"],
    rmf: ["grönt", "ɡrønt"],
    mus: ["lane", "lani"],
    chf: ["yäx", "jɨʃ"],
    djk: ["guun", "ɡuːn"],
    crn: ["jamuámua", "haˈmwamwa"],
    crx: ["dultlʼuz", "dutɬʼuz"],
    cni: ["kenashi", "kenaʃi"],
    ame: ["aspan", "aspan"],
    fax: ["verdi", "ˈbeɾdi"],
    kjh: ["ноған", "noɣan"],
    nog: ["ясыл", "jasɯl"],
    moh: ["óhonteʼ", "óhũteʔ"],
    chy: ["hoxoʼȯhtsévo", "hoxoʔohtsévo"],
    ium: ["maeng", "mæŋ˧"],
    kpy: ["нывʼтэлгыяӄэн", "nəwtelɣəjaqen"],
    aqc: ["оӏловттут", "oˤlowtːut"],
    ddo: ["цӏицӏира", "tsʼitsʼira"],
    tao: ["mogaraw", "moɡaraw"],
    tar: ["siyóname", "siˈjoname"],
    wba: ["hebuɾa", "hebuɾa"],
    tsu: ["enghova", "eŋxova"],
    bnn: ["masanglav", "masaŋlav"],
    wbp: ["yukuri-yukuri", "jukuɻijukuɻi"],
    aer: ["atherrke", "at̪erke"],
    otq: ["kꞌangi", "kʼaŋi"],
    vi_han: ["青", "tʰaɲ˧˧"],
    vi_nom: ["青蘿", "saɲ˧ laː˧˥"],
    nan_ph: ["青色", "tsʰĩ˧˧ siak˥"],
    fr_qc: ["vert", "vɛʁ"],
    skr: ["ساوا", "saːʋaː"],
    en_au: ["green", "ɡɹiːn"],
    en_sco: ["green", "ɡɹiːn"],
    en_aave: ["green", "ɡɹiːn"],
    en_yk: ["green", "ɡɹiːn"],
    en_in: ["green", "ɡriːn"],
    mai: ["हरियर", "ɦərijər"],
    nag: ["hara", "haɾa"],
    kru: ["हरियर", "haɾijaɾ"],
    en_south: ["green", "ɡɹiːn"],
    pcm: ["green", "ɡrin"],
    awa: ["हरिअर", "həriər"],
    de_at: ["grün", "ɡryːn"],
    en_app: ["green", "ɡɹiːn"],
    to: ["lanu mata", "lanu mata"],
    byn: ["ቍጣን", "kʷʼətʼan"],
    dng: ["лю", "liou˨˦"],
    saq: ["nanyori", "naɲori"],
    shn: ["ၶဵဝ်", "kʰew˨˦"],
    dnj: ["gblȅeyi̋dhē", "ɡblȅːji̋ɗē"],
    tkl: ["lanu meamata", "lanu meamata"],
    ckt: ["нывытэчгытрыӄэн", "nəwətetʃɣətrəqen"],
    dds: ["wɛru", "wɛru"],
    vo: ["grünik", "ɡryˈnik"],
    smn: ["ruánáá", "ˈruanaː"],
    kfa: ["ಪಚ್ಚೆ", "patʃtʃe"],
    en_wls: ["green", "ɡɹiːn"],
    es_sv: ["verde", "ˈbeɾðe"],
    es_do: ["verde", "ˈbeɾðe"],
    pt_mz: ["verde", "ˈveɾde"],
    fr_cm: ["vert", "vɛʁ"],
    en_wc: ["green", "ɡɹiːn"],
    en_ng: ["green", "ɡɹiːn"],
    ar_jo: ["أخضر", "ˈʔaxdˤar"],
    ar_ye: ["أخضر", "ˈʔaxdˤar"],
    fra_jer: ["vèrt", "vɛr"],
    pmy: ["hijou", "hidʒou"],
    uby: ["ʁˤaqʼa", "ʁˤaqʼa"],
    gsw_als: ["grìen", "ɡriən"],
    ar_ps: ["أخضر", "ˈʔaxdˤar"],
    acw: ["أخضر", "ˈʔaxdˤar"],
    es_ve: ["verde", "ˈbeɾðe"],
    ca_va: ["verd", "veɾt"],
    pt_cv: ["verde", "ˈveɾdɨ"],
    pt_mo: ["verde", "ˈveɾdɨ"],
    en_brum: ["green", "ɡɹiːn"],
    en_ph: ["green", "ɡɹin"],
    kgp: ["tánh", "təɲ"],
    nio: ["нөтәрәку", "nʷatərəku"],
    gqu: ["ten55", "ten˥˥"],
    bwi: ["hípole", "hípole"],
    blc: ["qʷli", "qʷli"],
    pt_gw: ["verdi", "ˈveɾdi"],
    en_us: ["green", "ɡɹin"],
    en_ke: ["green", "ɡɹiːn"],
    en_ng2: ["green", "ɡɹiːn"],
    en_za: ["green", "ɡɹiːn"],
    en_scouse: ["green", "ɡɹiːn"],
    es_py: ["verde", "ˈbeɾðe"],
    es_cr: ["verde", "ˈbeɾðe"],
    de_ch: ["grün", "ɡryːn"],
    de_lu: ["grün", "ɡʁyːn"],
    zh_tw: ["綠", "ly˥˩"],
    zh_nj: ["绿", "luʔ˥"],
    zh_xa: ["绿", "liɤu˨˩"],
    kwk: ["ła̱nx̱a", "ɬənχa"],
    kmc: ["su35", "su˧˥"],
    blr: ["khiu33", "kʰiu˧˧"],
    es_bo: ["verde", "ˈbeɾðe"],
    es_hn: ["verde", "ˈbeɾðe"],
    es_pa: ["verde", "ˈbeɾðe"],
    en_ca: ["green", "ɡɹiːn"],
    en_manc: ["green", "ɡɹiːn"],
    en_my: ["green", "ɡɹiːn"],
    vot: ["rohoin", "ˈrohoin"],
    sce: ["noghon", "noɣon"],
    zgh: ["ⴰⵣⴳⵣⴰ", "azəɡza"],
    bin: ["ebeebe", "ebeebe"],
    zh_cd: ["绿", "nu˨˩"],
    zh_km: ["绿", "lu˧˩"],
    zh_hf: ["绿", "luəʔ˦"],
    sma: ["kroenes", "kruenes"],
    rut: ["шилды", "ʃildɨ"],
    mjg: ["nughuun", "nuʁuːn"],
    vls: ["groene", "ˈhrunə"],
    wym: ["grin", "ɡrin"],
    kxm: ["ខៀវ", "kʰiːw"],
    pyu: ["miraʼat", "miraʔat"],
    tvl: ["lanu lau niu", "lanu lau niu"],
    ale: ["чидг̆ааюлих", "tʃiðɣaːjulix"],
    pnt: ["πράσινον", "ˈprasinon"],
    aln: ["jeshil", "jeˈʃil"],
    kfy: ["हरियो", "ɦərijo"],
    gsw_w: ["grie", "ɡriə"],
    lij_t: ["verde", "ˈverde"],
    sva: ["ჲჷრჟი", "jərʒi"],
    bdk: ["йашил", "jaʃil"],
    udi: ["йаьшил", "jæʃil"],
    zh_cq: ["绿", "lu˨˩"],
    zh_kf: ["绿", "ly˨˦"],
    kry: ["çʼukʼni", "tʃʼukʼni"],
    roo: ["kokovara", "kokoβaɾa"],
    mkz: ["lumuru", "lumuru"],
    slr: ["yaşil", "jɑʃil"],
    sel: ["патый", "patɨj"],
    sms: ["ruõnâs", "ruənɐs"],
    sjd: ["руэнн", "ruenː"],
    jio: ["laːk", "laːk˩"],
    bsk: ["ṣiqám", "ʂiˈqam"],
    ln: ["lángi la mpɔndú", "láŋɡi la mpɔndú"],
    kg: ["langi ya matiti", "laŋɡi ja matiti"],
    ff: ["haakoojo", "haːkoːdʒo"],
    rcf: ["vèr", "vɛr"],
    bqi: ["سوز", "sawz"],
    lzz: ["ხანჭელი", "xantʃʼeli"],
    tab: ["чруб", "tʃrub"],
    ngu: ["xoxojki", "ʃoˈʃohki"],
    xsr: ["ལྗང་སྨུ", "dʑaŋmu"],
    ssw: ["luhlata", "luɬaːta"],
    maz: ["cʼanga", "kʼaŋɡa"],
    mvf: ["noghoon", "noɢoon"],
    lwl: ["snga", "sᵊŋa"],
    hot: ["saŋgek", "saŋɡɛk"],
    dsh: ["ɠileeb", "ɠileːb"],
    rap: ["rito mata", "ɾito mata"],
    trm: ["palašó", "palaʃo"],
    hts: ["nxawejjene", "ᵑǁawetʃʼene"],
    tkr: ["чыван", "tʃɨvan"],
    rtm: ["čarava", "tʃarava"],
    cho: ["okchamali", "oktʃamali"],
    emp: ["pãwãrã", "pãwãˈɾã"],
    chk: ["araw", "araw"],
    cuk: ["arrad", "arːad"],
    es_ni: ["verde", "ˈbeɾðe"],
    es_pr: ["verde", "ˈbeɾðe"],
    fr_lu: ["vert", "vɛʁ"],
    en_jam: ["green", "ɡɹiːn"],
    pt_ao: ["verde", "ˈveɾde"],
    afb: ["أخضر", "ˈʔaxðˤar"],
    abv: ["أخضر", "ˈʔaxdˤar"],
    hns: ["hariar", "ɦəriaːr"],
    woe: ["gaaraweraw", "ɡaːɻaweɻaw"],
    win: ["coo", "tʃoː"],
    cro: ["shúa", "ʃúa"],
    atb: ["nyuì", "ŋjui˥˩"],
    pmt: ["matie", "matie"],
    khw: ["اوݯ", "ɔʈʂ"],
    adx: ["ལྗང་ཁུ", "dʑaŋkʰə"],
    duu: ["pɯɕiŋ", "pɯɕiŋ"],
    njo: ["tajem", "tadʒəm"],
    ybe: ["jahsïl", "jɑhˈsɯl"],
    yuy: ["noʁoon", "noʁoːn"],
    bor: ["kaworureu", "kawoɾuɾew"],
    xav: ["ĩʼuzé", "ĩʔuˈzɛ"],
    bfq: ["pachche", "patʃːe"],
    hsn_hy: ["绿", "lu˩˩˨"],
    czh_wy: ["绿", "lɑ˥˩"],
    cjy_lv: ["绿", "luəʔ˨˧"],
    ykg: ["хомоньэй", "xomoˈnʲej"],
    nuf: ["ȵɯ35ȵɯ31", "ȵɯ˧˥ȵɯ˧˩"],
    lbj: ["སྔོན་པོ", "ŋonpo"],
    pau: ["mellemau", "məlːəˈmaw"],
    tlh: ["SuD", "ʂuɖ"],
    en_geordie: ["green", "ɡɹiːn"],
    en_est: ["green", "ɡɹiːn"],
    bah: ["green", "ɡɹiːn"],
    aae: ["i virdhë", "i viɾðə"],
    wae: ["grüe", "ɡryə̯"],
    yrk: ["илебей", "ilʲebʲej"],
    niv: ["ньлайсвала", "ɲlajsvala"],
    yux: ["дьэльооноҥоой", "dʒeʎoːnoŋoːj"],
    eve: ["чӯлбаня̄", "tʃuːlbaɲaː"],
    iu: ["ᐆᔭᐅᔭᖅ", "uːjaujaq"],
    pmi: ["ȵĩ55mə53", "ɲĩ˥˥mə˥˧"],
    twm: ["dʑᴀŋ13ku53", "dʑᴀŋ˩˧ku˥˧"],
    kxc: ["ilaawa", "ilaːwa"],
    cay: ["onráhda̱ʼę:ʼ", "onráhdḁʔɛ̃ːʔ"],
    xed: ["kùzún-kùzún", "kùzún kùzún"],
    tiv: ["kwel", "kʷel"],
    izz: ["oyingo-oyingo", "ojiŋɡo ojiŋɡo"],
    urh: ["ọgiọgiọ", "ɔɡiɔɡiɔ"],
    rn: ["akatsi gatoto", "akatsi ɡatoto"],
    nzi: ["asuomenle", "asuomenle"],
    zne: ["nvutanvuta", "nvutanvuta"],
    bom: ["gwim-gwim", "ɡwimɡwim"],
    dak: ["tȟó", "txó"],
    nmn: ["ᶢǀa̤ʕi", "ᶢǀa̤ʕi"],
    yan: ["sangni", "saŋni"],
    aoz: ["mateʼ", "mateʔ"],
    ses: ["firzi", "firzi"],
    tll: ["eleselese", "eleselese"],
    adi: ["yaying", "jajiŋ"],
    nmf: ["khamateka", "kʰamateka"],
    gej: ["amamu", "amamu"],
    bem: ["katapa", "katapa"],
    pjt: ["ukiṟi-ukiṟi", "ukiɻiukiɻi"],
    mch: ["sheene", "ʃeːne"],
    jup: ["pɔ̃pɔ̃h", "pɔ̃pɔ̃h"],
    tue: ["sɨ̃bẽ", "sɨ̃ˈbẽ"],
    brh: ["خرن", "xarːun"],
    kha: ["jyrngam", "dʒərŋam"],
    moc: ["radala", "radala"],
    tob: ["dadala", "dadala"],
    plg: ["dadala", "dadala"],
    cag: ["nipewajʃi", "nipewajʃi"],
    tsi: ["mełiitk", "məɬiːtk"],
    bej: ["sootaay", "soːtaːj"],
    her: ["tarazu", "tarazu"],
    sad: ["jaanga", "ɟaːŋɡa"],
    shp: ["yãkõ", "jãkõ"],
    mpt: ["itanasit", "itanasit"],
    maw: ["bɛŋkoom", "bɛŋkoːm"],
    zh_jn: ["绿", "ly˨˩"],
    nan_xm: ["绿", "lik̚˦"],
    yue_dg: ["绿", "lok˧"],
    yue_nn: ["绿", "lʊk˨"],
    yue_zs: ["綠", "lʊk˧"],
    wuu_jh: ["绿", "loʔ˨˩˨"],
    ami: ["kangdaway", "kaŋdawaj"],
    tay: ["mtasiq", "mtasiq"],
    ssf: ["madishlum", "madiʃlum"],
    ckv: ["puli", "puli"],
    dru: ["salesese", "saləsəsə"],
    szy: ["langdaway", "laŋdawaj"],
    dtp_kzj: ["otomou", "oˈtomou"],
    hif: ["hariyar", "hərijər"],
    alq: ["ozhàwashkwà", "ɔʒaːwaʃkwaː"],
    pot: ["skebgya", "skʌbkja"],
    osa: ["mąhį́ htóho", "mãhĩ́ htóho"],
    pao: ["puhi", "puhi"],
    djr: ["menydjuṉ", "meɲɟuɳ"],
    ktz: ["ǀauhn", "ǀauhn"],
    fvr: ["kirro", "kirːo"],
    mpj: ["yukuri-yukuri", "jukuɻijukuɻi"],
    mcf: ["umu", "uˈmu"],
    bru: ["ramoong", "rəmɔːŋ"],
    ani: ["хочи", "χotʃi"],
    syc: ["ܝܘܪܩܐ", "jawrqaː"],
    chb: ["chysquyco", "tʃɨskɨko"],
    mga: ["úaine", "ˈuːənʲe"],
    en_em: ["greene", "ɡriːn"],
    de_lut: ["grün", "ɡryːn"],
    pi_edu: ["harita", "harita"],
    pi: ["हरित", "harita"],
    sa: ["हरितः", "haritaɦ"],
    sa_edu: ["हरितः", "haritaɦ"],
    osp: ["verde", "ˈβeɾde"],
    ja_heian: ["緑", "midoɾi"],
    ja_chu: ["緑", "midoɾi"],
    ja_edo: ["緑", "midoɾi"],
    ja_kanbun: ["緑", "midoɾi"],
    ptrk: ["*jāĺïl", "jaːʎɯl"],
    pmng: ["*noguɣan", "noɡuɣan"],
    p_ine: ["*ǵʰelh₃-", "ǵʰelh₃"],
    ptai: ["*xiəw", "xiəw"],
    pmay: ["*raʔx", "raʔʃ"],
    onw: ["ⲇⲉⲥⲥ", "desː"],
    psem: ["*waraḳ-", "waraq"],
    pura: ["*wiša", "wiʃa"],
    p_dra: ["*pac-", "patʃ"],
    och: ["綠", "*pə.rok"],
    zh_tang: ["綠", "luawk"],
    zh_wenyan_edu: ["綠", "lʊk˨"],
    xct: ["ལྗང་ཁུ", "ldʑaŋkʰu"],
    xct_litpr: ["ལྗང་ཁུ", "tɕəŋku"],
    orv: ["зеленъ", "zelenŭ"],
    arc: ["ܝܘܪܩܐ", "jaroːqaː"],
    xqa: ["yašıl", "jaʃɯl"],
    tpn: ["oby", "oˈβɨ"],
    sga: ["glas", "ɡlas"],
    gan_yc: ["绿", "luʔ˦"],
    gan_ja: ["绿", "ly˧˧˦"],
    gan_fz: ["绿", "tiuʔ˨"],
    cjy_xz: ["绿", "luəʔ˦˧"],
    kdt: ["khew", "kʰew"],
    srb: ["gən", "ɡən"],
    mra: ["bɨn liŋ", "bɨn liŋ"],
    rbb: ["niɨ", "niɨ"],
    crt: ["watso", "watso"],
    one: ["awʌ:lá:", "awʌ̃ːláː"],
    ote: ["kʼantsʼi", "kʼantsʼi"],
    aoc: ["rorape", "ɾoɾape"],
    yue_gz: ["绿", "lʊk̚˨˨"],
    ar_sa: ["أخضر", "ʔaˈxaðˤar"],
    ngl: ["ntikwa", "ntikwa"],
    cia: ["moijo", "moidʒo"],
    nlc: ["sugulamla", "suɡulamla"],
    qxs: ["χueχue", "χueχue"],
    piu: ["kuriinwana", "kuɻiːnwana"],
    kgg: ["hərgun", "hərɡun"],
    zh_song: ["綠", "liu"],
    pmh: ["हरिय", "harija"],
    xag: ["dai", "dai"],
    xng: ["ᠨ᠋ᠣᠬᠤᠬᠠᠨ", "noqoan"],
    otk: ["𐰖𐰽𐰞", "jaʃɯl"],
    txg: ["𗺭", "dʑjow˧"],
    juc: ["burha boco", "burxa botʃo"],
    qwc: ["qumir", "qomir"],
    ohu: ["zöld", "zøld"],
    pal: ["𐭮𐭯𐭦", "sabz"],
    cop: ["ⲟⲩⲟⲧⲟⲩⲉⲧ", "uotuet"],
    din: ["tɔ̈c", "tɔtʃ"],
    kwa: ["mɨ̃̂", "mɨ̃̂"],
    kjj: ["сыб", "sɨb"],
    nus: ["tɔc", "tɔtʃ"],
    rmt: ["axḍar", "axdˤar"],
    fkv: ["vihree", "ˈʋihreː"]
  }
};
