/**
 * Milk is the map of a word that is missing. For most basic things — mother, water, three — Indo-European
 * reconstructs one form that the whole family inherited. For milk it does not. Latin has lac, Greek
 * gála, Germanic *meluks (English milk, German Milch), Slavic *melko, Sanskrit kṣīra. Latin and Greek
 * at least look at each other — both point to something like *glakt-, which is such an un-Indo-European
 * shape that it is usually read as borrowed from whoever was around the Mediterranean first. Germanic
 * took a different route entirely and named the substance from the action, *h₂melǵ- 'to milk', which is
 * why English milks a cow and drinks milk with the same word.
 *
 * The Greek form left the biggest trace. Ancient Greek called the band of light across the night sky
 * galaxíās kúklos, 'the milky circle' — so every galaxy in the universe is named after milk, and the
 * Latin calque Via Lactea is the same thought in the other word.
 */
WORDS.milk = {
  emoji: "🥛",
  label: {
    en: "Milk", ja: "牛乳", ko: "우유", zh: "牛奶", yue: "牛奶", vi: "Sữa", th: "นม", id: "Susu",
    hi: "दूध", de: "Milch", fr: "Lait", it: "Latte", es: "Leche", es_eu: "Leche", es_mx: "Leche",
    pt: "Leite", pt_eu: "Leite", pt_br: "Leite", ru: "Молоко", uk: "Молоко", ar: "حليب",
    he: "חלב", sw: "Maziwa",
  },
  definition: {
    en: "Milk — the drink from a cow or a mother. Indo-European has no single inherited word for it; the Greek one, gála, is why galaxies are named after it.",
    ja: "牛乳 — 牛や母から出る飲み物。印欧語族に共通語はなく、ギリシア語 gála が galaxy（銀河）の語源になった。",
    ko: "우유 — 소나 어머니에게서 나오는 음료. 인도유럽어에는 공통 단어가 없고, 그리스어 gála가 galaxy(은하)의 어원이다.",
    zh: "牛奶 — 出自母牛或母亲的饮品。印欧语系没有共同的词，而希腊语 gála 正是 galaxy（银河）的词源。",
    yue: "牛奶 — 出自乳牛或者母親嘅飲品。印歐語系冇共同嘅詞，而希臘文 gála 正正就係 galaxy（銀河）嘅詞源。",
    vi: "Sữa — thức uống từ bò hoặc từ mẹ. Ngữ hệ Ấn-Âu không có một từ chung; từ Hy Lạp gála là gốc của galaxy (thiên hà).",
    th: "นม — เครื่องดื่มจากวัวหรือจากแม่ ตระกูลอินโด-ยูโรเปียนไม่มีคำร่วมคำเดียว และคำกรีก gála คือที่มาของคำว่า galaxy.",
    id: "Susu — minuman dari sapi atau dari ibu. Rumpun Indo-Eropa tidak punya satu kata warisan; kata Yunani gála-lah asal kata galaxy.",
    hi: "दूध — गाय या माँ से मिलने वाला पेय। भारोपीय परिवार में इसका एक साझा शब्द नहीं है; यूनानी gála से ही अंग्रेज़ी galaxy बना।",
    de: "Milch — das Getränk von der Kuh oder von der Mutter. Das Indogermanische hat dafür kein gemeinsames Erbwort; das griechische gála steckt in Galaxie.",
    fr: "Lait — la boisson de la vache ou de la mère. L'indo-européen n'a pas de mot hérité unique ; le grec gála a donné galaxie.",
    it: "Latte — la bevanda della mucca o della madre. L'indoeuropeo non ha un'unica parola ereditata; dal greco gála viene galassia.",
    es: "Leche — la bebida de la vaca o de la madre. El indoeuropeo no tiene una única palabra heredada; del griego gála viene galaxia.",
    es_eu: "Leche — la bebida de la vaca o de la madre. El indoeuropeo no tiene una única palabra heredada; del griego gála viene galaxia.",
    es_mx: "Leche — la bebida de la vaca o de la madre. El indoeuropeo no tiene una única palabra heredada; del griego gála viene galaxia.",
    pt: "Leite — a bebida da vaca ou da mãe. O indo-europeu não tem uma única palavra herdada; do grego gála vem galáxia.",
    pt_eu: "Leite — a bebida da vaca ou da mãe. O indo-europeu não tem uma única palavra herdada; do grego gála vem galáxia.",
    pt_br: "Leite — a bebida da vaca ou da mãe. O indo-europeu não tem uma única palavra herdada; do grego gála vem galáxia.",
    ru: "Молоко — напиток от коровы или от матери. В индоевропейском нет единого унаследованного слова; от греческого gála происходит «галактика».",
    uk: "Молоко — напій від корови або від матері. В індоєвропейській немає єдиного успадкованого слова; від грецького gála походить «галактика».",
    ar: "حليب — شراب البقرة أو الأم. لا تملك الهندية الأوروبية كلمة موروثة واحدة له؛ ومن اليونانية gála جاءت كلمة المجرّة galaxy.",
    he: "חלב — המשקה מן הפרה או מן האם. להודו-אירופית אין מילה מורשת אחת; מן היוונית gála באה המילה גלקסיה.",
    sw: "Maziwa — kinywaji kitokacho kwa ng'ombe au kwa mama. Kihindi-Ulaya hakina neno moja la urithi; neno la Kigiriki gála ndilo asili ya galaxy.",
  },
  data: {
    // --- UI languages -------------------------------------------------
    en: ["milk", "mɪlk"],
    ja: ["牛乳", "ɡʲɯːɲɯː"],
    ko: ["우유", "uju"],
    zh: ["牛奶", "njoʊ˧˥ naɪ˨˩˦"],
    yue: ["牛奶", "ŋɐu˨˩ naːi˩˧"],
    vi: ["sữa", "sɨə˧ˀ˥"],
    th: ["นม", "nom˧"],
    id: ["susu", "susu"],
    hi: ["दूध", "d̪uːd̪ʱ"],
    de: ["Milch", "mɪlç"],
    fr: ["lait", "lɛ"],
    it: ["latte", "ˈlatte"],
    es: ["leche", "ˈletʃe"],
    es_mx: ["leche", "ˈletʃe"],
    pt: ["leite", "ˈlejtɨ"],
    pt_br: ["leite", "ˈlejtʃi"],
    ru: ["молоко", "məlɐˈko"],
    uk: ["молоко", "moloˈko"],
    ar: ["حليب", "ħaliːb"],
    he: ["חלב", "ẖaˈlav"],
    sw: ["maziwa", "maˈziwa"],

    // --- *glakt-: the shape that does not look Indo-European ----------
    la: ["lac", "lak"],
    el_grc: ["γάλα", "ɡála"],
    el_kath: ["γάλα", "ˈɣala"],
    el: ["γάλα", "ˈɣala"],
    fro: ["lait", "lajt"],
    osp: ["leche", "ˈletʃe"],
    it_dan: ["latte", "ˈlatte"],

    // --- ...and Germanic, which named it from the verb ----------------
    got: ["𐌼𐌹𐌻𐌿𐌺𐍃", "miluks"],
    ang: ["meoluc", "ˈmeoluk"],
    enm: ["milk", "milk"],
    en_em: ["milk", "mɪlk"],
    ofs: ["melok", "ˈmelok"],
    osx: ["miluk", "ˈmiluk"],
    goh: ["miluh", "ˈmilux"],
    gmh: ["milch", "milç"],
    non: ["mjólk", "mjoːlk"],

    // --- Slavic, Indo-Iranian, and the ones that did something else ---
    cu: ["млѣко", "mlɛːko"],
    sa: ["क्षीर", "kʂiːrɐ"],
    h_vedic: ["क्षीर", "kʂiːrɐ"],
    pi: ["खीर", "kʰiːra"],
    pi_edu: ["khīra", "kʰiːra"],
    fa: ["شیر", "ʃiːɾ"],
    pal: ["𐭱𐭩𐭫", "ʃir"],
    hy_grab: ["կաթն", "katʰn"],
    hy: ["կաթ", "kɑtʰ"],
    sga: ["as", "as"],
    cy: ["llaeth", "ɬaiθ"],
    ga: ["bainne", "ˈbˠanʲə"],
    lt: ["pienas", "ˈpʲiɛnɐs"],
    lv: ["piens", "piens"],

    // --- Ancient Near East ---------------------------------------------
    akk: ["šizbu", "ʃizbu"],
    hbo: ["חלב", "ħaːˈlaːv"],
    he_mis: ["חלב", "ħaˈlav"],
    arc: ["ܚܠܒܐ", "ħalbaː"],
    ar_qur: ["لبن", "laban"],
    gez: ["ሐሊብ", "ħaliːb"],
    cop: ["ⲉⲣⲱⲧⲉ", "eroːte"],

    // --- Modern Europe --------------------------------------------------
    nl: ["melk", "mɛlk"],
    af: ["melk", "mɛlk"],
    sv: ["mjölk", "mjœlk"],
    no: ["melk", "mɛlk"],
    nn: ["mjølk", "mjœlk"],
    da: ["mælk", "mɛlˀɡ"],
    is: ["mjólk", "mjoulk"],
    fo: ["mjólk", "mjɔulk"],
    pl: ["mleko", "ˈmlɛkɔ"],
    cs: ["mléko", "ˈmlɛːko"],
    sk: ["mlieko", "ˈmlieko"],
    sl: ["mleko", "mleːko"],
    hr: ["mlijeko", "mlijeko"],
    sr: ["млеко", "mleko"],
    bs: ["mlijeko", "mlijeko"],
    bg: ["мляко", "ˈmlʲako"],
    mk: ["млеко", "ˈmlɛko"],
    be: ["малако", "malaˈko"],
    ro: ["lapte", "ˈlapte"],
    ca: ["llet", "ʎet"],
    gl: ["leite", "ˈlejte"],
    oc: ["lach", "lats"],
    sq: ["qumësht", "ˈcuməʃt"],
    hu: ["tej", "tɛj"],
    fi: ["maito", "ˈmaito"],
    et: ["piim", "piːm"],
    eu: ["esne", "esne"],
    ka: ["რძე", "rdze"],

    // --- Asia, Africa, Pacific -------------------------------------------
    tg: ["шир", "ʃir"],
    ps: ["شیدې", "ʃiːde"],
    ur: ["دودھ", "d̪uːd̪ʱ"],
    bn: ["দুধ", "d̪ud̪ʱ"],
    mr: ["दूध", "d̪uːd̪ʱ"],
    gu: ["દૂધ", "d̪uːd̪ʱ"],
    pa: ["ਦੁੱਧ", "d̪ʊd̪ʱː"],
    ne: ["दूध", "d̪ud̪ʱ"],
    si: ["කිරි", "kiri"],
    ta: ["பால்", "paːl"],
    te: ["పాలు", "paːlu"],
    ml: ["പാൽ", "paːl"],
    kn: ["ಹಾಲು", "haːlu"],
    my: ["နို့", "nòʊʔ"],
    km: ["ទឹកដោះគោ", "tɨk ɗɑh koː"],
    lo: ["ນົມ", "nom"],
    tr: ["süt", "syt"],
    az: ["süd", "syd"],
    kk: ["сүт", "syt"],
    ky: ["сүт", "syt"],
    uz: ["sut", "sut"],
    tt: ["сөт", "søt"],
    ug: ["سۈت", "syt"],
    mn: ["сүү", "syː"],
    bo: ["འོ་མ", "oma˥˥"],
    ms: ["susu", "susu"],
    tl: ["gatas", "ˈɡatas"],
    ceb: ["gatas", "ˈɡatas"],
    haw: ["waiū", "wɐiˈʔuː"],
    mi: ["miraka", "miɾaka"],
    ha: ["madara", "madara"],
    yo: ["wàrà", "wara"],
    am: ["ወተት", "wɐtɐt"],
    so: ["caano", "ʕaːno"],
    zu: ["ubisi", "uˈbisi"],
    xh: ["ubisi", "uˈbisi"],
    mg: ["ronono", "runun"],

    // --- English, everywhere it went -----------------------------------
    en_us: ["milk", "mɪlk"],
    en_ca: ["milk", "mɪlk"],
    en_au: ["milk", "mɪlk"],
    en_nz: ["milk", "məlk"],
    en_za: ["milk", "mɪlk"],
    en_in: ["milk", "mɪlk"],
    en_sg: ["milk", "mɪlk"],
    en_ph: ["milk", "mɪlk"],
    en_my: ["milk", "mɪlk"],
    en_ke: ["milk", "mɪlk"],
    en_ng: ["milk", "mɪlk"],
    en_ng2: ["milk", "mɪlk"],
    en_wls: ["milk", "mɪlk"],
    en_ie: ["milk", "mɪlk"],
    en_sco: ["milk", "mɪlk"],
    en_jam: ["milk", "mɪlk"],
    en_aave: ["milk", "mɪlk"],
    en_south: ["milk", "mɪlk"],
    en_app: ["milk", "mɪlk"],
    en_yk: ["milk", "mɪlk"],
    en_geordie: ["milk", "mɪlk"],
    en_brum: ["milk", "mɪlk"],
    en_manc: ["milk", "mɪlk"],
    en_wc: ["milk", "mɪlk"],
    en_scouse: ["milk", "mɪlk"],
    en_ck: ["milk", "mɪwk"],
    en_est: ["milk", "mɪwk"],
    sco: ["milk", "mɪlk"],

    // --- More Germanic — still the verb 'to milk' -----------------------
    de_at: ["Milch", "mɪlç"],
    de_ch: ["Milch", "mɪlç"],
    de_lu: ["Milch", "mɪlç"],
    de_lut: ["Milch", "mɪlç"],
    gsw: ["Milch", "milx"],
    pdc: ["Millich", "ˈmɪlɪç"],
    lb: ["Mëllech", "ˈmələç"],
    nds: ["Melk", "mɛlk"],
    nl_be: ["melk", "mɛlk"],
    vls: ["melk", "mɛlk"],
    li: ["melk", "mɛlk"],
    fy: ["molke", "ˈmolkə"],
    yi: ["מילך", "milx"],

    // --- Romance — lac, and what the dialects did to it ------------------
    es_cr: ["leche", "ˈletʃe"],
    es_hn: ["leche", "ˈletʃe"],
    es_ni: ["leche", "ˈletʃe"],
    es_sv: ["leche", "ˈletʃe"],
    es_bo: ["leche", "ˈletʃe"],
    es_py: ["leche", "ˈletʃe"],
    es_pa: ["leche", "ˈletʃe"],
    es_pr: ["leche", "ˈletʃe"],
    es_do: ["leche", "ˈletʃe"],
    es_gt: ["leche", "ˈletʃe"],
    es_ec: ["leche", "ˈletʃe"],
    es_uy: ["leche", "ˈletʃe"],
    es_ve: ["leche", "ˈletʃe"],
    es_co: ["leche", "ˈletʃe"],
    es_cl: ["leche", "ˈletʃe"],
    es_ar: ["leche", "ˈletʃe"],
    es_cu: ["leche", "ˈletʃe"],
    es_pe: ["leche", "ˈletʃe"],
    es_an: ["leche", "ˈletʃe"],
    es_sgl: ["leche", "ˈletʃe"],
    lad: ["leche", "ˈletʃe"],
    ast: ["lleche", "ˈʎetʃe"],
    ext: ["lechi", "ˈletʃi"],
    an: ["leit", "lejt"],
    mwl: ["lheite", "ˈʎejtɨ"],
    fax: ["leite", "ˈlejte"],
    pt_mo: ["leite", "ˈlejtɨ"],
    pt_ao: ["leite", "ˈlejte"],
    pt_mz: ["leite", "ˈlejte"],
    pt_cv: ["leite", "ˈlejte"],
    fr_qc: ["lait", "lɛ"],
    fr_be: ["lait", "lɛ"],
    fr_ch: ["lait", "lɛ"],
    fr_lu: ["lait", "lɛ"],
    fr_af: ["lait", "lɛ"],
    fr_cm: ["lait", "lɛ"],
    fr_sn: ["lait", "lɛ"],
    fr_ci: ["lait", "lɛ"],
    fr_ht: ["lait", "lɛ"],
    fr_class: ["lait", "lɛ"],
    ca_va: ["llet", "ʎet"],
    nap: ["latte", "ˈlattə"],
    scn: ["latti", "ˈlatti"],
    vec: ["late", "ˈlate"],
    co: ["latte", "ˈlatte"],
    lij: ["læte", "ˈlɛːte"],
    sc: ["late", "ˈlate"],
    fur: ["lat", "lat"],
    lmo: ["latt", "lat"],
    pms: ["làit", "lajt"],
    lld: ["lat", "lat"],
    egl: ["làt", "lat"],
    rm: ["latg", "latɕ"],
    rup: ["lapti", "ˈlapti"],
    ruq: ["lapti", "ˈlapti"],

    // --- More Slavic and Baltic -----------------------------------------
    hsb: ["mloko", "ˈmlɔkɔ"],
    dsb: ["mloko", "ˈmlɔko"],
    csb: ["mlékò", "ˈmlɛkɔ"],
    szl: ["mlyko", "ˈmlɨkɔ"],
    rue: ["молоко", "moloˈko"],
    orv: ["молоко", "moloko"],
    ltg: ["piens", "piens"],
    prg: ["dadan", "dadan"],

    // --- Celtic, Albanian, Greek ----------------------------------------
    gd: ["bainne", "ˈpaɲə"],
    gv: ["bainney", "ˈbanʲə"],
    mga: ["as", "as"],
    br: ["laezh", "leːs"],
    kw: ["leth", "lɛθ"],
    aln: ["tâmbël", "ˈtambəl"],
    pnt: ["γάλαν", "ˈɣalan"],

    // --- Indo-Aryan — dūdh from Sanskrit dugdha -------------------------
    as: ["গাখীৰ", "ɡakʰir"],
    bho: ["दूध", "d̪uːd̪ʱ"],
    anp: ["दूध", "d̪uːd̪ʱ"],
    awa: ["दूध", "d̪uːd̪ʱ"],
    mwr: ["दूध", "d̪uːd̪ʱ"],
    hne: ["दूध", "d̪uːd̪ʱ"],
    thr: ["दूध", "d̪uːd̪ʱ"],
    dty: ["दूध", "d̪uːd̪ʱ"],
    bhb: ["दूध", "d̪uːd̪ʱ"],
    kfx: ["दूध", "d̪uːd̪ʱ"],
    lmn: ["दूध", "d̪uːd̪ʱ"],
    mai: ["दूध", "d̪uːd̪ʱ"],
    bra: ["दूध", "d̪uːd̪ʱ"],
    bgc: ["दूध", "d̪uːd̪ʱ"],
    mag: ["दूध", "d̪uːd̪ʱ"],
    doi: ["दूध", "d̪uːd̪ʱ"],
    gbm: ["दूध", "d̪uːd̪ʱ"],
    kfy: ["दूध", "d̪uːd̪ʱ"],
    xnr: ["दूध", "d̪uːd̪ʱ"],
    bgq: ["दूध", "d̪uːd̪ʱ"],
    kfr: ["દૂધ", "d̪uːd̪ʱ"],
    or: ["ଦୁଧ", "d̪ud̪ʱɔ"],
    rkt: ["দুধ", "d̪ud̪ʱ"],
    ctg: ["দুধ", "d̪ud̪ʱ"],
    bpy: ["দুধ", "d̪ud̪ʱ"],
    pnb: ["دُدھ", "d̪ʊd̪ʱː"],
    hno: ["دُدھ", "d̪ʊd̪ʱː"],
    skr: ["دُدھ", "d̪ʊd̪ʱː"],
    sd: ["کير", "kʰiːru"],
    dv: ["ކިރު", "kiru"],
    hns: ["dudh", "d̪uːd̪ʱ"],
    hif: ["dudh", "d̪uːd̪ʱ"],
    nag: ["dudh", "d̪ud̪ʱ"],
    haj: ["dudh", "d̪ud̪ʱ"],
    rhg: ["duud", "d̪uːd̪"],
    rom: ["thud", "tʰud"],
    rmy: ["thud", "tʰud"],
    sa_edu: ["दुग्धम्", "duɡdʱam"],
    pmh: ["दुद्ध", "duddʱa"],

    // --- Iranian — šīr, the same word Persian has ------------------------
    prs: ["شیر", "ʃiːr"],
    fa_clas: ["شیر", "ʃiːr"],
    haz: ["شیر", "ʃiːr"],
    ku: ["şîr", "ʃiːr"],
    ckb: ["شیر", "ʃiːr"],
    sdh: ["شیر", "ʃiːr"],
    bal: ["شیر", "ʃiːr"],
    glk: ["شیر", "ʃir"],
    lrc: ["شیر", "ʃir"],
    bqi: ["شیر", "ʃir"],
    mzn: ["شیر", "ʃir"],
    luz: ["šir", "ʃir"],
    jpr: ["שיר", "ʃir"],
    zza: ["şit", "ʃit"],
    os: ["æхсыр", "əxsɨr"],

    // --- Turkic — süt, unbroken from Old Turkic --------------------------
    slr: ["süt", "syt"],
    ybe: ["süt", "syt"],
    gag: ["süt", "syt"],
    crh: ["süt", "syt"],
    kaa: ["süt", "syt"],
    xqa: ["süt", "syt"],
    tk: ["süýt", "syːjt"],
    qxq: ["süd", "syd"],
    azb: ["سود", "syd"],
    ota: ["سود", "syt"],
    cjs: ["сӱт", "syt"],
    kjh: ["сӱт", "syt"],
    alt: ["сӱт", "syt"],
    tyv: ["сүт", "syt"],
    kim: ["сүт", "syt"],
    kum: ["сют", "syt"],
    nog: ["сют", "syt"],
    krc: ["сют", "syt"],
    sah: ["үүт", "yːt"],
    dlg: ["үүт", "yːt"],
    ba: ["һөт", "høt"],
    cv: ["сӗт", "sət"],

    // --- Uralic ----------------------------------------------------------
    se: ["mielki", "ˈmielki"],
    krl: ["maido", "ˈmaido"],
    olo: ["maido", "ˈmaido"],
    vep: ["maid", "maid"],
    fkv: ["maito", "ˈmaito"],
    fit: ["maito", "ˈmaito"],
    vro: ["piim", "piːm"],
    kpv: ["йӧв", "jɵv"],
    koi: ["йӧв", "jɵv"],
    udm: ["йӧл", "jɵl"],
    mhr: ["шӧр", "ʃør"],
    mrj: ["шӧр", "ʃør"],
    myv: ["ловсо", "ˈlovso"],
    mdf: ["лофца", "ˈloftsa"],

    // --- Caucasus ---------------------------------------------------------
    ce: ["шура", "ʃura"],
    inh: ["шура", "ʃura"],
    av: ["рахь", "raħ"],
    lez: ["нек", "nek"],
    ady: ["щэ", "ʃa"],
    kbd: ["шэ", "ʃa"],
    ab: ["ахш", "axʃ"],

    // --- Semitic — the ḥ-l-b root -----------------------------------------
    ar_jo: ["حليب", "ħaliːb"],
    ar_ps: ["حليب", "ħaliːb"],
    ar_sy: ["حليب", "ħaliːb"],
    ar_lb: ["حليب", "ħaliːb"],
    ar_lev: ["حليب", "ħaliːb"],
    ar_iq: ["حليب", "ħaliːb"],
    ar_sa: ["حليب", "ħaliːb"],
    ar_ye: ["حليب", "ħaliːb"],
    acw: ["حليب", "ħaliːb"],
    afb: ["حليب", "ħaliːb"],
    abv: ["حليب", "ħaliːb"],
    ar_gulf: ["حليب", "ħaliːb"],
    ayl: ["حليب", "ħaliːb"],
    ar_ma: ["حليب", "ħlib"],
    arq: ["حليب", "ħlib"],
    ar_tn: ["حليب", "ħlib"],
    ar_eg: ["لبن", "ˈlaban"],
    ar_sd: ["لبن", "ˈlaban"],
    mt: ["ħalib", "ˈħaliːp"],
    syc: ["ܚܠܒܐ", "ħalbɔ"],
    tru: ["ܚܠܒܐ", "ħalwo"],
    aii: ["ܚܠܒܐ", "xalwa"],
    ti: ["ጸባ", "tsʼɐba"],
    tig: ["ሐሊብ", "ħaliːb"],
    kab: ["ayefki", "ajəfki"],
    om: ["aannan", "aːnːan"],

    // --- Africa ------------------------------------------------------------
    rw: ["amata", "amata"],
    rn: ["amata", "amata"],
    lg: ["amata", "amata"],
    xog: ["amata", "amata"],
    nyn: ["amate", "amate"],
    cgg: ["amate", "amate"],
    ttj: ["amate", "amate"],
    nyo: ["amate", "amate"],
    ki: ["iria", "iria"],
    tn: ["mashi", "maʃi"],
    st: ["lebese", "lebese"],
    nso: ["maswi", "maswi"],
    ts: ["masi", "masi"],
    ve: ["mafhi", "maɸi"],
    ssw: ["lubisi", "luˈbisi"],
    nd: ["uchago", "uˈtʃaɡo"],
    sn: ["mukaka", "mukaka"],
    mxc: ["mukaka", "mukaka"],
    ny: ["mkaka", "m̩kaka"],
    tum: ["mkaka", "m̩kaka"],
    bem: ["umukaka", "umukaka"],
    ff: ["kosam", "kosam"],
    wo: ["meew", "meːw"],
    bm: ["nɔnɔ", "nɔnɔ"],
    dyu: ["nɔnɔ", "nɔnɔ"],
    emk: ["nɔnɔ", "nɔnɔ"],
    mwk: ["nɔnɔ", "nɔnɔ"],
    mlq: ["nɔnɔ", "nɔnɔ"],
    kao: ["nɔnɔ", "nɔnɔ"],
    mnk: ["nono", "nono"],
    // Ewe and Igbo build it out of 'breast' + 'water'; both are phrases in origin.
    ee: ["notsi", "notsi"],
    gej: ["notsi", "notsi"],
    ig: ["mmiri ara", "mːiɾi aɾa"],
    luo: ["chak", "tʃak"],
    ach: ["cak", "tʃak"],
    laj: ["cak", "tʃak"],
    mas: ["kule", "kule"],
    saq: ["kule", "kule"],

    // --- East Asia ----------------------------------------------------------
    zh_tw: ["牛奶", "njoʊ˧˥ naɪ˨˩˦"],
    vi_han: ["乳", "ɲu˧ˀ˥"],
    ja_osa: ["牛乳", "ɡʲɯːɲɯː"],
    ja_kyo: ["牛乳", "ɡʲɯːɲɯː"],
    ja_hak: ["牛乳", "ɡʲɯːɲɯː"],
    ja_hir: ["牛乳", "ɡʲɯːɲɯː"],
    ja_aom: ["牛乳", "ɡʲɯːɲɯː"],
    ja_kg: ["牛乳", "ɡʲɯːɲɯː"],
    ja_sd: ["牛乳", "ɡʲɯːɲɯː"],
    ko_kp: ["우유", "uju"],
    ko_bus: ["우유", "uju"],
    ko_yb: ["우유", "uju"],
    ko_hg: ["우유", "uju"],
    ko_jl: ["우유", "uju"],
    ko_jeju: ["우유", "uju"],
    xct: ["འོ་མ", "oma"],
    xct_litpr: ["འོ་མ", "oma"],
    adx: ["འོ་མ", "oma"],
    bft: ["འོ་མ", "oma"],
    lbj: ["འོ་མ", "oma"],
    xsr: ["འོ་མ", "oma"],
    sip: ["འོ་མ", "oma"],
    new: ["दुरु", "duru"],
    mni: ["ꯁꯪꯒꯣꯝ", "səŋɡom"],
    brx: ["गाखिर", "ɡakʰir"],
    bxr: ["һүн", "hyn"],
    xal: ["үсн", "ysn̩"],
    mnc: ["ᠰᡠᠨ", "sun"],

    // --- Dravidian ----------------------------------------------------------
    tcy: ["ಪೇರ್", "peːr"],
    kfa: ["ಪಾಲ್", "paːl"],
    gon: ["पाल", "paːl"],
    iru: ["pāl", "paːl"],
    bfq: ["haalu", "haːlu"],

    // --- Austronesian — susu in the west, gatas in the Philippines ----------
    jv: ["susu", "susu"],
    jvn: ["susu", "susu"],
    su: ["susu", "susu"],
    min: ["susu", "susu"],
    ban: ["susu", "susu"],
    bjn: ["susu", "susu"],
    iba: ["susu", "susu"],
    sas: ["susu", "susu"],
    mui: ["susu", "susu"],
    abs: ["susu", "susu"],
    max: ["susu", "susu"],
    pmy: ["susu", "susu"],
    bew: ["susu", "susu"],
    mfa: ["susu", "susu"],
    omy: ["susu", "susu"],
    kaw: ["ꦱꦸꦱꦸ", "susu"],
    sm: ["susu", "susu"],
    ilo: ["gatas", "ˈɡatas"],
    hil: ["gatas", "ˈɡatas"],
    war: ["gatas", "ˈɡatas"],
    bik: ["gatas", "ˈɡatas"],
    bto: ["gatas", "ˈɡatas"],
    tsg: ["gatas", "ˈɡatas"],
    pam: ["gatas", "ɡaˈtas"],
    pag: ["gatas", "ɡaˈtas"],
    h_tagalog: ["ᜄᜆᜐ᜔", "ˈɡatas"],
    // Polynesian names it from the breast — Tahitian ū, Hawaiian waiū 'breast water'.
    ty: ["ū", "uː"],
    rar: ["ū", "uː"],
    to: ["huʻakau", "huʔaˈkau"],
    ch: ["leche", "ˈletʃe"],

    // --- Creoles and constructed languages ----------------------------------
    jam: ["milk", "mɪlk"],
    bah: ["milk", "mɪlk"],
    bzj: ["milk", "mɪlk"],
    pcm: ["milk", "mɪlk"],
    hwc: ["milk", "mɪlk"],
    kri: ["milk", "mɪlk"],
    tpi: ["susu", "susu"],
    pis: ["susu", "susu"],
    srn: ["merki", "ˈmɛrki"],
    ht: ["lèt", "lɛt"],
    gcf: ["lèt", "lɛt"],
    gcr: ["lèt", "lɛt"],
    acf: ["lèt", "lɛt"],
    mfe: ["dile", "dile"],
    crs: ["dile", "dile"],
    pap: ["lechi", "ˈletʃi"],
    cbk: ["leche", "ˈletʃe"],
    eo: ["lakto", "ˈlakto"],
    io: ["lakto", "ˈlakto"],
    ia: ["lacte", "ˈlakte"],
    ie: ["lacte", "ˈlakte"],
    jbo: ["ladru", "ˈladru"],
    // Toki Pona has no root for it — 'white liquid' is the usual phrase.
    tok: ["telo walo", "telo walo"],

    // --- Americas and the Arctic ---------------------------------------------
    kl: ["immuk", "imːuk"],
    iu: ["ᐃᒻᒧᒃ", "imːuk"],
    ik: ["immuk", "imːuk"],
    nv: ["abeʼ", "àpèʔ"],
    lkt: ["asáŋpi", "aˈsãpi"],
    // Classical Nahuatl names it 'breast water' too.
    nci: ["chīchīhualāyōtl", "tʃiːtʃiːwalaːjoːtɬ"],
    gn: ["kamby", "kambɨ"],
    gun: ["kamby", "kambɨ"],
    tpn: ["kamby", "kambɨ"],

    // --- Deep reconstructions, and the oldest writing --------------------------
    sux: ["𒂵", "ɡa"],
    ptrk: ["*sǖt", "syːt"],
    pmng: ["*sün", "syn"],
    psem: ["*ḥalab-", "ħalab-"],
    p_dra: ["*pāl", "pāl"],
    vi_nom: ["𣳪", "sɨə˧ˀ˥"],
  },
};
