/**
 * person — one human being, the sex-neutral citation word.
 *
 * Languages carve the notion up several ways. Latin persona (a mask-word taken
 * from Etruscan through the theatre) spread across Romance and on into English
 * and Welsh; Germanic keeps *manniz "Mensch / mens / människa"; Slavic stands
 * apart with *čelověkъ, and Greek ánthrōpos is its own root again. The
 * Sinosphere anchors on 人 (Japanese hito, beside Korean saram). Where a
 * language's plain word really means "man", the sex-neutral term is taken.
 */
WORDS.person = {
  label: {
    en: "Person",
    ja: "人",
    ko: "사람",
    zh: "人",
    yue: "人",
    vi: "Người",
    th: "คน",
    id: "Orang",
    hi: "व्यक्ति",
    de: "Mensch",
    fr: "Personne",
    it: "Persona",
    es: "Persona",
    es_eu: "Persona",
    es_mx: "Persona",
    pt: "Pessoa",
    pt_eu: "Pessoa",
    pt_br: "Pessoa",
    ru: "Человек",
    uk: "Людина",
    ar: "شخص",
    he: "אדם",
    sw: "Mtu",
  },
  definition: {
    en: "A single human being, citation form — the generic word for one person of any sex or age. Not \"man\" in the male sense, and not the plural collective \"people\".",
    ja: "一人の人間を指す辞書形。性別や年齢を問わず「人」を表す一般語であり、男性を指す「男」でも、集合的な「人々」でもない。",
    ko: "한 사람의 인간을 가리키는 사전형. 성별이나 나이와 무관하게 '사람'을 뜻하는 일반어이며, 남성을 뜻하는 '남자'도, 집합적인 '사람들'도 아니다.",
    zh: "指一个人的词典形，泛指任何性别、年龄的单个人类。不取专指男性的“男人”，也不取集合义的“人们”。",
    yue: "指一個人嘅詞典形，泛指任何性別、年齡嘅單個人類。唔取專指男性嘅「男人」，亦唔取集合義嘅「人哋」。",
    vi: "Dạng từ điển chỉ một con người — từ chung cho một người bất kể giới tính hay tuổi tác. Không phải \"đàn ông\" theo nghĩa nam giới, cũng không phải \"người ta / mọi người\" theo nghĩa tập hợp.",
    th: "รูปพจนานุกรมที่หมายถึงมนุษย์คนหนึ่ง เป็นคำทั่วไปสำหรับคนคนเดียวไม่ว่าเพศหรือวัยใด ไม่ใช่ \"ผู้ชาย\" ในความหมายเพศชาย และไม่ใช่ \"ผู้คน\" ในความหมายรวมหมู่",
    id: "Bentuk kamus untuk satu manusia — kata umum bagi seorang individu tanpa memandang jenis kelamin atau usia. Bukan \"laki-laki\" dalam arti pria, dan bukan \"orang-orang\" dalam arti kolektif.",
    hi: "एक मनुष्य को दर्शाने वाला शब्दकोश-रूप — किसी भी लिंग या आयु के एक व्यक्ति के लिए सामान्य शब्द। न पुरुष के अर्थ में \"आदमी\", न समूहवाचक \"लोग\"।",
    de: "Die Zitierform für einen einzelnen Menschen — das allgemeine Wort für eine Person jeden Geschlechts und Alters. Nicht „Mann“ im männlichen Sinn und nicht das kollektive „Leute“.",
    fr: "La forme de citation pour un être humain — le mot général désignant une personne quels que soient son sexe et son âge. Pas « homme » au sens masculin, ni le collectif « gens ».",
    it: "La forma di citazione per un singolo essere umano — la parola generale per una persona di qualsiasi sesso o età. Non «uomo» nel senso maschile, né il collettivo «gente».",
    es: "La forma de cita para un ser humano — la palabra general para una persona de cualquier sexo o edad. No «hombre» en el sentido masculino, ni el colectivo «gente».",
    es_eu: "La forma de cita para un ser humano — la palabra general para una persona de cualquier sexo o edad. No «hombre» en el sentido masculino, ni el colectivo «gente».",
    es_mx: "La forma de cita para un ser humano — la palabra general para una persona de cualquier sexo o edad. No «hombre» en el sentido masculino, ni el colectivo «gente».",
    pt: "A forma de citação para um ser humano — a palavra geral para uma pessoa de qualquer sexo ou idade. Não «homem» no sentido masculino, nem o coletivo «gente».",
    pt_eu: "A forma de citação para um ser humano — a palavra geral para uma pessoa de qualquer sexo ou idade. Não «homem» no sentido masculino, nem o coletivo «gente».",
    pt_br: "A forma de citação para um ser humano — a palavra geral para uma pessoa de qualquer sexo ou idade. Não «homem» no sentido masculino, nem o coletivo «gente».",
    ru: "Словарная форма для отдельного человека — общее слово для одного человека любого пола и возраста. Не «мужчина» в мужском смысле и не собирательное «люди».",
    uk: "Словникова форма для окремої людини — загальне слово для однієї людини будь-якої статі та віку. Не «чоловік» у чоловічому значенні й не збірне «люди».",
    ar: "صيغة المعجم للفرد الواحد من البشر — الكلمة العامة لشخص واحد أيًّا كان جنسه أو عمره. لا «الرجل» بالمعنى الذكوري، ولا «الناس» بالمعنى الجمعي.",
    he: "צורת המילון לאדם יחיד — המילה הכללית לאדם אחד מכל מין וגיל. לא \"גבר\" במובן הזכרי, ולא הריבוי הקיבוצי \"אנשים\".",
    sw: "Umbo la kamusi kwa binadamu mmoja — neno la jumla kwa mtu mmoja wa jinsia au umri wowote. Si \"mwanamume\" kwa maana ya kiume, wala \"watu\" kwa maana ya wingi.",
  },
  data: {
    en: ["person", "ˈpɜːsən"],
    de: ["Mensch", "mɛnʃ"],
    nl: ["mens", "mɛns"],
    sv: ["människa", "ˈmɛnːɪɧa"],
    da: ["menneske", "ˈmenəsɡə"],
    no: ["menneske", "ˈmɛnːəskə"],
    fr: ["personne", "pɛʁsɔn"],
    es: ["persona", "peɾˈsona"],
    it: ["persona", "perˈsona"],
    pt: ["pessoa", "pɨˈsoɐ"],
    ro: ["persoană", "persoˈanə"],
    ca: ["persona", "pərˈsonə"],
    ru: ["человек", "tɕɪlɐˈvʲek"],
    uk: ["людина", "lʲuˈdɪnɐ"],
    pl: ["człowiek", "ˈtʂwɔvjɛk"],
    cs: ["člověk", "ˈtʃlovjɛk"],
    sk: ["človek", "ˈtʃlovek"],
    bg: ["човек", "tʃoˈvɛk"],
    sr: ["човек", "tʃoʋek"],
    hr: ["čovjek", "tʃoʋjek"],
    sl: ["človek", "ˈtʃlɔʋɛk"],
    el: ["άνθρωπος", "ˈanθropos"],
    hi: ["व्यक्ति", "ˈʋjəkt̪i"],
    bn: ["মানুষ", "ˈmanuʃ"],
    fa: ["انسان", "ʔenˈsɒːn"],
    ur: ["انسان", "ɪnˈsaːn"],
    ja: ["人", "çito"],
    ko: ["사람", "saɾam"],
    zh: ["人", "ʐən˧˥"],
    yue: ["人", "jɐn˨˩"],
    vi: ["người", "ŋɨəi˨˩"],
    th: ["คน", "kʰon˧"],
    id: ["orang", "ˈoraŋ"],
    ms: ["orang", "ˈoraŋ"],
    tl: ["tao", "ˈtaʔo"],
    ceb: ["tawo", "ˈtawo"],
    ar: ["شخص", "ʃaxsˤ"],
    he: ["אדם", "aˈdam"],
    tr: ["kişi", "kiˈʃi"],
    sw: ["mtu", "ˈmtu"],
    fi: ["ihminen", "ˈihminen"],
    hu: ["ember", "ˈɛmbɛr"],
    eu: ["pertsona", "perˈts̻ona"],
    ga: ["duine", "ˈd̪ˠɪnʲə"],
    cy: ["person", "ˈpɛrsɔn"],
    hy: ["մարդ", "mɑrtʰ"],
    ka: ["ადამიანი", "adamiani"],
    af: ["mens", "mɛns"],
    is: ["manneskja", "ˈmanːɛskja"],
    lb: ["Mënsch", "mənʃ"],
    yi: ["מענטש", "mɛntʃ"],
    gl: ["persoa", "pɛɾˈsoa"],
    oc: ["persona", "perˈsunɔ"],
    la: ["homo", "ˈhomoː"],
    eo: ["homo", "ˈhomo"],
    sq: ["njeri", "ɲɛˈri"],
    be: ["чалавек", "tʂalaˈvʲɛk"],
    mk: ["човек", "ˈtʃɔvɛk"],
    bs: ["čovjek", "ˈtʃɔʋjɛk"],
    lt: ["žmogus", "ʒmoːˈɡus"],
    lv: ["cilvēks", "ˈtsilvɛːks"],
    et: ["inimene", "ˈinimene"],
    mt: ["bniedem", "ˈbniɛdɛm"],
    gd: ["duine", "ˈt̪ɯnʲə"],
    br: ["den", "deːn"],
    mn: ["хүн", "xuŋ"],
    az: ["insan", "inˈsan"],
    kk: ["адам", "ɑˈdɑm"],
    ky: ["адам", "ɑˈdɑm"],
    uz: ["odam", "ɒˈdam"],
    tk: ["adam", "ɑˈdɑm"],
    tt: ["кеше", "keˈʃe"],
    gu: ["વ્યક્તિ", "ˈʋjəkti"],
    mr: ["माणूस", "ˈmaːɳuːs"],
    ne: ["मान्छे", "ˈmantsʰe"],
    te: ["మనిషి", "maˈniʃi"],
    ku: ["mirov", "mɨˈrov"],
    tg: ["одам", "ɔˈdam"],
    bo: ["མི", "mi"],
    my: ["လူ", "lù"],
    km: ["មនុស្ស", "mɔˈnuh"],
    jv: ["wong", "wɔŋ"],
    haw: ["kanaka", "kaˈnaka"],
    mi: ["tangata", "ˈtaŋata"],
    sm: ["tagata", "taˈŋata"],
    to: ["tangata", "taˈŋata"],
    mg: ["olona", "ˈulnə"],
    zu: ["umuntu", "uˈmuntu"],
    xh: ["umntu", "ˈumntu"],
    am: ["ሰው", "səw"],
    so: ["qof", "qof"],
    sn: ["munhu", "muˈɲu"]
  }
};
