/**
 * poop — the everyday, informal/childish word for excrement (Japanese うんち,
 * not the clinical 便; Korean 똥; Chinese 屎/便便), as opposed to a clinical
 * term like "feces" or "stool". A striking number of unrelated language
 * families converge on the same nursery-babble shape: a reduplicated or
 * near-reduplicated syllable built on a velar stop + low vowel — caca
 * (Romance), kaka (Slavic, Germanic, Greek, Turkic, Finnic, Armenian,
 * Celtic) — independently traceable in several families to the PIE root
 * *kakka- "to void excrement", likely onomatopoeic for the grunt of straining.
 */
WORDS.poop = {
  partial: true,
  emoji: "💩",
  label: {
    en: "Poop",
    ja: "うんち",
    ko: "똥",
    zh: "便便",
    yue: "屎",
    vi: "Phân",
    th: "อึ",
    id: "Pup",
    hi: "टट्टी",
    de: "Kacke",
    fr: "Caca",
    it: "Cacca",
    es: "Caca",
    es_eu: "Caca",
    es_mx: "Caca",
    pt: "Cocô",
    pt_eu: "Cocó",
    pt_br: "Cocô",
    ru: "Кака",
    uk: "Кака",
    ar: "كاكا",
    he: "קקי",
    sw: "Kinyesi",
  },
  definition: {
    en: "Poop — the everyday, informal/childish word for excrement, not the clinical term (feces/stool).",
    ja: "うんち——排泄物を指す日常的・幼児語的な言い方。医学用語の「便」ではない。",
    ko: "똥 — 배설물을 가리키는 일상적·유아어적인 말. 의학 용어인 '대변'이 아니다.",
    zh: "便便——指排泄物的日常、儿语化说法，不是临床用语「粪便」。",
    yue: "屎——指排泄物嘅日常、口語講法，唔係臨床用語。",
    vi: "Phân — từ thông dụng, đời thường để chỉ chất thải của cơ thể; không phải thuật ngữ y khoa.",
    th: "อึ — คำเรียกอุจจาระแบบลำลองหรือคำเด็ก ไม่ใช่ศัพท์ทางการแพทย์",
    id: "Pup — kata sehari-hari/kata anak-anak untuk kotoran manusia; bukan istilah medis.",
    hi: "टट्टी — मल के लिए रोज़मर्रा का, बच्चों जैसा शब्द; चिकित्सकीय शब्द नहीं।",
    de: "Kacke — das umgangssprachliche, kindliche Wort für Kot; kein medizinischer Fachbegriff.",
    fr: "Caca — le mot familier et enfantin pour les excréments ; pas le terme médical.",
    it: "Cacca — la parola informale e infantile per gli escrementi; non il termine clinico.",
    es: "Caca — la palabra informal e infantil para las heces; no el término clínico.",
    es_eu: "Caca — la palabra informal e infantil para las heces; no el término clínico.",
    es_mx: "Caca — la palabra informal e infantil para las heces; no el término clínico.",
    pt: "Cocô — a palavra informal e infantil para as fezes; não o termo clínico.",
    pt_eu: "Cocó — a palavra informal e infantil para as fezes; não o termo clínico.",
    pt_br: "Cocô — a palavra informal e infantil para as fezes; não o termo clínico.",
    ru: "Кака — разговорное, детское слово для обозначения испражнений; не медицинский термин.",
    uk: "Кака — розмовне, дитяче слово для позначення випорожнень; не медичний термін.",
    ar: "كاكا — الكلمة العامية والطفولية للبراز؛ وليست المصطلح الطبي.",
    he: "קקי — המילה היומיומית והילדית לצואה; לא המונח הרפואי.",
    sw: "Kinyesi — neno la kawaida la kila siku kwa mavi; si neno la kitaalamu.",
  },
  data: {
    es_cr: ["caca", "ˈkaka"],
    es_hn: ["caca", "ˈkaka"],
    es_ni: ["caca", "ˈkaka"],
    es_sv: ["caca", "ˈkaka"],
    fr_lu: ["caca", "kaka"],
    fr_cm: ["caca", "kaka"],
    en_ng2: ["poop", "puːp"],
    pt_mo: ["cocó", "kuˈkɔ"],
    lb: ["Kack", "kak"],
    gan_yc: ["屎", "ʂɨ˨˩˥"],
    gan_ja: ["屎", "sɨ˨˩˧"],
    gan_fz: ["屎", "ʂɨ˧˨"],
    cjy_lv: ["屎", "sz̩˥˧"],
    cjy_xz: ["屎", "sz̩˥˧"],
    hsn_hy: ["屎", "sz̩˧˧"],
    hsn_yz: ["屎", "tsʰz̩˨˩"],
    es_bo: ["caca", "ˈkaka"],
    es_py: ["caca", "ˈkaka"],
    es_pa: ["caca", "ˈkaka"],
    en_my: ["poop", "puːp"],
    pt_gw: ["cocô", "koˈko"],
    es_pr: ["caca", "ˈkaka"],
    es_do: ["caca", "ˈkaka"],
    es_gt: ["caca", "ˈkaka"],
    es_ec: ["caca", "ˈkaka"],
    es_uy: ["caca", "ˈkaka"],
    en_wls: ["poo", "puː"],
    en_jam: ["poo", "puː"],
    en_ng: ["poop", "puːp"],
    en_ph: ["poop", "puːp"],
    en_ke: ["poop", "puːp"],
    fr_sn: ["caca", "kaka"],
    fr_ci: ["caca", "kaka"],
    fr_ht: ["caca", "kaka"],
    pt_mz: ["cocô", "koˈko"],
    pt_cv: ["cocó", "kuˈkɔ"],
    nl_be: ["poep", "pup"],
    en_us: ["poop", "puːp"],
    en_ca: ["poop", "puːp"],
    en_za: ["poo", "puː"],
    de_ch: ["Kacke", "ˈkakə"],
    pt_ao: ["cocô", "koˈko"],
    es_ve: ["caca", "ˈkaka"],
    ca_va: ["caca", "ˈkaka"],
    ja: ["うんち", "ɯ̃ɴtɕi"],
    ja_osa: ["うんち", "ɯ̃ɴtɕi"],
    ja_aom: ["うんち", "ɯ̃ɴtɕi"],
    ja_oki: ["くす", "kusu"],
    ja_hak: ["うんち", "ɯ̃ɴtɕi"],
    ja_kyo: ["うんち", "ɯ̃ɴtɕi"],
    ja_hir: ["うんち", "ɯ̃ɴtɕi"],
    ja_mvi: ["くす", "kusu"],
    ja_rys: ["くす", "kusu"],
    ko: ["똥", "t͈oŋ"],
    ko_kp: ["똥", "t͈oŋ"],
    ko_bus: ["똥", "t͈oŋ"],
    ko_jeju: ["똥", "t͈oŋ"],
    ko_yb: ["똥", "t͈oŋ"],
    zh: ["便便", "pjɛn˥˩pjɛn"],
    yue: ["屎", "si˧˥"],
    nan: ["屎", "sai˥˧"],
    zh_tw: ["便便", "pjɛn˥˩pjɛn"],
    wuu: ["屎", "sz̩˧˥"],
    hak_cn: ["屎", "sɨ˧˩"],
    vi: ["cứt", "kɨt̚˧˥"],
    vi_c: ["phân", "fɤn˧˧"],
    vi_s: ["phân", "fɤŋ˧˧"],
    th: ["อึ", "ʔɯː˥˩"],
    id: ["pup", "pup"],
    ms: ["tahi", "ˈtahi"],
    hi: ["टट्टी", "ʈəʈːiː"],
    sa_edu: ["गूथ", "ɡuːtʰɐ"],
    sa: ["गूथ", "ɡuːtʰɐ"],
    bn: ["হাগু", "haɡu"],
    ur: ["ٹٹی", "ʈəʈːiː"],
    ta: ["மலம்", "mʌlʌm"],
    en: ["poop", "puːp"],
    de: ["Kacke", "ˈkakə"],
    fr: ["caca", "kaka"],
    it: ["cacca", "ˈkakka"],
    es: ["caca", "ˈkaka"],
    es_mx: ["caca", "ˈkaka"],
    pt: ["cocô", "koˈko"],
    pt_br: ["cocô", "koˈko"],
    ru: ["кака", "ˈkakə"],
    ar: ["كاكا", "kaːka"],
    he: ["קקי", "ˈkaki"],
    tr: ["kaka", "kaka"],
    fa: ["گه", "ɡoh"],
    prs: ["گه", "guːh"],
    sw: ["Kinyesi", "kiˈɲesi"],
    tl: ["tae", "ˈtaʔɛ"],
    mn: ["баас", "paːs"],
    cv: ["пӑх", "pəx"],
    my: ["ချေး", "tɕʰé"],
    km: ["អាចម៍", "ʔacam"],
    lo: ["ຂີ້", "kʰiː˥˩"],
    yo: ["igbe", "iɡbɛ"],
    zu: ["amasimba", "amasimba"],
    am: ["ኩስ", "kus"],
    mg: ["tay", "taj"],
    fi: ["kakka", "ˈkakːɑ"],
    hu: ["kaki", "ˈkɒki"],
    el: ["κακά", "kaˈka"],
    nl: ["poep", "pup"],
    pl: ["kupa", "ˈkupa"],
    uk: ["кака", "ˈkaka"],
    sv: ["bajs", "bajs"],
    no: ["bæsj", "bæʃ"],
    da: ["lort", "loɐt"],
    ro: ["caca", "ˈkaka"],
    ga: ["cac", "kak"],
    eu: ["kaka", "kaka"],
    cy: ["cach", "kaːχ"],
    ka: ["კაკა", "kʼakʼa"],
    hy: ["քաքա", "kʰɑkʰɑ"],
    nv: ["chąąʼ", "tʃãːʔ"],
    haw: ["kūkae", "kuːkae"],
    mi: ["tūtae", "tuːtae"],
    qu: ["aka", "aka"],
    zh_db: ["屎", "ʂz̩˧˩˧"],
    zh_sc: ["屎", "sz̩˥˧"],
    cdo: ["屎", "sai˧˩"],
    bo: ["སྐྱག་པ", "tɕaʔpa"],
    th_isan: ["อึ", "ʔɯ˨˩"],
    th_n: ["อึ", "ʔɯ˨˩"],
    th_s: ["อึ", "ʔɯ˨˩"],
    za: ["haex", "haɯ˦"],
    jv: ["tai", "ˈtai"],
    su: ["taiʔ", "taiʔ"],
    ceb: ["tae", "taʔe"],
    ilo: ["tai", "taʔi"],
    sm: ["tae", "taʔe"],
    to: ["taʻe", "taʔe"],
    pa: ["ਟੱਟੀ", "ʈəʈːiː"],
    pnb: ["ٹٹی", "ʈəʈːiː"],
    ne: ["दिसा", "disaː"],
    mr: ["शी", "ʃiː"],
    gu: ["ગૂ", "ɡuː"],
    te: ["మలం", "malam"],
    kn: ["ಮಲ", "mala"],
    ml: ["മലം", "malam"],
    tg: ["гӯҳ", "ɡuːh"],
    ku: ["gû", "ɡuː"],
    ckb: ["گو", "ɡuː"],
    ps: ["سوپه", "ˈsʊpa"],
    az: ["kaka", "kaka"],
    azb: ["کاکا", "kaka"],
    ug: ["پوق", "poq"],
    kk: ["боқ", "boq"],
    ky: ["бок", "bok"],
    tk: ["bok", "bok"],
    ar_eg: ["كاكا", "kaːka"],
    ar_lev: ["كاكا", "kaːka"],
    ar_gulf: ["كاكا", "kaːka"],
    ar_iq: ["كاكا", "kaːka"],
    ar_ma: ["كاكا", "kaːka"],
    ar_tn: ["كاكا", "kaːka"],
    ar_sd: ["كاكا", "kaːka"],
    mt: ["kaka", "ˈkaka"],
    ig: ["nsị", "n̩sḭ"],
    ha: ["kashi", "kaʃi"],
    so: ["saxaro", "saħaro"],
    rw: ["amase", "amase"],
    rn: ["amase", "amase"],
    xh: ["amasimba", "amasimba"],
    en_aave: ["poop", "puːp"],
    en_nz: ["poo", "puː"],
    en_au: ["poo", "pʉː"],
    sco: ["keech", "kiːtʃ"],
    af: ["poep", "puəp"],
    de_at: ["Kacke", "ˈkakə"],
    yi: ["דרעק", "drɛk"],
    is: ["kúkur", "kʰuːkʏr"],
    gd: ["cac", "kʰaxk"],
    br: ["kac'h", "kax"],
    nap: ["cacca", "ˈkakːə"],
    scn: ["cacca", "ˈkakka"],
    ca: ["caca", "ˈkakə"],
    gl: ["caca", "ˈkaka"],
    be: ["кака", "ˈkaka"],
    cs: ["kaka", "ˈkaka"],
    sk: ["kaka", "ˈkaka"],
    sl: ["kakec", "ˈkaːkɛts"],
    sr: ["какица", "ˈkakitsa"],
    bg: ["каки", "kaˈki"],
    lt: ["kaka", "ˈkaka"],
    lv: ["kaka", "ˈkaka"],
    sq: ["kakë", "ˈkakə"],
    et: ["kaka", "ˈkɑkɑ"],
    ht: ["kaka", "kaka"],
    pap: ["kaka", "kaka"],
    tpi: ["pekpek", "pɛkpɛk"],
    pis: ["kaka", "kaka"],
    se: ["baika", "ˈpajːka"],
    gn: ["tepoti", "tepoti"],
    as: ["গু", "ɡu"],
    bho: ["टट्टी", "ʈəʈːiː"],
    en_south: ["poop", "puːp"],
    en_app: ["poop", "puːp"],
    en_in: ["poo", "puː"],
    en_ie: ["poo", "puː"],
    en_sco: ["poo", "puː"],
    en_yk: ["poo", "puː"],
    en_ck: ["poo", "puː"],
    en_scouse: ["poo", "puː"],
    en_geordie: ["poo", "puː"],
    en_brum: ["poo", "puː"],
    en_manc: ["poo", "puː"],
    en_wc: ["poo", "puː"],
    en_est: ["poo", "puː"],
    en_sg: ["poop", "puːp"],
    fo: ["kúkur", "kʉːkʊr"],
    fr_qc: ["caca", "kaka"],
    fr_af: ["caca", "kaka"],
    fr_be: ["caca", "kaka"],
    fr_ch: ["caca", "kaka"],
    es_co: ["caca", "ˈkaka"],
    es_cl: ["caca", "ˈkaka"],
    es_ar: ["caca", "ˈkaka"],
    es_cu: ["caca", "ˈkaka"],
    es_pe: ["caca", "ˈkaka"],
    es_an: ["caca", "ˈkaka"],
    sc: ["cacca", "ˈkakka"],
    la: ["merda", "ˈmɛrda"],
    el_grc: ["κόπρος", "ˈkopros"],
    el_kath: ["κόπρος", "ˈkopros"],
    egy: ["𓎛𓋴", "hɛs"],
    enm: ["tord", "tord"],
    en_em: ["turd", "tɜːrd"],
    ang: ["tord", "tord"],
    non: ["drit", "drit"],
    got: ["𐍃𐌼𐌰𐍂𐌽𐌰", "ˈsmarna"],
    cu: ["гъно", "ˈgŭno"],
    pi: ["गूथ", "ɡuːtʰɐ"],
    pi_edu: ["gūtha", "ɡuːtʰɐ"],
    akk: ["𒍪𒌑", "zuː"],
    nci: ["cuitlatl", "kʷitɬatɬ"],
    p_ine: ["*kakka-", "kakka"],
    p_jpn: ["*kuso", "kuso"],
    ptrk: ["*bok", "bok"],
    pmay: ["*ta7", "taʔ"],
    psem: ["*ḫaraʔ-", "haraʔ"],
    pura: ["*pućka", "putɕka"],
    paus: ["*Caqi", "tsaqi"],
    zh_song: ["屎", "ʂɿ˧˩˧"],
    zh_wenyan_edu: ["屎", "siː˧˥"],
    zh_han: ["屎", "ɕiʔ"],
    zh_tang: ["屎", "ɕiɪX"],
    ja_edo: ["うんこ", "uŋko"],
    ja_kanbun: ["糞", "kuso"],
    ja_heian: ["くそ", "kuso"],
    ja_chu: ["くそ", "kuso"],
    p_ryu: ["*kuso", "kuso"],
    ko_mid: ["ᄯᅩᇰ", "stwoŋ"],
    ko_em: ["똥", "t͈oŋ"],
    vi_han: ["糞", "fɤn˧˧"],
    vi_nom: ["𡳛", "kɨt̚˧˥"],
    eo: ["kako", "ˈkako"],
    ia: ["caca", "ˈkaka"],
    jbo: ["kalci", "ˈkalʃi"],
    cjy: ["屎", "sz̩˥˧"],
    hsn: ["屎", "sz̩˦˩"],
    gan: ["屎", "sɨ˨˩˧"],
    mai: ["टट्टी", "ʈəʈːiː"],
    hil: ["tae", "taʔe"],
    mk: ["каки", "ˈkaki"],
    ay: ["jama", "xama"],
    kl: ["anaq", "anaq"],
    ty: ["tūtae", "tuːtae"],
    niu: ["tae", "taʔe"],
    ch: ["tåke'", "ˈtɑkɛʔ"],
    bi: ["kaka", "kaka"],
    pjt: ["kuna", "kuna"],
    wbp: ["kuna", "kuna"],
    ban: ["tai", "tai"],
    war: ["tae", "taʔe"],
    bgc: ["टट्टी", "ʈəʈːiː"],
    mnp: ["屎", "sai˨˩"],
    nan_te: ["屎", "sai˥˧"],
    yue_ts: ["屎", "ɬi˧˧"],
    zh_jh: ["屎", "sz̩˨˩˦"],
    zh_tj: ["屎", "ʂz̩˩˧"],
    zh_lz: ["屎", "sz̩˦˦˨"],
    ast: ["caca", "ˈkaka"],
    an: ["caca", "ˈkaka"],
    nbl: ["amasimba", "amasimba"],
    nd: ["amasimba", "amasimba"],
    kw: ["kawgh", "kauɣ"],
    kgp: ["—", "—"],
    tob: ["—", "—"],
    plg: ["—", "—"],
    moc: ["—", "—"],
    mbc: ["—", "—"],
    kpj: ["—", "—"],
    guu: ["—", "—"],
    bwi: ["—", "—"],
    cag: ["—", "—"],
    crt: ["—", "—"],
    tpy: ["—", "—"],
    jup: ["—", "—"],
    kwa: ["—", "—"],
    hr: ["kakica", "ˈkakitsa"],
    pal: ["𐭢𐭥𐭧", "ɡoːh"],
    fro: ["merde", "ˈmɛrdə"],
    fr_class: ["merde", "mɛʁd"],
    it_dan: ["merda", "ˈmɛrda"],
    gmh: ["schîze", "ʃiːtsə"],
    sga: ["cac", "kak"],
    mga: ["cac", "kak"],
    hbo: ["חרא", "ħaraːʔ"],
    hy_grab: ["աղբ", "ɑʁb"],
    ja_kg: ["うんち", "ɯ̃ɴtɕi̥"],
    ja_sd: ["うんち", "ɯ̃ɴtɕi"],
    ko_hg: ["똥", "t͈oŋ"],
    ko_jl: ["똥", "t͈oŋ"],
    nan_pn: ["屎", "sai˥˧"],
    wuu_nb: ["屎", "sɿ˨˩˦"],
    yue_gz: ["屎", "si˧˥"],
    orv: ["говьно", "ɡovʲˈno"],
    qwc: ["aka", "ˈaka"],
    och: ["屎", "*[qʰ]ijʔ"],
    ojp: ["屎", "kuso"],
    hak_tw: ["屎", "sɨ˧˩"],
    wuu_sz: ["屎", "sʮ˥˩"],
    wuu_wz: ["屎", "sɿ˧˥"],
    nan_qz: ["屎", "sai˥˥"],
    nan_hai: ["屎", "zai˨˩˧"],
    zh_wh: ["屎", "sz̩˦˨"],
    zh_zz: ["屎", "sz̩˥˥"],
    hak_hl: ["屎", "ʃɨ˨˦"],
    cpx: ["屎", "ɬai˦˥˧"],
    wuu_hz: ["屎", "ʂz̩˥˧"],
    yue_dg: ["屎", "si˧˥"],
    yue_nn: ["屎", "ɬi˧˥"],
    zh_cq: ["屎", "sz̩˦˨"],
    zh_jn: ["屎", "ʂz̩˥˥"],
    zh_km: ["屎", "sz̩˥˧"],
    zh_xa: ["屎", "ʂz̩˥˧"],
    nan_xm: ["屎", "sai˥˧"],
    nan_zz: ["屎", "sai˥˧"],
    wuu_jh: ["屎", "sz̩˥˧˥"],
    wuu_jx: ["屎", "sz̩˧˩˧"],
    yue_zs: ["屎", "si˧˥"],
    zh_cd: ["屎", "sz̩˥˧"],
    zh_hf: ["屎", "ʂz̩˨˦"],
    zh_kf: ["屎", "ʂz̩˥˧"],
    zh_nj: ["屎", "ʂz̩˨˩˨"],

    // --- Pluricentric rows — each reads its own row's vowel where one differs
    ar_sy: ["كاكا", "kaːka"],
    ar_lb: ["كاكا", "kaːka"],
    ar_jo: ["كاكا", "kaːka"],
    ar_ps: ["كاكا", "kaːka"],
    ar_ye: ["كاكا", "kaːka"],
    ar_sa: ["كاكا", "kaːka"],
    abv: ["كاكا", "kaːka"],
    afb: ["كاكا", "kaːka"],
    acw: ["كاكا", "kaːka"],
    ayl: ["كاكا", "kaːka"],
    arq: ["كاكا", "kaːka"],
  },
};