/**
 * Salt is a word that paid people. Proto-Indo-European *séh₂ls gives Latin sal, and from sal comes
 * salārium, the allowance Roman soldiers drew — which is why English still calls a wage a salary, and
 * why salad (salted greens), sauce and sausage are all the same root wearing different clothes. The
 * word itself is inherited right across the family: Greek háls, Old Irish salann, Old Church Slavonic
 * solь, Gothic salt, Armenian ał, Tocharian A sāle. Two neighbours stand out by not joining in —
 * Sanskrit uses lavaṇa, and Basque, which is not Indo-European at all, has gatz.
 *
 * East Asia is a separate world here: 鹽 and its simplification 盐 carry the Sinoxenic layer, while
 * Japanese しお and Korean 소금 are native words underneath it. Semitic has its own root again —
 * Arabic milḥ, Hebrew melaḥ — and Akkadian ṭābtu is literally 'the good thing'.
 */
WORDS.salt = {
  emoji: "🧂",
  label: {
    en: "Salt", ja: "塩", ko: "소금", zh: "盐", yue: "鹽", vi: "Muối", th: "เกลือ", id: "Garam",
    hi: "नमक", de: "Salz", fr: "Sel", it: "Sale", es: "Sal", es_eu: "Sal", es_mx: "Sal",
    pt: "Sal", pt_eu: "Sal", pt_br: "Sal", ru: "Соль", uk: "Сіль", ar: "ملح", he: "מלח",
    sw: "Chumvi",
  },
  definition: {
    en: "Salt — the mineral used to season and preserve food. The Latin word paid Roman soldiers, which is why a wage is still a salary.",
    ja: "塩 — 味つけと保存に使う鉱物。ラテン語の sal はローマ兵の給与でもあり、それが英語 salary（給料）の語源になった。",
    ko: "소금 — 음식을 간하고 저장하는 데 쓰는 광물. 라틴어 sal은 로마 병사의 급여이기도 했고, 그래서 영어 salary(봉급)가 나왔다.",
    zh: "盐 — 用来调味和保存食物的矿物。拉丁语 sal 曾是罗马士兵的军饷，英语的 salary（薪水）便由此而来。",
    yue: "鹽 — 用嚟調味同保存食物嘅礦物。拉丁文 sal 曾經係羅馬士兵嘅軍餉，英文 salary（薪水）就係咁嚟。",
    vi: "Muối — khoáng chất dùng để nêm và bảo quản thức ăn. Tiếng Latinh sal từng là tiền lương lính La Mã, nên tiếng Anh vẫn gọi lương là salary.",
    th: "เกลือ — แร่ที่ใช้ปรุงรสและถนอมอาหาร คำละติน sal เคยเป็นเบี้ยเลี้ยงของทหารโรมัน จึงกลายเป็นคำว่า salary ในภาษาอังกฤษ.",
    id: "Garam — mineral untuk membumbui dan mengawetkan makanan. Kata Latin sal dulu dibayarkan kepada prajurit Romawi, maka gaji dalam bahasa Inggris disebut salary.",
    hi: "नमक — भोजन में स्वाद और परिरक्षण के लिए प्रयुक्त खनिज। लातिनी sal रोमन सैनिकों का भत्ता था, इसीलिए अंग्रेज़ी में वेतन आज भी salary है।",
    de: "Salz — das Mineral zum Würzen und Haltbarmachen. Das lateinische sal bezahlte römische Soldaten — daher heißt ein Gehalt englisch noch immer salary.",
    fr: "Sel — le minéral qui assaisonne et conserve. Le latin sal payait les soldats romains : c'est de là que vient l'anglais salary, « salaire ».",
    it: "Sale — il minerale che insaporisce e conserva. Il latino sal pagava i soldati romani: da lì l'inglese salary, «stipendio».",
    es: "Sal — el mineral que sazona y conserva. El latín sal pagaba a los soldados romanos: de ahí el inglés salary, «salario».",
    es_eu: "Sal — el mineral que sazona y conserva. El latín sal pagaba a los soldados romanos: de ahí el inglés salary, «salario».",
    es_mx: "Sal — el mineral que sazona y conserva. El latín sal pagaba a los soldados romanos: de ahí el inglés salary, «salario».",
    pt: "Sal — o mineral que tempera e conserva. O latim sal pagava os soldados romanos: daí vem o inglês salary, «salário».",
    pt_eu: "Sal — o mineral que tempera e conserva. O latim sal pagava os soldados romanos: daí vem o inglês salary, «salário».",
    pt_br: "Sal — o mineral que tempera e conserva. O latim sal pagava os soldados romanos: daí vem o inglês salary, «salário».",
    ru: "Соль — минерал для приправы и сохранения пищи. Латинское sal шло на жалованье римским солдатам — отсюда английское salary.",
    uk: "Сіль — мінерал для приправи та збереження їжі. Латинське sal ішло на платню римським воякам — звідси англійське salary.",
    ar: "ملح — المعدن الذي يُنكَّه به الطعام ويُحفَظ. كانت الكلمة اللاتينية sal تُدفع للجنود الرومان، ومنها الإنجليزية salary أي الراتب.",
    he: "מלח — המינרל שמתבל ומשמר מזון. המילה הלטינית sal שימשה לתשלום לחיילים רומיים, ומכאן salary באנגלית.",
    sw: "Chumvi — madini yanayokoleza na kuhifadhi chakula. Neno la Kilatini sal lililipwa kwa askari wa Kirumi, ndiyo maana mshahara kwa Kiingereza ni salary.",
  },
  data: {
    // --- UI languages -------------------------------------------------
    en: ["salt", "sɔːlt"],
    ja: ["塩", "ɕio"],
    ko: ["소금", "soɡɯm"],
    zh: ["盐", "jɛn˧˥"],
    yue: ["鹽", "jiːm˨˩"],
    vi: ["muối", "muəj˧˥"],
    th: ["เกลือ", "klɯa˧"],
    id: ["garam", "ɡaram"],
    hi: ["नमक", "nəmək"],
    de: ["Salz", "zalts"],
    fr: ["sel", "sɛl"],
    it: ["sale", "ˈsale"],
    es: ["sal", "sal"],
    es_mx: ["sal", "sal"],
    pt: ["sal", "saɫ"],
    pt_br: ["sal", "saw"],
    ru: ["соль", "solʲ"],
    uk: ["сіль", "silʲ"],
    ar: ["ملح", "milħ"],
    he: ["מלח", "ˈmelaχ"],
    sw: ["chumvi", "tʃumvi"],

    // --- *séh₂ls, and the two neighbours that opted out ---------------
    p_ine: ["*séh₂ls", "séh₂ls"],
    la: ["sal", "sal"],
    el_grc: ["ἅλς", "háls"],
    el_kath: ["ἅλας", "ˈalas"],
    el: ["αλάτι", "aˈlati"],
    got: ["𐍃𐌰𐌻𐍄", "salt"],
    ang: ["sealt", "sæɑlt"],
    enm: ["salt", "salt"],
    ofs: ["salt", "salt"],
    osx: ["salt", "salt"],
    goh: ["salz", "salts"],
    gmh: ["salz", "salts"],
    non: ["salt", "salt"],
    cu: ["соль", "solɪ"],
    sga: ["salann", "ˈsalan"],
    mga: ["salann", "ˈsalan"],
    cy: ["halen", "ˈhalen"],
    hy_grab: ["աղ", "aɫ"],
    hy: ["աղ", "aʁ"],
    lt: ["druska", "ˈdruskɐ"],
    lv: ["sāls", "saːls"],
    sa: ["लवण", "lɐʋɐɳɐ"],
    h_vedic: ["लवण", "lɐʋɐɳɐ"],
    pi: ["लोण", "loɳa"],
    pi_edu: ["loṇa", "loɳa"],
    eu: ["gatz", "ɡats̻"],

    // --- Ancient Near East and Egypt ----------------------------------
    akk: ["ṭābtu", "tˤaːbtu"],
    psem: ["*milḥ-", "milħ"],
    hbo: ["מלח", "ˈmelaħ"],
    he_mis: ["מלח", "ˈmelaħ"],
    arc: ["ܡܠܚܐ", "melħaː"],
    ar_qur: ["ملح", "milħ"],
    gez: ["ጼው", "sˤeːw"],
    cop: ["ϩⲙⲟⲩ", "hmu"],
    ti: ["ጨው", "tʃʼɐw"],
    am: ["ጨው", "tʃʼɐw"],

    // --- East Asia: a separate world ------------------------------------
    zh_wenyan_edu: ["鹽", "jiːm˨˩"],
    vi_han: ["鹽", "iəm˧˧"],
    ja_edo: ["塩", "ɕio"],
    ko_em: ["소곰", "soɡom"],

    // --- Modern Europe --------------------------------------------------
    nl: ["zout", "zʌut"],
    af: ["sout", "səut"],
    sv: ["salt", "salt"],
    no: ["salt", "sɑlt"],
    nn: ["salt", "sɑlt"],
    da: ["salt", "salˀd"],
    is: ["salt", "salt"],
    fo: ["salt", "salt"],
    ga: ["salann", "ˈsˠalˠən̪ˠ"],
    gv: ["sollan", "ˈsolan"],
    br: ["holen", "ˈhoːlɛn"],
    kw: ["holan", "ˈhɔlan"],
    pl: ["sól", "sul"],
    cs: ["sůl", "suːl"],
    sk: ["soľ", "solʲ"],
    sl: ["sol", "soːl"],
    hr: ["sol", "sol"],
    sr: ["со", "so"],
    bs: ["so", "so"],
    bg: ["сол", "sɔl"],
    mk: ["сол", "sɔl"],
    be: ["соль", "solʲ"],
    ro: ["sare", "ˈsare"],
    ca: ["sal", "sal"],
    gl: ["sal", "sal"],
    oc: ["sau", "saw"],
    sq: ["kripë", "ˈkripə"],
    hu: ["só", "ʃoː"],
    fi: ["suola", "ˈsuola"],
    et: ["sool", "soːl"],
    ka: ["მარილი", "marili"],

    // --- Asia, Africa, Pacific -------------------------------------------
    fa: ["نمک", "næˈmæk"],
    tg: ["намак", "namak"],
    ps: ["مالګه", "maːlɡa"],
    ur: ["نمک", "nəmək"],
    bn: ["নুন", "nun"],
    mr: ["मीठ", "miːʈʰ"],
    gu: ["મીઠું", "miːʈʰũ"],
    pa: ["ਲੂਣ", "luːɳ"],
    ne: ["नुन", "nun"],
    si: ["ලුණු", "luɳu"],
    ta: ["உப்பு", "uppu"],
    te: ["ఉప్పు", "uppu"],
    ml: ["ഉപ്പ്", "uppɨ"],
    kn: ["ಉಪ್ಪು", "uppu"],
    my: ["ဆား", "sʰá"],
    km: ["អំបិល", "ʔɑmbəl"],
    lo: ["ເກືອ", "kɯa"],
    tr: ["tuz", "tuz"],
    az: ["duz", "duz"],
    kk: ["тұз", "tʊz"],
    ky: ["туз", "tuz"],
    uz: ["tuz", "tuz"],
    tt: ["тоз", "toz"],
    ug: ["تۇز", "tuz"],
    mn: ["давс", "davs"],
    ms: ["garam", "ɡaram"],
    tl: ["asin", "ʔaˈsin"],
    ceb: ["asin", "ʔaˈsin"],
    haw: ["paʻakai", "pɐʔɐˈkɐi"],
    mi: ["tote", "tote"],
    sm: ["masima", "masima"],
    ha: ["gishiri", "ɡiʃiri"],
    yo: ["iyọ̀", "ijɔ"],
    zu: ["usawoti", "usaˈwɔti"],
    xh: ["ityuwa", "iˈtjuwa"],
    so: ["cusbo", "ʕusbo"],
    mg: ["sira", "sirə"],

    // --- Romance, sal all the way down ----------------------------------
    es_ar: ["sal", "sal"],
    es_cl: ["sal", "sal"],
    es_co: ["sal", "sal"],
    es_cu: ["sal", "sal"],
    es_pe: ["sal", "sal"],
    es_ve: ["sal", "sal"],
    es_bo: ["sal", "sal"],
    es_py: ["sal", "sal"],
    es_uy: ["sal", "sal"],
    es_ec: ["sal", "sal"],
    es_gt: ["sal", "sal"],
    es_hn: ["sal", "sal"],
    es_sv: ["sal", "sal"],
    es_ni: ["sal", "sal"],
    es_cr: ["sal", "sal"],
    es_pa: ["sal", "sal"],
    es_pr: ["sal", "sal"],
    es_do: ["sal", "sal"],
    es_an: ["sal", "sal"],
    es_sgl: ["sal", "sal"],
    osp: ["sal", "sal"],
    lad: ["sal", "sal"],
    ast: ["sal", "sal"],
    ext: ["sal", "sal"],
    an: ["sal", "sal"],
    mwl: ["sal", "sal"],
    fax: ["sal", "sal"],
    ca_va: ["sal", "sal"],
    vec: ["sal", "sal"],
    pms: ["sal", "sal"],
    rm: ["sal", "sal"],
    pt_mo: ["sal", "sal"],
    pt_ao: ["sal", "sal"],
    pt_mz: ["sal", "sal"],
    pt_cv: ["sal", "saɫ"],
    fr_be: ["sel", "sɛl"],
    fr_ch: ["sel", "sɛl"],
    fr_lu: ["sel", "sɛl"],
    fr_qc: ["sel", "sɛl"],
    fr_af: ["sel", "sɛl"],
    fr_cm: ["sel", "sɛl"],
    fr_sn: ["sel", "sɛl"],
    fr_ci: ["sel", "sɛl"],
    fr_ht: ["sel", "sɛl"],
    fr_class: ["sel", "sɛl"],
    fro: ["sel", "sɛl"],
    it_dan: ["sale", "ˈsale"],
    nap: ["sale", "ˈsalə"],
    scn: ["sali", "ˈsali"],
    co: ["sale", "ˈsale"],
    sc: ["sale", "ˈsale"],
    lij: ["sâ", "saː"],
    fur: ["sâl", "saːl"],
    rup: ["sare", "ˈsare"],

    // --- Germanic — salt, Salz, zout, and the Scots vocalised l ---------
    en_us: ["salt", "sɔlt"],
    en_ca: ["salt", "sɑlt"],
    en_au: ["salt", "soːlt"],
    en_nz: ["salt", "sɔːlt"],
    en_za: ["salt", "sɔːlt"],
    en_ie: ["salt", "sɒlt"],
    en_sco: ["salt", "sɔlt"],
    en_wls: ["salt", "sɔːlt"],
    en_yk: ["salt", "sɔːlt"],
    en_ck: ["salt", "soːlt"],
    en_est: ["salt", "sɔːlt"],
    en_scouse: ["salt", "sɔːlt"],
    en_geordie: ["salt", "sɔːlt"],
    en_brum: ["salt", "sɔːlt"],
    en_manc: ["salt", "sɔːlt"],
    en_wc: ["salt", "sɔːlt"],
    en_south: ["salt", "sɔːlt"],
    en_app: ["salt", "sɔːlt"],
    en_aave: ["salt", "sɔːlt"],
    en_in: ["salt", "sɔːlt"],
    en_sg: ["salt", "sɔlt"],
    en_my: ["salt", "sɔlt"],
    en_ph: ["salt", "sɔlt"],
    en_ng: ["salt", "sɔlt"],
    en_ng2: ["salt", "sɔlt"],
    en_ke: ["salt", "sɔlt"],
    en_jam: ["salt", "sɑːlt"],
    sco: ["saut", "sɑːt"],
    de_at: ["Salz", "salts"],
    de_ch: ["Salz", "salts"],
    de_lu: ["Salz", "zalts"],
    de_lut: ["Saltz", "zalts"],
    gsw: ["Salz", "salts"],
    gsw_w: ["Salz", "salts"],
    wae: ["Salz", "salts"],
    swg: ["Salz", "salts"],
    ksh: ["Salz", "zalts"],
    pdc: ["Salz", "salts"],
    lb: ["Salz", "zalts"],
    nds: ["Solt", "zɔlt"],
    pdt: ["Solt", "zolt"],
    nl_be: ["zout", "zɔut"],
    li: ["zout", "zɔut"],
    fy: ["sâlt", "sɔːlt"],
    yi: ["זאַלץ", "zalts"],

    // --- Rest of Europe -------------------------------------------------
    rue: ["сіль", "silʲ"],
    szl: ["sōl", "sol"],
    ltg: ["sōls", "soːls"],
    sgs: ["druska", "druska"],
    hyw: ["աղ", "ɑʁ"],
    se: ["sálti", "ˈsaːlti"],
    vro: ["suul", "suːl"],
    krl: ["suola", "ˈsuola"],
    olo: ["suolu", "ˈsuolu"],
    fkv: ["suola", "ˈsuolɑ"],
    fit: ["suola", "ˈsuolɑ"],
    myv: ["сал", "sal"],
    mdf: ["сал", "sal"],
    kpv: ["сов", "sov"],
    koi: ["сов", "sov"],
    udm: ["сылал", "sɨlal"],
    mhr: ["шинчал", "ʃintʃal"],
    mrj: ["санзал", "sanzal"],

    // --- Caucasus -------------------------------------------------------
    ce: ["туьха", "tyxa"],
    av: ["цӏам", "tsʼam"],
    lez: ["кьел", "qʼel"],
    ady: ["щыгъу", "ɕəʁʷ"],
    kbd: ["шыгъу", "ʃəʁʷ"],
    os: ["цӕхх", "tsæxː"],

    // --- Turkic — tuz/duz, and Chuvash going its own way ----------------
    gag: ["tuz", "tuz"],
    crh: ["tuz", "tuz"],
    kum: ["туз", "tuz"],
    nog: ["туз", "tuz"],
    krc: ["туз", "tuz"],
    cjs: ["тус", "tus"],
    kjh: ["тус", "tus"],
    alt: ["тус", "tus"],
    tyv: ["дус", "dus"],
    sah: ["туус", "tuːs"],
    dlg: ["туус", "tuːs"],
    ba: ["тоҙ", "toð"],
    tk: ["duz", "duz"],
    kaa: ["duz", "duz"],
    qxq: ["duz", "duz"],
    azb: ["دوز", "duz"],
    ota: ["طوز", "tuz"],
    xqa: ["tuz", "tuz"],
    otk: ["𐱃𐰆𐰕", "tuz"],
    cv: ["тӑвар", "təvar"],

    // --- Mongolic -------------------------------------------------------
    bxr: ["дабһан", "dabhan"],
    xal: ["давсн", "davsn"],
    mn_cn: ["ᠳᠠᠪᠤᠰᠤ", "dabusu"],
    cmg: ["ᠳᠠᠪᠤᠰᠤᠨ", "dabusun"],
    xng: ["ᠳᠠᠪᠤᠰᠤᠨ", "dabusun"],

    // --- Korean and Japanese, including Okinawan māsu -------------------
    ko_kp: ["소금", "soɡɯm"],
    ko_bus: ["소금", "soɡɯm"],
    ko_yb: ["소금", "soɡɯm"],
    ko_hg: ["소금", "soɡɯm"],
    ko_jl: ["소금", "soɡɯm"],
    ko_jeju: ["소금", "soɡɯm"],
    ja_osa: ["塩", "ɕio"],
    ja_kyo: ["塩", "ɕio"],
    ja_hir: ["塩", "ɕio"],
    ja_hak: ["塩", "ɕio"],
    ja_aom: ["塩", "ɕio"],
    ja_sd: ["塩", "ɕio"],
    ja_kg: ["塩", "ɕio"],
    ja_kanbun: ["塩", "ɕio"],
    ja_chu: ["塩", "ɕiwo"],
    ja_heian: ["塩", "siwo"],
    ojp: ["塩", "sipo"],
    ja_oki: ["マース", "maːsu"],

    // --- Sinitic — 鹽 is 陽平 everywhere -------------------------------
    zh_tw: ["鹽", "jɛn˧˥"],
    zh_db: ["盐", "jɛn˧˥"],
    zh_tj: ["盐", "jɛn˦˥"],
    zh_sc: ["盐", "jɛn˨˩"],
    zh_cd: ["盐", "jɛn˨˩"],
    zh_cq: ["盐", "jɛn˨˩"],
    zh_wh: ["盐", "jɛn˨˩˧"],
    zh_zz: ["盐", "jɛn˦˨"],
    zh_kf: ["盐", "jɛn˦˨"],
    zh_jn: ["盐", "jã˦˨"],
    zh_km: ["盐", "jã˧˩"],
    zh_xa: ["盐", "jã˨˦"],
    cjy: ["盐", "jæ̃˩˩"],
    cjy_lv: ["盐", "jæ̃˩˩"],
    cjy_xz: ["盐", "jæ̃˩˩"],
    hsn: ["盐", "jɛn˩˧"],
    hsn_hy: ["盐", "jɛn˩˧"],
    hsn_yz: ["盐", "jɛn˩˧"],
    gan: ["盐", "jɛn˨˦"],
    gan_ja: ["盐", "jɛn˦˥"],
    gan_fz: ["盐", "jɛn˦˥"],
    gan_yc: ["盐", "jɛn˥"],
    wuu: ["盐", "ɦi˨˧"],
    wuu_nb: ["盐", "ɦi˨˨˧"],
    wuu_wz: ["盐", "ɦi˧˩"],
    yue_gz: ["盐", "jiːm˨˩"],
    yue_dg: ["盐", "jiːm˨˩"],
    yue_nn: ["盐", "jiːm˨˩"],
    yue_zs: ["鹽", "jiːm˨˩"],
    yue_ts: ["盐", "jiam˨˨"],
    cnp: ["盐", "jiːm˨˩"],
    nan: ["鹽", "iam˨˦"],
    nan_xm: ["鹽", "iam˨˦"],
    nan_zz: ["鹽", "iam˩˧"],
    nan_qz: ["鹽", "iam˨˦"],
    nan_pn: ["鹽", "iam˨˦"],
    nan_te: ["盐", "iam˥˥"],
    nan_hai: ["盐", "iam˨˩"],
    hak_cn: ["盐", "iam˩˩"],
    hak_tw: ["鹽", "iam˩˩"],
    hak_hl: ["鹽", "iam˥˥"],

    // --- Tibetic and neighbours ------------------------------------------
    bo: ["ཚྭ", "tsʰa˥"],
    xct: ["ཚྭ", "tsʰwa"],
    xct_litpr: ["ཚྭ", "tsʰwa"],
    dz: ["ཚྭ", "tsʰa"],
    xsr: ["ཚྭ", "tsʰa"],
    sip: ["ཚྭ", "tsʰa"],
    lbj: ["ཚྭ", "tsʰa"],
    bft: ["ཚྭ", "tsʰa"],
    khg: ["ཚྭ", "tsʰa"],
    adx: ["ཚྭ་", "tsʰa"],
    lhm: ["ཚྭ་", "tsʰa˥"],
    rki: ["ဆား", "sʰá"],
    lus: ["chi", "tʃi"],
    cnh: ["chi", "tʃi"],
    mni: ["ꯊꯨꯝ", "tʰum"],

    // --- Arabic, Aramaic, Berber ------------------------------------------
    ar_lev: ["ملح", "milħ"],
    ar_sy: ["ملح", "milħ"],
    ar_lb: ["ملح", "milħ"],
    ar_jo: ["ملح", "milħ"],
    ar_ps: ["ملح", "milħ"],
    ar_sa: ["ملح", "milħ"],
    ar_ye: ["ملح", "milħ"],
    ar_gulf: ["ملح", "milħ"],
    afb: ["ملح", "milħ"],
    abv: ["ملح", "milħ"],
    acw: ["ملح", "milħ"],
    ar_sd: ["ملح", "milħ"],
    ar_iq: ["ملح", "miliħ"],
    ar_eg: ["ملح", "malħ"],
    ar_ma: ["ملح", "məlħ"],
    arq: ["ملح", "məlħ"],
    ar_tn: ["ملح", "məlħ"],
    ayl: ["ملح", "məlħ"],
    mey: ["ملح", "məlħ"],
    mt: ["melħ", "mɛlħ"],
    syc: ["ܡܠܚܐ", "melħaː"],
    aii: ["ܡܠܚܐ", "ˈmilxa"],
    tru: ["ܡܠܚܐ", "melħo"],
    oar: ["מלח", "melaħ"],
    tig: ["ጨው", "tʃʼəw"],
    kab: ["tisent", "tisənt"],
    shy: ["tisent", "tisənt"],
    shi: ["ⵜⵉⵙⵏⵜ", "tisənt"],
    tzm: ["ⵜⵉⵙⵏⵜ", "tisənt"],
    zgh: ["ⵜⵉⵙⵏⵜ", "tisənt"],
    rif: ["ⵜⵉⵙⵏⵜ", "θisənθ"],

    // --- Iranian ----------------------------------------------------------
    prs: ["نمک", "namak"],
    fa_clas: ["نمک", "namak"],
    haz: ["نمک", "namak"],
    ku: ["xwê", "xweː"],
    ckb: ["خوێ", "xweː"],

    // --- Indo-Aryan — lavaṇa splits into lūṇ and nūn ---------------------
    sa_edu: ["लवणम्", "lɐʋɐɳɐm"],
    pmh: ["लोण", "loɳa"],
    xto: ["𑀲𑀸𑀮𑁂", "saːle"],
    sd: ["لوڻ", "luːɳu"],
    pnb: ["لوݨ", "luːɳ"],
    skr: ["لوݨ", "luːɳ"],
    hno: ["لون", "luːɳ"],
    ks: ["نون", "nuːn"],
    dv: ["ލޮނު", "lonu"],
    as: ["নিমখ", "nimɔkʰ"],
    or: ["ଲୁଣ", "luɳɔ"],
    syl: ["লুন", "lun"],
    rkt: ["নুন", "nun"],
    bpy: ["নুন", "nun"],
    bho: ["नून", "nuːn"],
    mai: ["नून", "nuːn"],
    awa: ["नून", "nuːn"],
    mag: ["नून", "nuːn"],
    hne: ["नून", "nuːn"],
    anp: ["नून", "nuːn"],
    thr: ["नून", "nuːn"],
    dty: ["नुन", "nun"],
    mwr: ["लूण", "luːɳ"],
    bgc: ["लूण", "luːɳ"],
    bgq: ["लूण", "luːɳ"],
    doi: ["लूण", "luːɳ"],
    xnr: ["लूण", "luːɳ"],
    kok: ["मीठ", "miːʈʰ"],
    rom: ["lon", "lon"],
    rmy: ["lon", "lon"],
    hif: ["namak", "nəmək"],
    hns: ["namak", "nəmək"],

    // --- Mainland Southeast Asia ------------------------------------------
    vi_s: ["muối", "muəj˧˥"],
    sukh: ["เกลือ", "klɯa"],
    kxm: ["អំបិល", "ʔəmbəl"],
    sat: ["ᱵᱩᱞᱩᱝ", "buluŋ"],
    unr: ["bulung", "buluŋ"],
    hoc: ["bulung", "buluŋ"],
    tcy: ["ಉಪ್ಪು", "uppu"],

    // --- Austronesian — uyah, garam, asin, masima -------------------------
    jv: ["uyah", "ujah"],
    jvn: ["uyah", "ujah"],
    su: ["uyah", "ujah"],
    osn: ["uyah", "ujah"],
    ban: ["uyah", "ujah"],
    bjn: ["uyah", "ujah"],
    kaw: ["ꦈꦪꦃ", "ujah"],
    min: ["garam", "ɡaram"],
    omy: ["garam", "ɡaram"],
    abs: ["garam", "ɡaram"],
    max: ["garam", "ɡaram"],
    mui: ["garam", "ɡaram"],
    pmy: ["garam", "ɡaram"],
    iba: ["garam", "ɡaram"],
    bew: ["garem", "ɡarəm"],
    ace: ["sira", "sira"],
    bbc: ["sira", "sira"],
    bts: ["sira", "sira"],
    akb: ["sira", "sira"],
    ilo: ["asin", "ʔaˈsin"],
    hil: ["asin", "ʔaˈsin"],
    war: ["asin", "ʔaˈsin"],
    bik: ["asin", "ʔaˈsin"],
    bto: ["asin", "aˈsin"],
    pam: ["asin", "ʔaˈsin"],
    pag: ["asin", "ʔaˈsin"],
    tsg: ["asin", "asin"],
    h_tagalog: ["ᜀᜐᜒᜈ᜔", "aˈsin"],
    ch: ["asiga", "aˈsiɡa"],
    tet: ["masin", "ˈmasin"],
    fj: ["masima", "ˈmasima"],
    to: ["māsima", "ˈmaːsima"],
    niu: ["masima", "ˈmasima"],
    tvl: ["masima", "ˈmasima"],
    tkl: ["masima", "masima"],
    wls: ["māsima", "maːsima"],
    fud: ["masima", "masima"],

    // --- Africa — kɔgɔ, munyu, letswai ------------------------------------
    ig: ["nnu", "nːu"],
    ak: ["nkyene", "ntɕene"],
    ee: ["dze", "dze"],
    gej: ["dze", "dze"],
    bm: ["kɔgɔ", "kɔɡɔ"],
    dyu: ["kɔgɔ", "kɔɡɔ"],
    emk: ["kɔgɔ", "kɔɡɔ"],
    mlq: ["kɔgɔ", "kɔɡɔ"],
    mwk: ["kɔgɔ", "kɔɡɔ"],
    kao: ["kɔgɔ", "kɔɡɔ"],
    wo: ["xorom", "xorom"],
    rn: ["umunyu", "umuɲu"],
    lg: ["omunnyo", "omuɲːo"],
    nyn: ["omunyu", "omuɲu"],
    cgg: ["omunyu", "omuɲu"],
    ttj: ["omunyu", "omuɲu"],
    nyo: ["omunyu", "omuɲu"],
    ts: ["munyu", "muɲu"],
    mxc: ["munyu", "muɲu"],
    ndc: ["munyu", "muɲu"],
    tn: ["letswai", "letswai"],
    st: ["letswai", "letswai"],
    nso: ["letswai", "letswai"],
    ssw: ["lusawoti", "lusawoti"],
    ln: ["mongwa", "moŋɡwa"],
    kg: ["mungwa", "muŋɡwa"],
    tum: ["mchere", "mtʃere"],

    // --- The Americas ------------------------------------------------------
    qu: ["kachi", "ˈkatʃi"],
    quz: ["kachi", "ˈkatʃi"],
    quy: ["kachi", "ˈkatʃi"],
    qwc: ["kachi", "katʃi"],
    ay: ["jayu", "ˈhaju"],
    gn: ["juky", "dʒuˈkɨ"],
    nci: ["iztatl", "istatɬ"],
    nch: ["istatl", "istatɬ"],
    nhw: ["istatl", "istatɬ"],
    nhe: ["istatl", "istatɬ"],
    ngu: ["istatl", "istatɬ"],
    ppl: ["istat", "istat"],
    quc: ["atzʼam", "atsʼam"],
    cak: ["atzʼam", "atsʼam"],
    kek: ["atzʼam", "atsʼam"],
    oj: ["zhiiwitaagan", "ʒiːwitaːɡan"],

    // --- Creoles ------------------------------------------------------------
    ht: ["sèl", "sɛl"],
    gcf: ["sèl", "sɛl"],
    gcr: ["sèl", "sɛl"],
    acf: ["sèl", "sɛl"],
    mfe: ["disel", "disel"],
    crs: ["disel", "disel"],
    pap: ["salu", "salu"],
    kea: ["sal", "sal"],
    cbk: ["sal", "sal"],
    pt_gw: ["sal", "sal"],
    jam: ["salt", "saːlt"],
    bah: ["salt", "sɑːlt"],
    bzj: ["salt", "sɑːlt"],
    hwc: ["salt", "sɑlt"],
    pcm: ["salt", "sɔlt"],
    kri: ["sɔlt", "sɔlt"],
    tpi: ["sol", "sol"],
    pis: ["sol", "sol"],
    bi: ["sol", "sol"],
    srn: ["sowtu", "sowtu"],
    djk: ["sowtu", "sowtu"],

    // --- Isolate ------------------------------------------------------------
    ain: ["シッポ", "ʃippo"],
    vi_nom: ["圤", "muəj˧˥"],

    // --- Sinitic: 鹽 is 陽平 — tone taken from each row's own 鱼 ---------
    zh_nj: ["盐", "iɛn˨˦"],
    zh_hf: ["盐", "iĩ˥˥"],
    zh_jh: ["盐", "iɛn˧˥"],
    cdo: ["盐", "sieŋ˥˧"],
    mnp: ["盐", "iŋ˧˧"],
    cpx: ["盐", "iɛŋ˩˧"],
    wuu_sz: ["盐", "ɦiɪ˨˨˧"],
    wuu_hz: ["盐", "ɦiẽ˨˩˧"],
    dng: ["ян", "jan˨˦"],
    och: ["鹽", "*[ɢr][o]m"],
    zh_tang: ["鹽", "jiᴇm"],
    p_sit: ["*g-rjum", "g-rjum"],


    // --- Tibeto-Burman: PTB *g-ryum in the Sal branch, *tsa in Qiangic and Lolo ---
    kac: ["jum", "tʃum˧˩"],
    lif: ["ᤕᤢᤶ", "jum"],
    ii: ["ꋂ", "tsʰɯ˧˧"],
    yiz: ["tsʰo", "tsʰo˨˩"],
    hni: ["caqdevq", "tsʰa˧˩dɤ˧˩"],
    lhu: ["á-lɛ̀", "álɛ̀"],
    lis: ["tsha-bo", "tsʰɑ˧˩bo˧˧"],
    nxq: ["ce", "tsʰe˧˧"],
    tji: ["lapu", "la˧˥pu˥˥"],
    qxs: ["tshɿ", "tsʰɿ"],
    ers: ["tshɿ", "tsʰɿ"],
    cng: ["tshə", "tsʰə"],
    duu: ["svla", "sɯlaʔ"],
    new: ["चि", "tʃi"],


    // --- Reconstructed, ancient and constructed ----------------------
    p_jpn: ["*sipo", "sipo"],
    p_ryu: ["*masio", "masio"],
    ja_mvi: ["真塩", "maːsuː"],
    ja_rys: ["真塩", "maːsu"],
    ko_mid: ["소곰", "sokom"],
    ko_gor: ["蘇甘", "*swokwom"],
    ptrk: ["*tūŕ", "tūŕ"],
    pmng: ["*dabusun", "dabusun"],
    p_dra: ["*cuppu", "cuppu"],
    sux: ["𒁵", "mun"],
    txb: ["𑀲𑀮𑁆𑀬𑀺𑀬𑁂", "saʎije"],
    pal: ["𐭭𐭬𐭪", "namak"],
    eo: ["salo", "ˈsalo"],
    vo: ["sal", "sal"],
    io: ["salo", "ˈsalo"],
    ia: ["sal", "sal"],
    ie: ["sale", "ˈsale"],
    jbo: ["silna", "ˈsilna"],


    // --- North Eurasia: Turkic *tūŕ, Mongolic *dabusun, and Russian соль all over Siberia ---
    slr: ["duz", "duz"],
    ybe: ["duz", "duz"],
    sce: ["dansun", "dansun"],
    mjg: ["dabusi", "dabusɿ"],
    mnc: ["ᡩᠠᠪᠰᡠᠨ", "dabsun"],
    evn: ["турукэ̄", "turukeː"],
    eve: ["так", "tak"],
    gld: ["даосон", "daoson"],
    yrk: ["сэрˮ", "serʔ"],
    enf: ["syr", "sɨr"],
    sel: ["щяӈ", "ɕæŋ"],
    kca: ["соӆ", "soɬ"],
    ckt: ["чоԓ", "tʃoɬ"],
    itl: ["сољ", "solʲ"],
    ykg: ["суоль", "suolʲ"],
    niv: ["тафть", "taftʲ"],
    ket: ["тъʼ", "təʔ"],
    vep: ["sol", "sol"],
    vot: ["soolõ", "ˈsoːlɤ"],
    liv: ["sūoļ", "suoːlʲ"],
    sma: ["saelhtie", "saelʰtie"],
    smj: ["sállte", "ˈsaːltɛ"],
    smn: ["sältti", "ˈsæltːi"],
    sms: ["säʹltt", "sælʲtː"],
    sjd: ["сӯлль", "suːʎː"],
    mns: ["солвал", "solwal"],
    inh: ["тух", "tux"],
    dar: ["зе", "ze"],
    agx: ["кьаьл", "qʼæl"],
    ddo: ["цийо", "tsijo"],
    tab: ["кьил", "qʼil"],
    udi: ["ел", "jel"],
    tkr: ["кьев", "qʼev"],
    ani: ["цӏцӏон", "tsʼːon"],
    bdk: ["кьел", "qʼel"],
    huz: ["цаᴴ", "tsã"],
    khv: ["цийо", "tsijo"],
    kjj: ["кьаь", "kʲʼæ"],
    rut: ["кьел", "qʼel"],
    ab: ["аџьыка", "adʑəka"],
    abq: ["джькӏа", "dʑkʼa"],
    xmf: ["ჯიმუ", "dʒimu"],
    sva: ["ჯიმ", "dʒim"],
    lzz: ["მცუმუ", "mtsumu"],
    srm: ["sátu", "sátu"],
    kfa: ["ಉಪ್ಪ್", "uppɨ"],


    // --- Indo-European margins: sal / solь / salt, and namak where Indo-Iranian opted out ---
    en_em: ["salt", "salt"],
    frr: ["sålt", "sɔlt"],
    frr_amr: ["saalt", "saːlt"],
    bar: ["Soiz", "sɔɪts"],
    gd: ["salann", "ˈsaɫən"],
    rgn: ["sêl", "seːl"],
    frp: ["sal", "sal"],
    lmo: ["sal", "sal"],
    lij_t: ["sâ", "saː"],
    wa: ["sé", "se"],
    nrf: ["sé", "se"],
    fra_jer: ["sé", "se"],
    nrf_gg: ["saïl", "sajl"],
    hsb: ["sól", "sʊl"],
    dsb: ["sol", "sɔl"],
    csb: ["sòl", "swɛl"],
    orv: ["соль", "solĭ"],
    zza: ["sol", "sol"],
    tly: ["nemek", "nemek"],
    bal: ["واد", "waːd"],
    jpr: ["נמך", "næmæk"],
    rhg: ["nun", "nun"],
    bsk: ["bayú", "baˈjuː"],
    mad: ["buja", "budʒa"],


    // --- Austroasiatic *ɓɔːh, Tai *klwɯə, Hmong-Mien *ntsjəuX — almost no borrowing ---
    prk: ["kih", "kih"],
    wbm: ["kih", "kih"],
    lwl: ["kih", "kih"],
    kdt: ["phɑ̤ːh", "pʰɑːh"],
    srb: ["basid", "bəsɨd"],
    kjg: ["hmaar", "ʰmaːr"],
    kha: ["ka mluh", "ka mluʔ"],
    mra: ["chuʌk", "tʃuʌk"],
    mnw: ["ၜဵု", "ɓɜ"],
    bru: ["boi", "ɓɔːj"],
    bdq: ["boh", "ɓɔh"],
    mtq: ["bỏi", "ɓɔːj"],
    vi_c: ["muối", "muəj˧˥"],
    p_aav: ["*ɓɔːh", "ɓɔːh"],
    soa: ["เกลือ", "kɯa˧"],
    th_isan: ["เกือ", "kɯa˥"],
    th_n: ["เกื๋อ", "kɯa˩˧"],
    th_s: ["เกลือ", "klɯa˥"],
    za: ["gyu", "kju˨˦"],
    shn: ["ၵိူဝ်", "kɤː˨˦"],
    khb: ["ᦵᦂᦲ", "kɤː˥"],
    blt: ["ꪹꪀ", "kɯa˨˦"],
    tyz: ["cưa", "kɯə˧˧"],
    nut: ["cưa", "kɯə˧˧"],
    ptai: ["*klwɯə", "klwɯə"],
    hmn: ["ntsev", "ntse˨˦"],
    ium: ["nzauv", "dzau˧˩"],
    p_hmx: ["*ntsjəuX", "ntsjəu"],


    // --- New Guinea trade salt, and the Australian loans that replaced it ---
    kmh: ["pi", "pi"],
    enq: ["aipi", "aipi"],
    hui: ["ibi", "ibi"],
    mpt: ["yal", "jal"],
    fai: ["yol", "jol"],
    roo: ["avaka", "aβaka"],
    kpf: ["sii", "siː"],
    kmu: ["sole", "sole"],
    aau: ["sol", "sol"],
    yle: ["ntii", "ntiː"],
    mkz: ["asi", "ˈasi"],
    tcs: ["solt", "solt"],
    pjt: ["tjaltu", "caltu"],
    wbp: ["jarlti", "caɭti"],
    piu: ["paṉṯu", "paɳʈu"],
    aer: ["apirnte", "apiɳʈə"],
    mpj: ["juulu", "cuːlu"],
    djr: ["dje'la", "ɟeʔla"],
    nys: ["djallam", "dʒalam"],


    // --- Himalayan and Gheg additions --------------------------------
    brx: ["संख्रि", "sɯŋkʰri"],
    lep: ["ᰟᰩᰮ", "vom"],
    aln: ["krypë", "kryp"],


    // --- Nilotic, Cushitic and Omotic: native words, Bantu loans, Arabic milḥ on the coast ---
    din: ["awai", "awai"],
    luo: ["chumbi", "tʃumbi"],
    ach: ["kado", "kado"],
    laj: ["kado", "kado"],
    mas: ["ɛmunyan", "ɛmuɲan"],
    saq: ["nkisiicho", "ŋkisiːtʃo"],
    kln: ["munyek", "muɲek"],
    teo: ["abalang", "abalaŋ"],
    bfa: ["alang", "alaŋ"],
    om: ["soogidda", "soːɡidːa"],
    wal: ["maxiniyaa", "matʼinijaː"],
    sid: ["maxine", "matʼine"],
    drs: ["maxine", "matʼine"],
    kxc: ["sookitta", "soːkitːa"],
    aa: ["asbo", "asbo"],
    ssy: ["milxo", "milħo"],
    fia: ["imiid", "imiːd"],


    // --- Caucasian Albanian and Umbrian ------------------------------
    xag: ["el", "el"],
    xum: ["salu", "ˈsa.lu"],


    // --- Mesoamerica and South America: pM *aʔtzʼaam, Tupi *ĵukɨr, and the Iberian sal inland ---
    yua: ["taʼab", "taʔaɓ"],
    itz: ["tab", "tab"],
    usp: ["atzʼam", "atsʼam"],
    tzo: ["atsʼam", "atsʼam"],
    tzh: ["atsʼam", "atsʼam"],
    poh: ["atzʼaam", "atsʼaːm"],
    kjb: ["atzʼam", "atsʼam"],
    ctu: ["atsʼam", "atsʼam"],
    toj: ["atsʼam", "atsʼam"],
    chf: ["atzʼam", "atsʼam"],
    agu: ["aatzʼum", "aːtsʼum"],
    ixl: ["atzʼam", "atsʼam"],
    mam: ["atzʼan", "atsʼan"],
    mixtec: ["ñii", "ɲiː"],
    mxv: ["ñii", "ɲiː"],
    zap: ["zidi", "zidi"],
    maz: ["õʼõ", "õʔõ"],
    ote: ["u", "u"],
    otq: ["u", "u"],
    toc: ["mátzat", "mátsat"],
    huv: ["kiniük", "kiniɨk"],
    gym: ["mren", "mɾen"],
    bzd: ["dayë", "dajə"],
    cuk: ["balu", "palu"],
    chb: ["nygua", "nɨɡua"],
    cni: ["tivi", "tiβi"],
    ame: ["pos", "pos"],
    cab: ["sálu", "ˈsalu"],
    guc: ["ichii", "itʃiː"],
    ter: ["yúki", "ˈjuki"],
    trn: ["ʼchewe", "ʔtʃewe"],
    car: ["wajo", "wajo"],
    ake: ["waiyo", "waijo"],
    mch: ["sayu", "saju"],
    mbc: ["pan", "pan"],
    shp: ["tashi", "taʃi"],
    mcf: ["sa", "sa"],
    tca: ["yucüra", "jukɨɾa"],
    pbb: ["nega", "neɡa"],
    jiv: ["wee", "weː"],
    agr: ["wee", "wɨː"],
    acu: ["wee", "weː"],
    gum: ["tre", "tɾe"],
    emp: ["tã", "tã"],
    arn: ["chadi", "tʃaði"],
    xav: ["sa", "sa"],
    kgp: ["sa", "sa"],
    kpj: ["dʒɨra", "dʒɨra"],
    tob: ["towe", "towe"],
    plg: ["qaaʔnowa", "qaaʔnowa"],
    moc: ["ʔwe", "ʔwe"],
    mzh: ["nisuy", "nisuj"],
    cag: ["naʔpkutax", "naʔpkutax"],
    crt: ["sifʷoniʔ", "sifʷoniʔ"],
    tue: ["móã", "mõã"],
    jup: ["bʼǒh", "bʼǒh"],
    guu: ["saju", "saju"],
    gun: ["juky", "ʒuˈkɨ"],
    yrl: ["yukira", "jukiɾa"],
    tpn: ["îukyra", "juˈkɨɾa"],


    // --- Bantu: *-nyʊ̀, *-céde, *-ngùa, *-cééyà — and almost no European loan ---
    zdj: ["shingo", "ʃiŋɡo"],
    swb: ["shingo", "ʃiŋɡo"],
    rw: ["umunyu", "umuɲu"],
    sn: ["munyu", "muɲu"],
    ny: ["mchere", "mtʃere"],
    yao: ["njete", "ndʒete"],
    ki: ["cumbĩ", "tʃumbi"],
    kam: ["mũnyũ", "muɲu"],
    ve: ["muṋo", "mun̪o"],
    kqn: ["mukele", "mukele"],
    lua: ["luepu", "luepu"],
    lol: ["bokwá", "bokwá"],
    tll: ["leho", "leho"],
    nbl: ["itswayi", "itswaji"],
    nd: ["itswayi", "itswaji"],
    fan: ["nku", "ŋku"],
    ewo: ["nku", "ŋku"],
    bum: ["nku", "ŋku"],
    umb: ["omongwa", "omoŋɡwa"],
    kmb: ["mungua", "muŋɡwa"],
    her: ["omongua", "omoŋɡua"],
    loz: ["lizwai", "lizwai"],
    kde: ["munyu", "muɲu"],
    seh: ["munyu", "muɲu"],
    sg: ["îngö", "iŋɡɔ"],


    // --- Austronesian: PAN *qasiRa and *timuq, with English salt across Micronesia ---
    ami: ["cilah", "tsilah"],
    pwn: ["qatia", "qatia"],
    tay: ["cimu'", "tsimuʔ"],
    bnn: ["hasila", "hasila"],
    trv: ["cimu", "tsimu"],
    tsu: ["sieu", "sieu"],
    tao: ["asin", "asin"],
    pyu: ["iyam", "ijam"],
    szy: ["cikah", "tsikah"],
    ssf: ["qtilha", "qtiɬa"],
    dru: ["timu", "ˈtimu"],
    ckv: ["zemiyan", "zəmijan"],
    bzg: ["sassi", "sasi"],
    agt: ["asin", "ʔaˈsin"],
    mrw: ["asin", "asin"],
    mdh: ["timus", "ˈtimus"],
    gor: ["watingo", "waˈtiŋo"],
    mak: ["ce'la", "ˈtʃeʔla"],
    bug: ["pejje", "pədʒːe"],
    sda: ["sia", "sia"],
    nij: ["uyah", "ujah"],
    ljp: ["uyah", "ujah"],
    sas: ["sie", "siə"],
    gay: ["poa", "poa"],
    dtp: ["tusi", "tusi"],
    dtp_kzj: ["tusi", "tusi"],
    aoz: ["masiʼ", "masiʔ"],
    rtm: ["masi", "masi"],
    pau: ["sar", "sar"],
    meu: ["damena", "damena"],
    ho: ["damena", "damena"],
    emi: ["uela", "uela"],
    bzh: ["mamireng", "mamireŋ"],
    woe: ["gasiigaa", "ɡasiːɡaː"],
    yap: ["sool", "soːl"],
    chk: ["sóón", "səːn"],
    pon: ["soahl", "sɔːl"],
    kos: ["sohl", "sɔl"],
    mh: ["jọọḷ", "tʲɒːlˠ"],
    gil: ["taoro", "taoro"],
    ty: ["miti", "miti"],
    rap: ["miti", "miti"],
    rar: ["miti", "miti"],
    pkp: ["miti", "ˈmiti"],
    paus: ["*qasiRa", "qasiRa"],
    pmay: ["*ʔaʔtzʼaam", "ʔaʔtsʼaːm"],
    pban: ["*-jínyʊ̀", "-jíɲʊ̀"],
    puaz: ["*ona", "ona"],


    // --- Zaiwa -------------------------------------------------------
    atb: ["xo", "tsʰo˥˥"],


    // --- Kuvi and Nagamese -------------------------------------------
    kxv: ["hāru", "haːru"],
    nag: ["nimok", "nimok"],


    // --- West Africa: Mande *kɔ, Chadic ɬugwul, and Kanuri manda along the trade routes ---
    bin: ["umwẹn", "uw̃ɛ̃"],
    tiv: ["bar", "baɾ"],
    efi: ["inuñ", "inuŋ"],
    ekp: ["ada", "ada"],
    izz: ["unu", "unu"],
    ibb: ["inụñ", "inʌŋ"],
    urh: ["ughwaka", "uɣʷaka"],
    deg: ["ubuon", "ubuon"],
    ff: ["lamɗam", "lamɗam"],
    snk: ["sappe", "sapːe"],
    bsq: ["tɔ̃", "tɔ̃"],
    gaa: ["ŋo", "ŋo"],
    mnk: ["koo", "koː"],
    vai: ["ꖏ", "kɔ"],
    tem: ["mɛr", "mɛr"],
    spp: ["suumpe", "suːmpe"],
    sus: ["fɔxɛ", "fɔxɛ"],
    kbp: ["ɖɔm", "ɖɔm"],
    xed: ["hlùghúl", "ɬùɣúl"],
    dbq: ["mandà", "mandà"],
    tmh: ["ⵜⵉⵙⵎⵜ", "tesəmt"],
    kr: ["manda", "manda"],
    ses: ["ciiri", "tʃiːri"],
    dje: ["ciri", "tʃiri"],
    rcf: ["dosèl", "dosɛl"],
    mos: ["yamsem", "jamsem"],
    dag: ["yalim", "jalim"],
    fon: ["jɛ̀", "dʒɛ̀"],


    // --- Bororo and Hote ---------------------------------------------
    bor: ["sal", "sal"],
    hot: ["ŋgwêk", "ŋɡwɛk"],


    // --- North America: Algonquian *šiwitakan, Siouan 'sweet water', French sel in the north-east ---
    bla: ["isttsiksipoko", "istːsiksipoko"],
    hop: ["öönga", "ʔøːŋa"],
    win: ["nįįsgú", "nĩːsˈɡu"],
    cro: ["awaxóosa", "awaχoːsa"],
    hai: ["tang", "taŋ"],
    cic: ["hapi'", "hapiʔ"],
    ik: ["taġiuq", "taʁiuq"],
    nez: ["ketuenes", "ketuenes"],
    cay: ["ojikeʼdaʼ", "odʒikeʔdaʔ"],
    moh: ["tyohyòtsis", "tjohjotsis"],
    chr: ["ᎠᎹ", "aːmã"],
    cho: ["hapi", "hapi"],
    mus: ["okcvnwv", "oktʃənwə"],
    nv: ["áshįįh", "ʔáʃĩːh"],
    apw: ["ishįįh", "ʔiʃĩːh"],
    crx: ["lisel", "lisel"],
    squ: ["tl'álhem", "tɬʼaɬəm"],
    thp: ["c̓ált", "tsʼalt"],
    kwk: ["da̱msxi", "dəmsχi"],
    tsi: ["moon", "muːn"],
    cr: ["ᓰᐑᐦᑖᑲᐣ", "siːwiːhtaːkan"],
    chp: ["dedhai", "deðai"],
    mic: ["salawei", "salawei"],
    pqm: ["salawey", "salawej"],
    abe: ["siwan", "siwan"],
    umu: ["shíiwang", "ʃiːwaŋ"],
    crk: ["ᓰᐑᐦᑖᑲᐣ", "siːwiːhtaːkan"],
    yur: ["peeshkah", "piʃkah"],
    lkt: ["mniskúya", "mniskúja"],
    dak: ["mniskúya", "mniskúja"],
    chy: ["vóhpoma'ȯhtse", "vóhpomaʔohtse"],
    arp: ["niicoo'owu'", "niːtʃoːʔowuʔ"],
    nhx: ["istaꞌ", "istaʔ"],
    hch: ["'una", "ʔuna"],
    crn: ["unáj", "unah"],
    pao: ["ongabe", "oŋabe"],
    mez: ["sēwehtākan", "seːwehtaːkan"],
    osa: ["niskúðe", "niskúðe"],
    pot: ["siwtagen", "siwtaɡen"],
    esu: ["taryuq", "taʁjuq"],
    ess: ["таӷьюӄ", "taɣjuq"],
    iu: ["ᑕᕆᐅᖅ", "tariuq"],
    kl: ["taratsut", "taratsut"],
    tsz: ["itúkua", "iˈtukwa"],


    // --- Romance and Germanic minority languages, second pass --------
    stq: ["Soalt", "zɔːlt"],
    wym: ["zaołc", "zaːwts"],
    lld: ["sèl", "sɛl"],
    ruq: ["sari", "ˈsari"],
    pnt: ["άλας", "ˈalas"],
    aae: ["krip", "krip"],
    ctg: ["নুন", "nun"],
    lmn: ["नूण", "nuːɳ"],
    bqi: ["نمک", "nemek"],


    // --- Picard and Atikamekw ----------------------------------------
    pcd: ["sé", "se"],
    atj: ["ciwotakan", "ʃiwotakan"],


    // --- Lak ---------------------------------------------------------
    lbe: ["цӏву", "tsʼʷu"],

  },
};
