/**
 * sugar — one Sanskrit word that reached almost every language on earth, by
 * two different roads; three OTHER Sanskrit words that took their own roads;
 * and China, which never borrowed anything and exported instead.
 *
 * PARTIAL WORD (🧪): mapped only where a sourced form exists. Seven routes,
 * carried in each entry's `family`:
 *
 *   śarkarā — Sanskrit शर्करा 'grit, gravel' (the crystals) → Pali sakkharā →
 *     Middle Persian šakar → Arabic sukkar → Medieval Latin zuccarum, and from
 *     there sugar, sucre, Zucker, zucchero, cukier, сахар, şeker, шакар. Most
 *     of Eurasia is on this route, and so are Marathi साखर, Tamil சர்க்கரை and
 *     Kannada ಸಕ್ಕರೆ, which never left home.
 *   as-sukkar — the same Arabic word borrowed WITH its definite article, which
 *     is what Iberia did: al-sukkar → azúcar, açúcar, Galician/Asturian azucre,
 *     Basque azukre, and — by way of Spanish — Tagalog asukal and Cebuano
 *     asukar. Catalan sucre never had the article and is on the route above;
 *     Aragonese zucre and Asturian azucre are neighbours on opposite routes.
 *     Maltese zokkor is a Semitic language that got its sugar word back from
 *     Sicilian, minus the article.
 *   cīnī — and here the word turns around. India, which gave the world
 *     śarkarā, calls refined sugar चीनी — literally 'Chinese', after the
 *     refining technique. Hindi, Urdu, Bengali, Assamese, Odia, Nepali and
 *     Sinhala සීනි are all on this route, sitting directly beside Marathi and
 *     Tamil on the śarkarā one.
 *   khaṇḍa — a second Sanskrit noun, खण्ड 'piece, lump', which went west
 *     through Persian qand and became English CANDY. Punjabi ਖੰਡ, Gujarati
 *     ખાંડ, Sindhi کنڊ kept it at home; Kazakh қант and Kyrgyz кант took it
 *     back east through Persian.
 *   guḍa — a third, गुड 'jaggery', which went southeast and became Malay and
 *     Indonesian gula, Javanese, Sundanese and Balinese likewise.
 *   táng 糖 — China did not import a word. 糖 is its own, and it carried into
 *     Japanese 砂糖, Korean 설탕, Vietnamese đường.
 *   other — a native word or an unrelated root: Slovene sladkor from 'sweet',
 *     Thai น้ำตาล and Lao ນ້ຳຕານ from the palmyra palm (the -taan is the tree,
 *     not Chinese 糖), Māori huka, Hawaiian kōpaʻa.
 */
WORDS.sugar = {
  partial: true,
  emoji: "🍬",
  label: {
    en: "Sugar",
    ja: "砂糖",
    ko: "설탕",
    zh: "糖",
    yue: "糖",
    vi: "Đường",
    th: "น้ำตาล",
    id: "Gula",
    hi: "चीनी",
    de: "Zucker",
    fr: "Sucre",
    it: "Zucchero",
    es: "Azúcar",
    es_eu: "Azúcar",
    es_mx: "Azúcar",
    pt: "Açúcar",
    pt_eu: "Açúcar",
    pt_br: "Açúcar",
    ru: "Сахар",
    uk: "Цукор",
    ar: "سكر",
    he: "סוכר",
    sw: "Sukari",
  },
  definition: {
    en: "Sugar — the sweet crystalline substance used to sweeten food and drink. The everyday household word: not 'sweet' the adjective, not honey, not syrup, not the chemical sense (blood sugar, sugars in general), and not sugar cane the plant.",
    ja: "砂糖 — 食べ物や飲み物を甘くする結晶状の甘味料。家庭で使う日常語であって、形容詞の「甘い」でも、蜂蜜・シロップでも、化学的な意味（血糖・糖類）でも、植物のサトウキビでもない。",
    ko: "설탕 — 음식과 음료를 달게 하는 결정 형태의 감미료. 일상적인 낱말이며, 형용사 '달다'나 꿀·시럽, 화학적 의미(혈당·당류), 식물인 사탕수수를 가리키지 않음.",
    zh: "糖 — 用来使食物和饮料变甜的结晶状甜味物质。指日常家用的那种糖，不是形容词“甜”，不是蜂蜜或糖浆，不是化学意义上的糖（血糖、糖类），也不是甘蔗这种植物。",
    yue: "糖 — 用嚟整甜食物同飲品嘅結晶甜味物質。係日常屋企用嗰種，唔係形容詞「甜」，唔係蜂蜜或者糖漿，唔係化學意義嘅糖（血糖、糖類），亦唔係甘蔗呢種植物。",
    vi: "Đường — chất kết tinh có vị ngọt dùng để làm ngọt thức ăn và đồ uống. Từ thường dùng trong nhà: không phải tính từ 'ngọt', không phải mật ong hay siro, không phải nghĩa hoá học (đường huyết), cũng không phải cây mía.",
    th: "น้ำตาล — สารผลึกรสหวานที่ใช้ทำให้อาหารและเครื่องดื่มหวาน เป็นคำที่ใช้ในครัวเรือน ไม่ใช่คำคุณศัพท์ 'หวาน' ไม่ใช่น้ำผึ้งหรือน้ำเชื่อม ไม่ใช่ความหมายทางเคมี (น้ำตาลในเลือด) และไม่ใช่ต้นอ้อย",
    id: "Gula — zat kristal manis yang dipakai untuk memaniskan makanan dan minuman. Kata sehari-hari di rumah: bukan kata sifat 'manis', bukan madu atau sirop, bukan makna kimiawi (gula darah), dan bukan tebu.",
    hi: "चीनी — खाने-पीने की चीज़ों को मीठा करने वाला दानेदार पदार्थ। घर में रोज़ बोला जाने वाला शब्द: न विशेषण 'मीठा', न शहद या चाशनी, न रासायनिक अर्थ (रक्त शर्करा), और न गन्ना।",
    de: "Zucker — der süße kristalline Stoff zum Süßen von Speisen und Getränken. Das alltägliche Haushaltswort: nicht das Adjektiv 'süß', nicht Honig oder Sirup, nicht die chemische Bedeutung (Blutzucker) und nicht das Zuckerrohr.",
    fr: "Sucre — la substance cristalline sucrée servant à sucrer les aliments et les boissons. Le mot courant de la cuisine : ni l'adjectif « sucré », ni le miel, ni le sirop, ni le sens chimique (glycémie), ni la canne à sucre.",
    it: "Zucchero — la sostanza cristallina dolce usata per dolcificare cibi e bevande. La parola di uso domestico: non l'aggettivo 'dolce', non il miele o lo sciroppo, non il senso chimico (glicemia), non la canna da zucchero.",
    es: "Azúcar — la sustancia cristalina dulce que se usa para endulzar alimentos y bebidas. La palabra doméstica de todos los días: no el adjetivo 'dulce', ni la miel o el jarabe, ni el sentido químico (glucemia), ni la caña de azúcar.",
    es_eu: "Azúcar — la sustancia cristalina dulce que se usa para endulzar alimentos y bebidas. La palabra doméstica de todos los días: no el adjetivo 'dulce', ni la miel o el jarabe, ni el sentido químico (glucemia), ni la caña de azúcar.",
    es_mx: "Azúcar — la sustancia cristalina dulce que se usa para endulzar alimentos y bebidas. La palabra doméstica de todos los días: no el adjetivo 'dulce', ni la miel o el jarabe, ni el sentido químico (glucemia), ni la caña de azúcar.",
    pt: "Açúcar — a substância cristalina doce usada para adoçar alimentos e bebidas. A palavra caseira do dia a dia: não o adjetivo 'doce', nem o mel ou a calda, nem o sentido químico (glicemia), nem a cana-de-açúcar.",
    pt_eu: "Açúcar — a substância cristalina doce usada para adoçar alimentos e bebidas. A palavra caseira do dia a dia: não o adjetivo 'doce', nem o mel ou a calda, nem o sentido químico (glicemia), nem a cana-de-açúcar.",
    pt_br: "Açúcar — a substância cristalina doce usada para adoçar alimentos e bebidas. A palavra caseira do dia a dia: não o adjetivo 'doce', nem o mel ou a calda, nem o sentido químico (glicemia), nem a cana-de-açúcar.",
    ru: "Сахар — сладкое кристаллическое вещество, которым подслащивают еду и напитки. Обиходное домашнее слово: не прилагательное 'сладкий', не мёд и не сироп, не химическое значение (сахар в крови), не сахарный тростник.",
    uk: "Цукор — солодка кристалічна речовина, якою підсолоджують їжу та напої. Побутове щоденне слово: не прикметник 'солодкий', не мед і не сироп, не хімічне значення (цукор у крові), не цукрова тростина.",
    ar: "السكر — المادة البلورية الحلوة التي تُحلّى بها الأطعمة والمشروبات. الكلمة البيتية اليومية: لا الصفة 'حلو'، ولا العسل أو الشراب المركّز، ولا المعنى الكيميائي (سكر الدم)، ولا قصب السكر.",
    he: "סוכר — החומר הגבישי המתוק שבו ממתיקים מאכלים ומשקאות. המילה הביתית היומיומית: לא שם התואר 'מתוק', לא דבש או סירופ, לא המובן הכימי (סוכר בדם), ולא קנה הסוכר.",
    sw: "Sukari — kitu chenye fuwele na ladha tamu kinachotumika kutia utamu katika chakula na vinywaji. Neno la kawaida la nyumbani: si kivumishi 'tamu', si asali wala shira, si maana ya kikemia (sukari ya damu), wala si mwanzi wa sukari.",
  },
  family: {
    es_cr: "assukkar",
    es_hn: "assukkar",
    es_ni: "assukkar",
    es_sv: "assukkar",
    ar_jo: "sharkara",
    ar_ps: "sharkara",
    fr_lu: "sharkara",
    fr_cm: "sharkara",
    en_ng2: "sharkara",
    pt_mo: "assukkar",
    lb: "sharkara",
    es_bo: "assukkar",
    es_py: "assukkar",
    es_pa: "assukkar",
    en_my: "sharkara",
    ayl: "sharkara",
    abv: "sharkara",
    afb: "sharkara",
    acw: "sharkara",
    har: "sharkara",
    es_pr: "assukkar",
    es_do: "assukkar",
    es_gt: "assukkar",
    es_ec: "assukkar",
    es_uy: "assukkar",
    ar_sy: "sharkara",
    ar_ye: "sharkara",
    ar_sa: "sharkara",
    ar_lb: "sharkara",
    en_wls: "sharkara",
    en_jam: "sharkara",
    en_ng: "sharkara",
    en_ph: "sharkara",
    en_ke: "sharkara",
    fr_sn: "sharkara",
    fr_ci: "sharkara",
    fr_ht: "sharkara",
    pt_mz: "assukkar",
    pt_cv: "assukkar",
    en_us: "sharkara",
    en_ca: "sharkara",
    en_za: "sharkara",
    pt_ao: "assukkar",
    es_ve: "assukkar",
    ja: "tang",
    ko: "tang",
    zh: "tang",
    yue: "tang",
    nan: "tang",
    zh_tw: "tang",
    wuu: "tang",
    hak_cn: "tang",
    vi: "tang",
    vi_s: "tang",
    th: "other",
    id: "guda",
    ms: "guda",
    hi: "chini",
    sa: "sharkara",
    bn: "chini",
    ur: "chini",
    ta: "sharkara",
    en: "sharkara",
    de: "sharkara",
    fr: "sharkara",
    it: "sharkara",
    es: "assukkar",
    es_mx: "assukkar",
    pt: "assukkar",
    pt_br: "assukkar",
    ru: "sharkara",
    ar: "sharkara",
    he: "sharkara",
    tr: "sharkara",
    fa: "sharkara",
    sw: "sharkara",
    tl: "assukkar",
    mn: "sharkara",
    sah: "sharkara",
    alt: "sharkara",
    cv: "sharkara",
    my: "sharkara",
    km: "sharkara",
    lo: "other",
    yo: "sharkara",
    zu: "sharkara",
    am: "sharkara",
    fi: "sharkara",
    hu: "sharkara",
    el: "sharkara",
    nl: "sharkara",
    pl: "sharkara",
    uk: "sharkara",
    sv: "sharkara",
    no: "sharkara",
    da: "sharkara",
    ro: "sharkara",
    ga: "sharkara",
    eu: "assukkar",
    cy: "sharkara",
    ka: "sharkara",
    hy: "sharkara",
    haw: "other",
    mi: "sharkara",
    zh_db: "tang",
    jv: "guda",
    su: "guda",
    ceb: "assukkar",
    sm: "sharkara",
    to: "sharkara",
    sd: "khanda",
    pa: "khanda",
    ne: "chini",
    mr: "sharkara",
    gu: "khanda",
    si: "chini",
    te: "sharkara",
    kn: "sharkara",
    ml: "other",
    tg: "sharkara",
    ku: "sharkara",
    ckb: "sharkara",
    az: "sharkara",
    azb: "sharkara",
    ug: "sharkara",
    kk: "khanda",
    ky: "khanda",
    uz: "sharkara",
    tk: "sharkara",
    ar_eg: "sharkara",
    ar_gulf: "sharkara",
    ar_iq: "sharkara",
    ar_ma: "sharkara",
    arq: "sharkara",
    ar_tn: "sharkara",
    ar_sd: "sharkara",
    ti: "sharkara",
    mt: "sharkara",
    so: "sharkara",
    om: "sharkara",
    xh: "sharkara",
    en_aave: "sharkara",
    en_nz: "sharkara",
    en_au: "sharkara",
    sco: "sharkara",
    af: "sharkara",
    nds: "sharkara",
    yi: "sharkara",
    is: "sharkara",
    gd: "sharkara",
    br: "sharkara",
    nap: "sharkara",
    scn: "sharkara",
    co: "sharkara",
    lij: "sharkara",
    ca: "sharkara",
    gl: "assukkar",
    oc: "sharkara",
    be: "sharkara",
    cs: "sharkara",
    sk: "sharkara",
    sl: "other",
    sr: "sharkara",
    bg: "sharkara",
    lt: "sharkara",
    lv: "sharkara",
    sq: "sharkara",
    et: "sharkara",
    ht: "sharkara",
    se: "sharkara",
    as: "chini",
    or: "chini",
    en_south: "sharkara",
    en_app: "sharkara",
    en_in: "sharkara",
    en_ie: "sharkara",
    en_sco: "sharkara",
    en_yk: "sharkara",
    en_ck: "sharkara",
    en_scouse: "sharkara",
    en_geordie: "sharkara",
    en_brum: "sharkara",
    en_manc: "sharkara",
    en_wc: "sharkara",
    en_est: "sharkara",
    en_sg: "sharkara",
    fy: "sharkara",
    li: "sharkara",
    fo: "sharkara",
    fr_qc: "sharkara",
    fr_af: "sharkara",
    fr_be: "sharkara",
    fr_ch: "sharkara",
    es_co: "assukkar",
    es_cl: "assukkar",
    es_ar: "assukkar",
    es_cu: "assukkar",
    es_pe: "assukkar",
    es_an: "assukkar",
    rm: "sharkara",
    sc: "sharkara",
    la: "sharkara",
    el_grc: "sharkara",
    vi_nom: "tang",
    eo: "sharkara",
    ia: "sharkara",
    mk: "sharkara",
    ban: "guda",
    aa: "sharkara",
    ast: "assukkar",
    an: "sharkara",
    tt: "sharkara",
    ba: "sharkara",
    kw: "sharkara",
    hr: "sharkara",
    bs: "sharkara",
    ach: "sharkara",
    hak_tw: "tang",
    nan_qz: "tang",
    zh_km: "tang",
    nan_xm: "tang",
    io: "sharkara",
  },
  routes: {
    sharkara: { color: "#b45309", emoji: "💎", en: "from Sanskrit śarkarā", ja: "サンスクリット śarkarā 由来", ko: "산스크리트 śarkarā 유래", zh: "源自梵语 śarkarā", yue: "源自梵文 śarkarā", vi: "từ tiếng Phạn śarkarā", th: "จากภาษาสันสกฤต śarkarā", id: "dari bahasa Sanskerta śarkarā", hi: "संस्कृत शर्करा से", de: "vom Sanskrit śarkarā", fr: "du sanskrit śarkarā", it: "dal sanscrito śarkarā", es: "del sánscrito śarkarā", pt: "do sânscrito śarkarā", ru: "от санскр. śarkarā", uk: "від санскр. śarkarā", ar: "من السنسكريتية śarkarā", he: "מסנסקריט śarkarā", sw: "kutoka Kisanskriti śarkarā" },
    assukkar: { color: "#be123c", emoji: "🕌", en: "Arabic as-sukkar, article and all", ja: "アラビア語 as-sukkar・冠詞ごと", ko: "아랍어 as-sukkar, 관사까지 함께", zh: "阿拉伯语 as-sukkar，连冠词一起", yue: "阿拉伯文 as-sukkar，連冠詞一齊", vi: "tiếng Ả Rập as-sukkar, cả mạo từ", th: "ภาษาอาหรับ as-sukkar พร้อมคำนำหน้า", id: "bahasa Arab as-sukkar, berikut kata sandangnya", hi: "अरबी as-sukkar, उपपद सहित", de: "arabisch as-sukkar, samt Artikel", fr: "arabe as-sukkar, article compris", it: "arabo as-sukkar, articolo incluso", es: "árabe as-sukkar, con artículo y todo", pt: "árabe as-sukkar, artigo incluído", ru: "араб. as-sukkar, вместе с артиклем", uk: "араб. as-sukkar, разом з артиклем", ar: "العربية السُّكَّر بأداة التعريف", he: "ערבית as-sukkar, כולל התווית", sw: "Kiarabu as-sukkar, pamoja na kiambishi" },
    tang: { color: "#0e7490", emoji: "🎋", en: "Chinese 糖, not borrowed at all", ja: "漢語 糖・借用ではない", ko: "한자 糖, 차용이 아님", zh: "汉语「糖」，并非借词", yue: "漢語「糖」，唔係借詞", vi: "chữ Hán 糖, không phải từ mượn", th: "ภาษาจีน 糖 ไม่ได้ยืมมา", id: "bahasa Tionghoa 糖, bukan pinjaman", hi: "चीनी 糖, उधार लिया हुआ नहीं", de: "chinesisch 糖, gar nicht entlehnt", fr: "chinois 糖, nullement emprunté", it: "cinese 糖, per nulla prestito", es: "chino 糖, no es préstamo", pt: "chinês 糖, não é empréstimo", ru: "кит. 糖, вовсе не заимствование", uk: "кит. 糖, зовсім не запозичення", ar: "الصينية 糖، وليست اقتراضًا", he: "סינית 糖, לא שאילה כלל", sw: "Kichina 糖, si mkopo hata kidogo" },
    chini: { color: "#7c3aed", emoji: "🔁", en: "cīnī — 'the Chinese one'", ja: "cīnī・「中国のもの」", ko: "cīnī — '중국 것'", zh: "cīnī — 意思是「中国的」", yue: "cīnī — 意思係「中國嘅」", vi: "cīnī — 'thứ của Trung Hoa'", th: "cīnī — 'ของจีน'", id: "cīnī — 'yang dari Tiongkok'", hi: "चीनी — यानी 'चीन का'", de: "cīnī — 'das Chinesische'", fr: "cīnī — « la chinoise »", it: "cīnī — 'quella cinese'", es: "cīnī — 'la china'", pt: "cīnī — 'a chinesa'", ru: "cīnī — 'китайский'", uk: "cīnī — 'китайський'", ar: "cīnī — أي 'الصينيّ'", he: "cīnī — 'הסינית'", sw: "cīnī — 'ile ya Kichina'" },
    khanda: { color: "#c2410c", emoji: "🍬", en: "khaṇḍa — the root of CANDY", ja: "khaṇḍa・CANDY の語源", ko: "khaṇḍa — CANDY의 어원", zh: "khaṇḍa — CANDY 的词根", yue: "khaṇḍa — CANDY 嘅詞根", vi: "khaṇḍa — gốc của CANDY", th: "khaṇḍa — รากของคำว่า CANDY", id: "khaṇḍa — akar kata CANDY", hi: "खण्ड — CANDY का मूल", de: "khaṇḍa — die Wurzel von CANDY", fr: "khaṇḍa — la racine de CANDY", it: "khaṇḍa — la radice di CANDY", es: "khaṇḍa — la raíz de CANDY", pt: "khaṇḍa — a raiz de CANDY", ru: "khaṇḍa — корень слова CANDY", uk: "khaṇḍa — корінь слова CANDY", ar: "khaṇḍa — أصل كلمة CANDY", he: "khaṇḍa — השורש של CANDY", sw: "khaṇḍa — shina la neno CANDY" },
    guda: { color: "#0d9488", emoji: "🌴", en: "guḍa — jaggery, gone southeast", ja: "guḍa・粗糖が東南へ", ko: "guḍa — 조당이 동남쪽으로", zh: "guḍa — 粗糖，向东南而去", yue: "guḍa — 粗糖，向東南而去", vi: "guḍa — đường thô, đi về đông nam", th: "guḍa — น้ำตาลดิบ ที่ไปทางตะวันออกเฉียงใต้", id: "guḍa — gula merah, menuju tenggara", hi: "गुड — दक्षिण-पूर्व की ओर गया", de: "guḍa — Rohzucker, nach Südosten", fr: "guḍa — le sucre brut, parti vers le sud-est", it: "guḍa — zucchero grezzo, verso sud-est", es: "guḍa — azúcar sin refinar, hacia el sudeste", pt: "guḍa — açúcar mascavo, rumo a sudeste", ru: "guḍa — тростниковый сахар, ушедший на юго-восток", uk: "guḍa — тростинний цукор, що пішов на південний схід", ar: "guḍa — السكر الخام، اتجه جنوب شرقًا", he: "guḍa — סוכר גולמי, שהלך דרום-מזרחה", sw: "guḍa — sukari ghafi, iliyoelekea kusini-mashariki" },
    other: { color: "#6b7280", emoji: "🌾", en: "a native or unrelated word", ja: "固有語または無関係の語", ko: "고유어 또는 무관한 낱말", zh: "本土词或无关的词", yue: "本土詞或者無關嘅詞", vi: "từ bản địa hoặc không liên quan", th: "คำพื้นเมืองหรือคำที่ไม่เกี่ยวข้อง", id: "kata asli atau tak berkaitan", hi: "देशज या असंबद्ध शब्द", de: "ein eigenes oder nicht verwandtes Wort", fr: "un mot propre ou sans rapport", it: "una parola propria o non imparentata", es: "una palabra propia o sin relación", pt: "uma palavra própria ou sem relação", ru: "своё или неродственное слово", uk: "власне або неспоріднене слово", ar: "كلمة أصلية أو غير ذات صلة", he: "מילה מקורית או לא קשורה", sw: "neno la asili au lisilohusiana" },
  },
  data: {
    es_cr: ["azúcar", "aˈsukaɾ"],
    es_hn: ["azúcar", "aˈsukaɾ"],
    es_ni: ["azúcar", "aˈsukaɾ"],
    es_sv: ["azúcar", "aˈsukaɾ"],
    ar_jo: ["سكر", "ˈsukkar"],
    ar_ps: ["سكر", "ˈsukkar"],
    fr_lu: ["sucre", "sykʁ"],
    fr_cm: ["sucre", "sykʁ"],
    en_ng2: ["sugar", "ˈʃʊɡə"],
    pt_mo: ["açúcar", "ɐˈsukaɾ"],
    lb: ["Zocker", "ˈtsokɐ"],
    es_bo: ["azúcar", "aˈsukaɾ"],
    es_py: ["azúcar", "aˈsukaɾ"],
    es_pa: ["azúcar", "aˈsukaɾ"],
    en_my: ["sugar", "ˈʃʊɡə"],
    ayl: ["سكر", "ˈsukkar"],
    abv: ["سكر", "ˈsukkar"],
    afb: ["سكر", "ˈsukkar"],
    acw: ["سكر", "ˈsukkar"],
    har: ["sukkar", "sukːɑr"],
    es_pr: ["azúcar", "aˈsukal"],
    es_do: ["azúcar", "aˈsuka"],
    es_gt: ["azúcar", "aˈsukaɾ"],
    es_ec: ["azúcar", "aˈsukaɾ"],
    es_uy: ["azúcar", "aˈsukaɾ"],
    ar_sy: ["سكر", "ˈsukkar"],
    ar_ye: ["سكر", "ˈsukkar"],
    ar_sa: ["سكر", "ˈsukkar"],
    ar_lb: ["سكر", "ˈsukkar"],
    en_wls: ["sugar", "ˈʃʊɡə"],
    en_jam: ["sugar", "ˈʃʊɡə"],
    en_ng: ["sugar", "ˈʃʊɡə"],
    en_ph: ["sugar", "ˈʃʊɡɚ"],
    en_ke: ["sugar", "ˈʃʊɡə"],
    fr_sn: ["sucre", "sykʁ"],
    fr_ci: ["sucre", "sykʁ"],
    fr_ht: ["sucre", "sykʁ"],
    pt_mz: ["açúcar", "ɐˈsukaɾ"],
    pt_cv: ["açúcar", "ɐˈsukaɾ"],
    en_us: ["sugar", "ˈʃʊɡɚ"],
    en_ca: ["sugar", "ˈʃʊɡɚ"],
    en_za: ["sugar", "ˈʃʊɡə"],
    pt_ao: ["açúcar", "aˈsukaɾ"],
    es_ve: ["azúcar", "aˈsukaɾ"],
    ja: ["砂糖", "satoː"],
    ko: ["설탕", "sʌltʰaŋ"],
    zh: ["糖", "tʰɑŋ˧˥"],
    yue: ["糖", "tʰɔːŋ˨˩"],
    nan: ["糖", "tʰŋ̍˨˦"],
    zh_tw: ["糖", "tʰaŋ˧˥"],
    wuu: ["糖", "dɑ̃˨˧"],
    hak_cn: ["糖", "tʰoŋ˩˩"],
    vi: ["đường", "ɗɨəŋ˨˩"],
    vi_s: ["đường", "ɗɨəŋ˨˩"],
    th: ["น้ำตาล", "nam˦˥ taːn˧"],
    id: ["gula", "ˈɡula"],
    ms: ["gula", "ˈɡula"],
    hi: ["चीनी", "tʃiːniː"],
    sa: ["शर्करा", "ɕɐrkɐraː"],
    bn: ["চিনি", "tɕini"],
    ur: ["چینی", "tʃiːniː"],
    ta: ["சர்க்கரை", "sarkkaɾai"],
    en: ["sugar", "ˈʃʊɡə"],
    de: ["Zucker", "ˈtsʊkɐ"],
    fr: ["sucre", "sykʁ"],
    it: ["zucchero", "ˈdzukkero"],
    es: ["azúcar", "aˈθukaɾ"],
    es_mx: ["azúcar", "aˈsukaɾ"],
    pt: ["açúcar", "ɐˈsukaɾ"],
    pt_br: ["açúcar", "aˈsukaɾ"],
    ru: ["сахар", "ˈsaxər"],
    ar: ["سكر", "ˈsukkar"],
    he: ["סוכר", "suˈkaʁ"],
    tr: ["şeker", "ʃeˈceɾ"],
    fa: ["شکر", "ʃeˈkæɾ"],
    sw: ["sukari", "suˈkari"],
    tl: ["asukal", "ʔaˈsukal"],
    mn: ["элсэн чихэр", "ˈelsəŋ tʃʰixər"],
    sah: ["саахар", "ˈsaːxar"],
    alt: ["чикир", "tʃiˈkir"],
    cv: ["сахӑр", "ˈsaxər"],
    my: ["သကြား", "θədʑá"],
    km: ["ស្ករ", "skɑː"],
    lo: ["ນ້ຳຕານ", "naːm˥˩ taːn˩˧"],
    yo: ["ṣúgà", "ʃúɡà"],
    zu: ["ushukela", "uʃuˈkɛːla"],
    am: ["ስኳር", "sɨkʷar"],
    fi: ["sokeri", "ˈsokeri"],
    hu: ["cukor", "ˈtsukor"],
    el: ["ζάχαρη", "ˈzaxari"],
    nl: ["suiker", "ˈsœʏkər"],
    pl: ["cukier", "ˈtsukʲɛr"],
    uk: ["цукор", "ˈtsukor"],
    sv: ["socker", "ˈsɔkːɛr"],
    no: ["sukker", "ˈsʊkːər"],
    da: ["sukker", "ˈsɔɡɐ"],
    ro: ["zahăr", "ˈzahər"],
    ga: ["siúcra", "ˈʃuːkɾˠə"],
    eu: ["azukre", "as̻ukɾe"],
    cy: ["siwgr", "ˈʃʊɡʊr"],
    ka: ["შაქარი", "ʃakʰari"],
    hy: ["շաքար", "ʃɑˈkʰɑɾ"],
    haw: ["kōpaʻa", "koːˈpɐʔɐ"],
    mi: ["huka", "huka"],
    zh_db: ["糖", "tʰɑŋ˧˥"],
    jv: ["gula", "ˈɡulɔ"],
    su: ["gula", "ɡula"],
    ceb: ["asukar", "ʔaˈsukar"],
    sm: ["suka", "suka"],
    to: ["suka", "ˈsuka"],
    sd: ["کنڊ", "kʰanɖu"],
    pa: ["ਖੰਡ", "kʰəɳɖ"],
    ne: ["चिनी", "tsini"],
    mr: ["साखर", "ˈsaːkʰəɾ"],
    gu: ["ખાંડ", "kʰaːɳɖ"],
    si: ["සීනි", "siːni"],
    te: ["చక్కెర", "tʃakkeɾa"],
    kn: ["ಸಕ್ಕರೆ", "sakkaɾe"],
    ml: ["പഞ്ചസാര", "paɲtʃasaːɾa"],
    tg: ["шакар", "ʃaˈkar"],
    ku: ["şekir", "ʃɛˈkɪr"],
    ckb: ["شەکر", "ʃɛˈkɪr"],
    az: ["şəkər", "ʃæˈkæɾ"],
    azb: ["شکر", "ʃæˈkæɾ"],
    ug: ["شېكەر", "ʃeˈkɛr"],
    kk: ["қант", "qɑnt"],
    ky: ["кант", "kant"],
    uz: ["shakar", "ʃaˈkar"],
    tk: ["şeker", "ʃeˈker"],
    ar_eg: ["سكر", "ˈsukkar"],
    ar_gulf: ["سكر", "ˈsukkar"],
    ar_iq: ["سكر", "ˈsukkar"],
    ar_ma: ["سكر", "ˈsukkar"],
    arq: ["سكر", "ˈsukkar"],
    ar_tn: ["سكر", "ˈsukkar"],
    ar_sd: ["سكر", "ˈsukkar"],
    ti: ["ሽኮር", "ʃɨkor"],
    mt: ["zokkor", "ˈtsɔkkor"],
    so: ["sonkor", "sonkor"],
    om: ["sukkaara", "sukːaːra"],
    xh: ["iswekile", "isweˈkiːle"],
    en_aave: ["sugar", "ˈʃʊɡɚ"],
    en_nz: ["sugar", "ˈʃʊɡə"],
    en_au: ["sugar", "ˈʃʊɡə"],
    sco: ["shuggar", "ˈʃʌɡər"],
    af: ["suiker", "ˈsœɪkər"],
    nds: ["Sucker", "ˈzʊkɐ"],
    yi: ["צוקער", "ˈtsukər"],
    is: ["sykur", "ˈsɪːkʏr"],
    gd: ["siùcar", "ˈʃuːxkər"],
    br: ["sukr", "sykɾ"],
    nap: ["zùccaro", "ˈtsukkərə"],
    scn: ["zuccuru", "ˈtsukkuru"],
    co: ["zuccheru", "ˈdzukkeru"],
    lij: ["sûccao", "ˈsykaw"],
    ca: ["sucre", "ˈsukɾə"],
    gl: ["azucre", "aˈθukɾe"],
    oc: ["sucre", "ˈsykɾe"],
    be: ["цукар", "ˈtsukar"],
    cs: ["cukr", "tsukr̩"],
    sk: ["cukor", "ˈtsukor"],
    sl: ["sladkor", "ˈslaːtkɔr"],
    sr: ["шећер", "ˈʃɛtɕeːr"],
    bg: ["захар", "ˈzaxɐr"],
    lt: ["cukrus", "ˈtsʊkrʊs"],
    lv: ["cukurs", "ˈtsukurs"],
    sq: ["sheqer", "ʃɛˈcɛr"],
    et: ["suhkur", "ˈsuhkur"],
    ht: ["sik", "sik"],
    se: ["sohkar", "ˈsohkar"],
    as: ["চেনি", "seni"],
    or: ["ଚିନି", "tʃini"],
    en_south: ["sugar", "ˈʃʊɡɚ"],
    en_app: ["sugar", "ˈʃʊɡɚ"],
    en_in: ["sugar", "ˈʃʊɡɚ"],
    en_ie: ["sugar", "ˈʃʊɡəɹ"],
    en_sco: ["sugar", "ˈʃʊɡəɹ"],
    en_yk: ["sugar", "ˈʃʊɡə"],
    en_ck: ["sugar", "ˈʃʊɡə"],
    en_scouse: ["sugar", "ˈʃʊɡə"],
    en_geordie: ["sugar", "ˈʃʊɡɐ"],
    en_brum: ["sugar", "ˈʃʊɡə"],
    en_manc: ["sugar", "ˈʃʊɡɐ"],
    en_wc: ["sugar", "ˈʃʊɡɚ"],
    en_est: ["sugar", "ˈʃʊɡə"],
    en_sg: ["sugar", "ˈʃʊɡə"],
    fy: ["sûker", "ˈsuːkər"],
    li: ["sókker", "ˈsɔkər"],
    fo: ["sukur", "ˈsuːkʊɹ"],
    fr_qc: ["sucre", "sʏkʁ"],
    fr_af: ["sucre", "sykʁ"],
    fr_be: ["sucre", "sykʁ"],
    fr_ch: ["sucre", "sykʁ"],
    es_co: ["azúcar", "aˈsukaɾ"],
    es_cl: ["azúcar", "aˈsukaɾ"],
    es_ar: ["azúcar", "aˈsukaɾ"],
    es_cu: ["azúcar", "aˈsukaɾ"],
    es_pe: ["azúcar", "aˈsukaɾ"],
    es_an: ["azúcar", "aˈsukaɾ"],
    rm: ["zutger", "ˈtsutɕer"],
    sc: ["tzùcaru", "ˈtsukaru"],
    la: ["saccharum", "ˈsakkʰarum"],
    el_grc: ["σάκχαρ", "sákkʰar"],
    vi_nom: ["糖", "ɗɨəŋ˨˩"],
    eo: ["sukero", "suˈkero"],
    ia: ["sucro", "ˈsukro"],
    mk: ["шеќер", "ˈʃɛcɛr"],
    ban: ["gula", "ɡula"],
    aa: ["sokkár", "sokːar"],
    ast: ["azucre", "aˈθukɾe"],
    an: ["zucre", "ˈθukɾe"],
    tt: ["шикәр", "ʃiˈkær"],
    ba: ["шәкәр", "ʃæˈkær"],
    kw: ["sugra", "ˈsuɡra"],
    hr: ["šećer", "ˈʃɛtɕeːr"],
    bs: ["šećer", "ˈʃɛtɕeːr"],
    ach: ["cukari", "tʃukari"],
    hak_tw: ["糖", "tʰoŋ˩˩"],
    nan_qz: ["糖", "tʰŋ̍˨˦"],
    zh_km: ["糖", "tʰaŋ˧˩"],
    nan_xm: ["糖", "tʰŋ̍˨˦"],
    io: ["sukro", "ˈsukro"],
  },
};
