/**
 * wind — the everyday noun for naturally moving air. Most of Eurasia traces
 * to PIE *h₂weh₁-nt- "blowing" (participle of *h₂weh₁- "to blow"): Latin
 * ventus → Romance vent/viento/vento, Germanic *windaz → English wind /
 * German Wind, Celtic (Welsh gwynt), Slavic větrъ → ветер/wiatr, Sanskrit
 * vāta / Avestan vāta, Baltic vėjas. Outside Indo-European: Semitic *rīḥ
 * (Arabic ريح, Hebrew רוח, also "spirit"), Sino-Tibetan 風 (Mandarin fēng,
 * Japanese kaze, Sino-Vietnamese phong), Austronesian *baŋin (Malay/Tagalog
 * angin), Bantu *-pepo (Swahili upepo) — each an independent root.
 */
WORDS.wind = {
  emoji: "🌬️",
  label: {
    en: "Wind",
    ja: "風",
    ko: "바람",
    zh: "风",
    yue: "風",
    vi: "Gió",
    th: "ลม",
    id: "Angin",
    hi: "हवा",
    de: "Wind",
    fr: "Vent",
    it: "Vento",
    es: "Viento",
    es_eu: "Viento",
    es_mx: "Viento",
    pt: "Vento",
    pt_eu: "Vento",
    pt_br: "Vento",
    ru: "Ветер",
    uk: "Вітер",
    ar: "ريح",
    he: "רוח",
    sw: "Upepo",
  },
  definition: {
    en: "Wind — naturally moving air, especially outdoors; not \"breath\" or \"to wind\" (as in winding a clock).",
    ja: "風——屋外などで自然に動く空気の流れ。「息」や「（時計を）巻く」という意味ではない。",
    ko: "바람 — 자연적으로 움직이는 공기(특히 야외의). \"숨\"이나 \"(시계를) 감다\"가 아니다.",
    zh: "风——自然流动的空气（尤指室外）；不是\"呼吸\"或\"上发条\"的意思。",
    yue: "風——自然流動嘅空氣（尤其係戶外嘅）；唔係「呼吸」或者「上鏈」嘅意思。",
    vi: "Gió — luồng không khí chuyển động tự nhiên (ngoài trời); không phải \"hơi thở\" hay \"lên dây (đồng hồ)\".",
    th: "ลม — อากาศที่เคลื่อนที่ตามธรรมชาติ (โดยเฉพาะกลางแจ้ง); ไม่ใช่ \"ลมหายใจ\" หรือ \"การไขลาน\"",
    id: "Angin — udara yang bergerak secara alami (terutama di luar ruangan); bukan \"napas\" atau \"memutar\" (jam).",
    hi: "हवा — प्राकृतिक रूप से चलने वाली वायु (विशेषतः बाहर); \"सांस\" या \"घड़ी की चाबी भरना\" नहीं।",
    de: "Wind — natürlich bewegte Luft (besonders im Freien); nicht \"Atem\" oder \"aufziehen\" (wie eine Uhr).",
    fr: "Vent — air en mouvement naturel (surtout en extérieur); pas le \"souffle\" ni \"remonter\" (une horloge).",
    it: "Vento — aria in movimento naturale (soprattutto all'aperto); non il \"respiro\" né \"caricare\" (un orologio).",
    es: "Viento — aire en movimiento natural (sobre todo al aire libre); no el \"aliento\" ni \"dar cuerda\" (a un reloj).",
    es_eu: "Viento — aire en movimiento natural (sobre todo al aire libre); no el \"aliento\" ni \"dar cuerda\" (a un reloj).",
    es_mx: "Viento — aire en movimiento natural (sobre todo al aire libre); no el \"aliento\" ni \"dar cuerda\" (a un reloj).",
    pt: "Vento — ar em movimento natural (sobretudo ao ar livre); não a \"respiração\" nem \"dar corda\" (a um relógio).",
    pt_eu: "Vento — ar em movimento natural (sobretudo ao ar livre); não a \"respiração\" nem \"dar corda\" (a um relógio).",
    pt_br: "Vento — ar em movimento natural (sobretudo ao ar livre); não a \"respiração\" nem \"dar corda\" (a um relógio).",
    ru: "Ветер — естественное движение воздуха (особенно на улице); не \"дыхание\" и не \"завести\" (часы).",
    uk: "Вітер — природний рух повітря (особливо на вулиці); не \"дихання\" і не \"завести\" (годинник).",
    ar: "الريح — حركة طبيعية للهواء (خاصة في الخارج)؛ ليست \"النَفَس\" ولا \"لَفّ\" (الساعة).",
    he: "רוח — תנועה טבעית של אוויר (בעיקר בחוץ); לא \"נשימה\" ולא \"למתוח\" (שעון).",
    sw: "Upepo — hewa inayosogea kiasili (hasa nje); si \"pumzi\" wala \"kuzungusha\" (saa).",
  },
  data: {
    la: ["ventus", "ˈwɛntʊs"],
    el_grc: ["ἄνεμος", "ˈanemos"],
    el_kath: ["άνεμος", "ˈanemos"],
    ang: ["wind", "wind"],
    enm: ["wind", "wind"],
    en_em: ["wind", "wɪnd"],
    non: ["vindr", "vindr"],
    got: ["𐍅𐌹𐌽𐌳𐍃", "winds"],
    goh: ["wint", "wint"],
    gmh: ["wint", "wɪnt"],
    osx: ["wind", "wind"],
    ofs: ["wind", "wind"],
    fro: ["vent", "vent"],
    fr_class: ["vent", "vɑ̃"],
    it_dan: ["vento", "ˈvɛnto"],
    osp: ["viento", "ˈvjento"],
    es_sgl: ["viento", "ˈbjento"],
    sa: ["वायुः", "ʋaːjʊh"],
    sa_edu: ["वायुः", "ʋaːjʊh"],
    h_vedic: ["वात", "ˈʋaːtɐ"],
    pi: ["वात", "ʋaːtɐ"],
    pi_edu: ["vāta", "ʋaːtɐ"],
    cu: ["вѣтръ", "ˈvʲɛtrŭ"],
    orv: ["вѣтръ", "ˈvʲetrə"],
    hbo: ["רוח", "ˈruːaħ"],
    he_mis: ["רוח", "ˈruaħ"],
    arc: ["ܪܘܚܐ", "ˈruħaː"],
    syc: ["ܪܘܚܐ", "ˈruħɔ"],
    aii: ["ܪܘܚܐ", "ˈruxa"],
    gez: ["ነፋስ", "nafas"],
    p_ine: ["*h₂wéh₁n̥ts", "h₂wéh₁n̥ts"],
    p_ryu: ["*kaze", "kaze"],
    och: ["風", "*prəm"],
    zh_tang: ["風", "pjuŋ"],
    vi_han: ["風", "fɔŋm˧˧"],
    ja: ["風", "kaze"],
    ja_osa: ["風", "kaze"],
    ja_aom: ["風", "kadze"],
    ja_hak: ["風", "kaze"],
    ja_kyo: ["風", "kaze"],
    ja_hir: ["風", "kaze"],
    ja_kg: ["風", "kaze"],
    ja_sd: ["風", "kadze"],
    ja_edo: ["風", "kadze"],
    ja_heian: ["風", "kadze"],
    ja_chu: ["風", "kadze"],
    ja_kanbun: ["風", "kaze"],
    ja_oki: ["風", "kadʑi"],
    ja_mvi: ["風", "kadʑi"],
    ja_rys: ["風", "kadʑi"],
    ko: ["바람", "paɾam"],
    ko_kp: ["바람", "paɾam"],
    ko_bus: ["바람", "paɾam"],
    ko_hg: ["바람", "paɾam"],
    ko_jl: ["바람", "paɾam"],
    ko_yb: ["바람", "paɾam"],
    ko_mid: ["ᄇᆞᄅᆞᆷ", "pʌɾʌm"],
    ko_gor: ["孛纜", "*pʌɾʌm"],
    es: ["viento", "ˈbjento"],
    es_mx: ["viento", "bjento"],
    es_ar: ["viento", "bjento"],
    es_co: ["viento", "bjento"],
    es_cl: ["viento", "bjento"],
    es_pe: ["viento", "bjento"],
    es_ve: ["viento", "bjento"],
    es_cu: ["viento", "bjento"],
    es_do: ["viento", "bjento"],
    es_pr: ["viento", "bjento"],
    es_gt: ["viento", "bjento"],
    es_uy: ["viento", "bjento"],
    es_ec: ["viento", "bjento"],
    es_bo: ["viento", "bjento"],
    es_py: ["viento", "bjento"],
    es_cr: ["viento", "bjento"],
    es_hn: ["viento", "bjento"],
    es_ni: ["viento", "bjento"],
    es_sv: ["viento", "bjento"],
    es_pa: ["viento", "bjento"],
    es_an: ["viento", "bjento"],
    pt: ["vento", "ˈvẽtu"],
    pt_br: ["vento", "ˈvẽtʊ"],
    pt_ao: ["vento", "ˈvẽtu"],
    pt_mz: ["vento", "ˈvẽtu"],
    fr: ["vent", "vɑ̃"],
    fr_qc: ["vent", "vã"],
    fr_be: ["vent", "vɑ̃"],
    fr_ch: ["vent", "vɑ̃"],
    it: ["vento", "ˈvento"],
    ca: ["vent", "ben"],
    ca_va: ["vent", "vent"],
    gl: ["vento", "ˈbento"],
    ro: ["vânt", "vɨnt"],
    oc: ["vent", "ben"],
    co: ["ventu", "ˈventu"],
    sc: ["bentu", "ˈbɛntu"],
    rm: ["vent", "vɛnt"],
    lad: ["viento", "ˈbjento"],
    an: ["viento", "ˈbjento"],
    ast: ["vientu", "ˈbjentu"],
    ext: ["ventu", "ˈbentu"],
    vec: ["vento", "ˈvento"],
    nap: ["viento", "ˈvjendə"],
    scn: ["ventu", "ˈvɛntu"],
    lij: ["véntu", "ˈventu"],
    lmo: ["vent", "vɛnt"],
    pms: ["vent", "vɛnt"],
    fur: ["vint", "vint"],
    egl: ["vèint", "veint"],
    wa: ["vint", "vɛ̃"],
    frp: ["vent", "vɛ̃"],
    pcd: ["vint", "vɛ̃"],
    mwl: ["ventu", "ˈventu"],
    ia: ["vento", "ˈvento"],
    ie: ["vent", "vent"],
    io: ["vento", "ˈvento"],
    eo: ["vento", "ˈvento"],
    de: ["Wind", "vɪnt"],
    de_at: ["Wind", "vɪnt"],
    de_ch: ["Wind", "vɪnt"],
    gsw: ["Wind", "vɪnd"],
    bar: ["Wind", "vind"],
    nds: ["Wind", "vɪnt"],
    nl: ["wind", "ʋɪnt"],
    nl_be: ["wind", "ʋɪnt"],
    af: ["wind", "vəint"],
    sv: ["vind", "vɪnd"],
    no: ["vind", "vɪnː"],
    nn: ["vind", "vɪnː"],
    da: ["vind", "venˀ"],
    is: ["vindur", "ˈvɪntʏr"],
    fo: ["vindur", "ˈvɪndʊr"],
    fy: ["wyn", "vin"],
    lb: ["Wand", "vɑnt"],
    yi: ["ווינט", "vɪnt"],
    sco: ["wind", "wɪn"],
    en: ["wind", "wɪnd"],
    en_us: ["wind", "wɪnd"],
    en_ca: ["wind", "wɪnd"],
    en_au: ["wind", "wɪnd"],
    en_nz: ["wind", "wɪnd"],
    en_za: ["wind", "wɪnd"],
    en_ie: ["wind", "wɪnd"],
    en_sco: ["wind", "wɪnd"],
    en_in: ["wind", "wɪnɖ"],
    ru: ["ветер", "ˈvʲetʲɪr"],
    uk: ["вітер", "ˈʋitɛr"],
    be: ["вецер", "ˈvʲetsʲɛr"],
    pl: ["wiatr", "vjatr"],
    cs: ["vítr", "viːtr"],
    sk: ["vietor", "ˈvjetor"],
    sl: ["veter", "ˈʋeːtər"],
    hr: ["vjetar", "ʋjɛtar"],
    bs: ["vjetar", "ʋjɛtar"],
    sr: ["ветар", "ʋɛtar"],
    mk: ["ветер", "ˈvɛtɛr"],
    bg: ["вятър", "ˈvjatər"],
    hsb: ["wětr", "vjɛtr"],
    dsb: ["wětš", "vjɛtʃ"],
    csb: ["wiater", "ˈvjatɛr"],
    rue: ["вітер", "ˈvitɛr"],
    lt: ["vėjas", "ˈvʲeːjas"],
    lv: ["vējš", "ʋeːjʃ"],
    ga: ["gaoth", "ɡeː"],
    gd: ["gaoth", "kɯː"],
    cy: ["gwynt", "ɡwɪnt"],
    br: ["avel", "ˈavɛl"],
    gv: ["geay", "gjeː"],
    kw: ["gwyns", "ɡwɪnz"],
    fi: ["tuuli", "ˈtuːli"],
    et: ["tuul", "tuːl"],
    hu: ["szél", "seːl"],
    se: ["biegga", "ˈbieɡːa"],
    tr: ["rüzgâr", "ɾyzˈgjaːɾ"],
    az: ["külək", "cyˈlæc"],
    azb: ["کولک", "cyˈlæc"],
    uz: ["shamol", "ʃɒˈmɒl"],
    kk: ["жел", "ʒel"],
    ky: ["шамал", "ʃaˈmal"],
    tk: ["ýel", "jel"],
    ug: ["شامال", "ʃamal"],
    tt: ["җил", "dʒil"],
    ba: ["ел", "jel"],
    cv: ["ҫил", "ɕil"],
    sah: ["тыал", "tɯal"],
    mn: ["салхи", "salxi"],
    ar: ["ريح", "riːħ"],
    ar_eg: ["هوا", "hawa"],
    he: ["רוח", "ˈʁuax"],
    am: ["ነፋስ", "nɨfas"],
    ti: ["ንፋስ", "nɪfas"],
    mt: ["riħ", "rɪħ"],
    hi: ["हवा", "ɦəʋaː"],
    ur: ["ہوا", "ɦəʋaː"],
    bn: ["বাতাস", "baːtaʃ"],
    pa: ["ਹਵਾ", "ɦəʋaː"],
    gu: ["પવન", "pəʋən"],
    mr: ["वारा", "ʋaːɾaː"],
    ne: ["हावा", "ɦaːʋaː"],
    si: ["සුළඟ", "suɭəŋɡə"],
    fa: ["باد", "bɒːd"],
    prs: ["باد", "bɒːd"],
    ps: ["باد", "baːd"],
    ku: ["ba", "ba"],
    ckb: ["با", "ba"],
    tg: ["бод", "bod"],
    as: ["বতাহ", "bɔtaɦ"],
    or: ["ପବନ", "pɔbɔna"],
    mai: ["हवा", "ɦəʋaː"],
    bho: ["हवा", "ɦəʋaː"],
    bal: ["گوات", "ɡwaːt"],
    ta: ["காற்று", "kaːtru"],
    te: ["గాలి", "ɡaːli"],
    kn: ["ಗಾಳಿ", "ɡaːɭi"],
    ml: ["കാറ്റ്", "kaːtːɨ"],
    zh: ["风", "fɤŋ˥"],
    zh_tw: ["風", "fɤŋ˥"],
    yue: ["風", "fʊŋ˥"],
    nan: ["風", "hɔŋ˥"],
    wuu: ["风", "foŋ˥"],
    hak_cn: ["风", "fuŋ˦"],
    gan: ["风", "fuŋ˥"],
    hsn: ["风", "fəŋ˥"],
    cjy: ["风", "fəŋ˥"],
    vi: ["gió", "zɔ˧˩˧"],
    vi_s: ["gió", "jɔ˨˩˦"],
    th: ["ลม", "lom˧"],
    th_isan: ["ลม", "lom˧"],
    th_n: ["ลม", "lom˧"],
    th_s: ["ลม", "lom˧"],
    lo: ["ລົມ", "lom˧"],
    km: ["ខ្យល់", "kʰjɔl"],
    my: ["လေ", "lè"],
    id: ["angin", "ˈaŋin"],
    ms: ["angin", "ˈaŋin"],
    tl: ["hangin", "haˈŋin"],
    ceb: ["hangin", "haˈŋin"],
    jv: ["angin", "aŋin"],
    su: ["angin", "aŋin"],
    mg: ["rivotra", "riˈvutʂ"],
    haw: ["makani", "maˈkani"],
    mi: ["hau", "hau"],
    sm: ["matagi", "mataŋi"],
    to: ["matangi", "mataŋi"],
    fj: ["cagi", "ˈðaŋi"],
    ty: ["mata'i", "mataʔi"],
    niu: ["matagi", "mataŋi"],
    tvl: ["matagi", "mataŋi"],
    gil: ["ang", "aŋ"],
    ch: ["manglo'", "maŋɡlɔʔ"],
    sw: ["upepo", "uˈpepo"],
    ha: ["iska", "ˈiska"],
    yo: ["afẹ́fẹ́", "afɛ̃fɛ̃"],
    ig: ["ifufe", "ifufe"],
    zu: ["umoya", "umoːja"],
    xh: ["umoya", "umoːja"],
    st: ["moya", "mɔja"],
    tn: ["phefo", "pʰefɔ"],
    sn: ["mhepo", "ˈmʱepo"],
    rw: ["umuyaga", "umujaɣa"],
    rn: ["umuyaga", "umujaɣa"],
    ny: ["mphepo", "ˈmpʰepo"],
    lg: ["empewo", "empeːwo"],
    so: ["dabayl", "ˈdabajl"],
    om: ["bubbee", "ˈbubːeː"],
    wo: ["ngelaw", "ŋɡelaw"],
    ff: ["henndu", "hɛndu"],
    bm: ["fiɲɛ", "fiɲɛ"],
    ak: ["mframa", "mframa"],
    ln: ["mopepe", "mopepe"],
    nv: ["níyol", "níjol"],
    qu: ["wayra", "ˈwajra"],
    ay: ["thaya", "ˈtʰaja"],
    gn: ["yvytu", "ɨvɨˈtu"],
    nci: ["ehecatl", "eˈhekatɬ"],
    jbo: ["brife", "ˈbri.fe"],
    tlh: ["SuS", "ʂuʂ"],
    tok: ["kon", "kon"],
    hy: ["քամի", "kʰɑˈmi"],
    hyw: ["քամի", "kʰɑˈmi"],
    ka: ["ქარი", "kʰɑɾi"],
    sq: ["erë", "ˈɛɾə"],
    aln: ["erë", "ˈɛɾə"],
    eu: ["haize", "ˈaise"],
    tpi: ["win", "win"],
    ht: ["van", "van"],
    jam: ["wind", "wɪn"],
    pap: ["bientu", "ˈbjentu"],
    kea: ["vento", "ˈvẽtu"],
    mfe: ["divan", "diˈvɑ̃"],
    rcf: ["divan", "diˈvɑ̃"],
    pcm: ["win", "win"],
    bzj: ["wind", "wɪn"],
    srn: ["winti", "ˈwɪnti"],
    cdo: ["风", "huŋ˦˦"],
    czh: ["风", "fʌ̃˧˩"],
    hak_tw: ["風", "fuŋ˨˦"],
    nan_hai: ["风", "foŋ˨˧"],
    nan_te: ["风", "hoŋ˧˧"],
    nan_xm: ["風", "hɔŋ˥˥"],
    wuu_hz: ["风", "foŋ˧˧"],
    wuu_sz: ["风", "foŋ˥˥"],
    wuu_wz: ["风", "hoŋ˧˧"],
    zh_cd: ["风", "foŋ˥˥"],
    zh_nj: ["风", "fən˧˩"],
    zh_wh: ["风", "foŋ˥˥"],
    zh_xa: ["风", "fəŋ˨˩"],
    en_aave: ["wind", "wɪn"],
    en_app: ["wind", "waɪnd"],
    en_brum: ["wind", "wɪnd"],
    en_ck: ["wind", "wɪnd"],
    en_est: ["wind", "wɪnd"],
    en_geordie: ["wind", "wɪnd"],
    en_jam: ["wind", "wɪnd"],
    en_ke: ["wind", "wɪnd"],
    en_manc: ["wind", "wɪnd"],
    en_my: ["wind", "wɪnd"],
    en_ng: ["wind", "wɪnd"],
    en_ng2: ["wind", "wɪnd"],
    en_ph: ["wind", "wɪnd"],
    en_scouse: ["wind", "wɪnd"],
    en_sg: ["wind", "wɪnd"],
    en_south: ["wind", "wɪnd"],
    en_wc: ["wind", "wɪnd"],
    en_wls: ["wind", "wɪnd"],
    en_yk: ["wind", "wɪnd"],
    fr_af: ["vent", "vɑ̃"],
    fr_ci: ["vent", "vɑ̃"],
    fr_cm: ["vent", "vɑ̃"],
    fr_ht: ["vent", "vɑ̃"],
    fr_lu: ["vent", "vɑ̃"],
    fr_sn: ["vent", "vɑ̃"],
    li: ["wind", "vɪnt"],
    pt_cv: ["vento", "ˈvẽtu"],
    pt_gw: ["bentu", "bẽtu"],
    pt_mo: ["vento", "ˈvẽtu"],
    szl: ["wiatr", "vjatr"],
    kab: ["aḍu", "adˤu"],
    shi: ["ⴰⴹⵓ", "adˤu"],
    shy: ["aḍu", "adˤu"],
    tzm: ["ⴰⴹⵓ", "adˤu"],
    zgh: ["ⴰⴹⵓ", "adˤu"],
    aa: ["caacay", "ħaːħaj"],
    ar_ma: ["ريح", "riːħ"],
    ar_lev: ["هوا", "hawa"],
    acw: ["هوا", "hawa"],
    ar_qur: ["ريح", "riːħ"],
    ts: ["moya", "mɔja"],
    toi: ["muwo", "muwo"],
    lua: ["tshipepele", "tʃipepele"],
    nso: ["phefo", "pʰɛfɔ"],
    ssw: ["umoya", "umoːja"],
    nd: ["umoya", "umoːja"],
    umb: ["ofela", "ofela"],
    kg: ["mupepe", "mupepe"],
    efi: ["ofụm", "ofʊm"],
    tiv: ["ahumbe", "ahumbe"],
    men: ["gbayailɔ", "gbajailɔ"],
    sus: ["foye", "foje"],
    loz: ["moya", "moja"],
    tum: ["mphepo", "ˈmpʰepo"],
    sd: ["هوا", "ɦəʋaː"],
    bo: ["རླུང", "luŋ˥"],
    dz: ["རླུང་མ", "luŋma"],
    chr: ["ᎤᏃᎴ", "unole"],
    iu: ["ᐊᓄᕆ", "anuri"],
    kl: ["anori", "anoʁi"],
    sux: ["líl", "liːl"],
    hit: ["𒄷𒌋𒉿𒀭𒍝", "xuwants"],
    uga: ["𐎗𐎈", "riːħu"],
    phn: ["𐤓𐤇", "riːħ"],
    xpu: ["𐤓𐤅𐤇", "ruːħ"],
    oar: ["𐡓𐡅𐡇", "riːħ"],
    xto: ["𑀯𑀦𑁆𑀢𑁆", "wɑnt"],
    txb: ["𑀬𑁂𑀦𑁆𑀢𑁂", "jɛntə"],
    otk: ["𐰘𐰠", "jel"],
    pal: ["𐭥𐭠𐭲", "waːd"],
    egy: ["𓍿𓄿𓅱", "tʃaw"],
    cop: ["ⲑⲏⲟⲩ", "tʰeːu"],
    hy_grab: ["հողմ", "hoʁm"],
    qwc: ["wayra", "ˈwajra"],
    gmy: ["𐀀𐀚𐀗", "ˈanemos"],
    p_jpn: ["*kansay", "kansay"],
    ojp: ["風", "kadze"],
    el: ["άνεμος", "ˈanemos"],
    dv: ["ވައި", "ʋəi"],
    ave: ["𐬬𐬁𐬙𐬀", "ˈʋaːta"],
    ko_em: ["바람", "paɾam"],
    sga: ["gáeth", "ɣaːiθʲ"],
    psem: ["*rīḥ-", "riːħ"],
    tet: ["anin", "ˈanin"],
    zdj: ["upepo", "uˈpepo"],
    rom: ["balval", "ˈbalval"],
    shn: ["လူမ်း", "lum˥"],
    ks: ["واو", "vaːv"],
    ce: ["мох", "mɔx"],
    ady: ["жьыбгъэ", "ʑəbʁɛ"],
    os: ["уад", "wad"],
    krc: ["жел", "ʒel"],
    tyv: ["салгын", "salɣɯn"],
    bxr: ["һалхи", "halxi"],
    inh: ["мух", "mux"],
    av: ["гьури", "huri"],
    kum: ["ел", "jel"],
    hmn: ["cua", "tɕua˧"],
    mh: ["an̄", "aŋ"],
    za: ["rumz", "ɣum˨"],
    sat: ["ᱦᱚᱭ", "hɔj"],
    kok: ["वारो", "ʋaːɾo"],
    doi: ["ब्हाऽ", "bʱaː"],
    sg: ["pupu", "pupu"],
    din: ["yom", "jom"],
    ee: ["aya", "aja"],
    luo: ["yamo", "jamo"],
    ilo: ["angin", "ˈaŋin"],
    hil: ["hangin", "haˈŋin"],
    war: ["hangin", "haˈŋin"],
    pag: ["dagem", "daˈɡɛm"],
    min: ["angin", "aŋin"],
    ban: ["angin", "aŋin"],
    bug: ["anging", "aŋiŋ"],
    mak: ["anging", "aŋiŋ"],
    bjn: ["angin", "aŋin"],
    vi_nom: ["𩙋", "zɔ˧˩˧"],
    ar_jo: ["ريح", "riːħ"],
    ar_ps: ["ريح", "riːħ"],
    ar_sy: ["ريح", "riːħ"],
    ar_lb: ["ريح", "riːħ"],
    ar_ye: ["ريح", "riːħ"],
    ar_sa: ["ريح", "riːħ"],
    ayl: ["ريح", "riːħ"],
    abv: ["ريح", "riːħ"],
    afb: ["ريح", "riːħ"],
    ar_gulf: ["ريح", "riːħ"],
    ar_iq: ["ريح", "riːħ"],
    arq: ["ريح", "riːħ"],
    mey: ["ريح", "riːħ"],
    ar_tn: ["ريح", "riːħ"],
    ar_sd: ["ريح", "riːħ"],
    de_lu: ["Wand", "vant"],
    pam: ["angin", "ˈaŋin"],
    krl: ["tuuli", "ˈtuːlʲi"],
    vot: ["tuuli", "ˈtuːli"],
    udm: ["тӧл", "ˈtɘl"],
    kpv: ["тӧв", "ˈtɘʋ"],
    koi: ["тӧв", "ˈtɘʋ"],
    mhr: ["мардеж", "mɑɾˈdeʒ"],
    slr: ["yel", "jɛl"],
    crh: ["yel", "jel"],
    quz: ["wayra", "ˈwajɾa"],
    quy: ["wayra", "ˈwajɾa"],
    xal: ["салькн", "salʲˈkn̩"],
    vo: ["vien", "viˈen"],
    ain: ["レラ", "rera"],
    pmt: ["matangi", "maˈtaŋi"],
    pkp: ["matangi", "maˈtaŋi"],
    rap: ["tokerau", "tokeˈɾau"],
    lez: ["гар", "ɡar"],
    mnp: ["风", "xɔŋ⁵⁴"],
    yue_ts: ["风", "fɵŋ³³"],
    wuu_nb: ["风", "foŋ⁵²"],
    evn: ["эдын", "ədin"],
    eve: ["эдэн", "ədən"],
    mnc: ["ᡝᡩᡠᠨ", "ədun"],
    sjo: ["ᡝᡩᡠᠨ", "ədun"],
    kjh: ["чил", "tʃil"],
    lkt: ["tȟaté", "tʰaˈte"],
    mni: ["ꯅꯨꯡꯁꯤꯠ", "nuŋsit"],
    ket: ["бей", "beːj"],
    gld: ["хэдун", "hədũ"],
    kpy: ["кытэг", "kəteɣ"],
    yrl: ["iwitú", "iwiˈtu"],
    rgn: ["vènt", "vɛt"],
    ki: ["rũhuho", "ɾòhùːhɔ̀"],
    gun: ["yvytu", "ɨʋɨˈtu"],
    crk: ["ᔫᑎᐣ", "joːˈtin"],
    cr: ["ᔫᑎᐣ", "joːˈtin"],
    mn_cn: ["ᠰᠠᠯᠬᠢ", "salxi"],
    gan_ja: ["风", "fuŋ˧˧˦"],
    gan_fz: ["风", "fuŋ˨˨"],
    cjy_lv: ["风", "xuəŋ˨˩˧"],
    cjy_xz: ["风", "fəŋ˧˩˧"],
    hsn_hy: ["風", "xɤŋ˦˦˥"],
    zh_sc: ["风", "foŋ˥˥"],
    zh_jh: ["风", "fə̃˧˩"],
    zh_zz: ["风", "fəŋ˨˩"],
    zh_jn: ["风", "fəŋ˨˩˧"],
    zh_hf: ["风", "fəŋ˨˩˨"],
    cnp: ["风", "føŋ˦˩"],
    nan_pn: ["風", "hɔŋ˧˧"],
    nan_qz: ["風", "hɔŋ˧˧"],
    nan_zz: ["風", "hɔŋ˦˦"],
    cpx: ["风", "hɒŋ˥˧˧"],
    yue_dg: ["风", "foŋ˨˩˧"],
    yue_nn: ["风", "fuŋ˥˥"],
    yue_zs: ["風", "hoŋ˥˥"],
    wuu_jh: ["风", "foŋ˧˧˦"],
    wuu_jx: ["风", "foŋ˥˧"],
    agr: ["dasɨ", "dasɨ"],
    agx: ["кулак", "kulak"],
    ani: ["мочи", "moči"],
    aqc: ["гьува", "huwa"],
    arn: ["kɨrɨf", "kɨrɨf"],
    bbl: ["мох", "mox"],
    bdk: ["кулак", "kulak"],
    dar: ["дягІ", "daˤʕ"],
    ddo: ["лъаци", "ɬaci"],
    emp: ["nãũ", "nãũ"],
    guc: ["houtai", "houtai"],
    huz: ["за̇лІе", "zɑƛe"],
    kca: ["wot", "wot"],
    khb: ["lum.2", "lum"],
    khv: ["лъаца", "ɬaca"],
    kjj: ["кулак", "kulak"],
    kry: ["кулак", "kulak"],
    lbe: ["марч", "marč"],
    mch: ["hehēnčə", "hehēnčə"],
    mns: ["wot", "wot"],
    myv: ["var̃ma", "var̃ma"],
    mzh: ["inhʷokʷ", "inhʷokʷ"],
    nog: ["ел", "yel"],
    nut: ["lam.2", "lam"],
    pbb: ["wexʸa", "wexʸa"],
    rmy: ["balval", "balval"],
    rtm: ["lɔŋi", "lɔŋi"],
    rut: ["хьыбыл", "x̌ɨbɨl"],
    sel: ["mær̃ḳɨ", "mær̃ḳɨ"],
    shp: ["niwɨ", "niwɨ"],
    tab: ["микІ", "mikʼ"],
    tkr: ["мыц", "mɨc"],
    tue: ["wĩ'dõ", "wĩ'dõ"],
    udi: ["муш", "muš"],
    bi: ["win", "win"],
    pis: ["win", "win"],
    tcs: ["win", "win"],
  },
};
