/**
 * Wine is a word that crosses language families, and nobody has established which way it travelled.
 * Indo-European has *wóyh₁nom — Latin vīnum, Greek oînos, Armenian gini, Hittite wiyana-. Semitic has
 * *wayn- — Hebrew yayin, Ugaritic yn, Arabic wayn. Kartvelian has *ɣwino- — Georgian ღვინო. Three
 * unrelated families, one word, and the oldest chemical traces of winemaking anywhere are from Georgia
 * and the south Caucasus around 6000 BC, which is exactly where all three families are in contact. The
 * honest state of the question is that the word spread with the drink and the direction is unsettled.
 *
 * Germanic did not inherit it: English wine, German Wein and Old English wīn are all borrowed from
 * Latin vīnum, along with vine and vinegar. East Asia is a fourth layer again — 葡萄酒 is 'grape
 * liquor', and the 葡萄 is itself a loan, brought back along the Silk Road from an Iranian source.
 *
 * The colours on this map are the four routes, not the four families: a language is coloured by where
 * its word came from.
 */
WORDS.wine = {
  emoji: "🍷",
  label: {
    en: "Wine", ja: "ワイン", ko: "포도주", zh: "葡萄酒", yue: "葡萄酒", vi: "Rượu vang",
    th: "ไวน์", id: "Anggur", hi: "शराब", de: "Wein", fr: "Vin", it: "Vino", es: "Vino",
    es_eu: "Vino", es_mx: "Vino", pt: "Vinho", pt_eu: "Vinho", pt_br: "Vinho", ru: "Вино",
    uk: "Вино", ar: "نبيذ", he: "יין", sw: "Mvinyo",
  },
  definition: {
    en: "Wine — fermented grape juice. The word crosses three unrelated families around the Caucasus, and which of them lent it is still unsettled.",
    ja: "ワイン — 葡萄を発酵させた酒。この語はカフカス周辺で無関係な三語族をまたいでおり、どこが貸したのかは未解決。",
    ko: "포도주 — 포도를 발효시킨 술. 이 단어는 캅카스 주변에서 서로 무관한 세 어족을 넘나들며, 어느 쪽이 빌려주었는지는 아직 미해결이다.",
    zh: "葡萄酒 — 葡萄发酵而成的酒。这个词在高加索一带跨越三个互不相关的语系，究竟谁借给谁至今未有定论。",
    yue: "葡萄酒 — 葡萄發酵而成嘅酒。呢個詞喺高加索一帶跨越三個唔相關嘅語系，究竟邊個借畀邊個仍然未有定論。",
    vi: "Rượu vang — nước nho lên men. Từ này bắc qua ba ngữ hệ không liên quan quanh vùng Kavkaz, và ai vay của ai thì vẫn chưa ngã ngũ.",
    th: "ไวน์ — น้ำองุ่นหมัก คำนี้ข้ามสามตระกูลภาษาที่ไม่เกี่ยวข้องกันแถบคอเคซัส และยังไม่มีข้อสรุปว่าใครยืมจากใคร.",
    id: "Anggur — sari buah anggur yang difermentasi. Kata ini melintasi tiga rumpun bahasa tak berkerabat di sekitar Kaukasus, dan siapa meminjam dari siapa masih belum jelas.",
    hi: "शराब — किण्वित अंगूर का रस। यह शब्द काकेशस के आसपास तीन असंबंधित भाषा-परिवारों को पार करता है, और किसने किससे लिया यह अब भी अनिश्चित है।",
    de: "Wein — vergorener Traubensaft. Das Wort überquert rund um den Kaukasus drei nicht verwandte Sprachfamilien, und wer es wem geliehen hat, ist ungeklärt.",
    fr: "Vin — jus de raisin fermenté. Le mot traverse trois familles sans parenté autour du Caucase, et l'on ignore toujours qui l'a emprunté à qui.",
    it: "Vino — succo d'uva fermentato. La parola attraversa tre famiglie non imparentate intorno al Caucaso, e chi l'abbia prestata a chi resta irrisolto.",
    es: "Vino — zumo de uva fermentado. La palabra cruza tres familias sin parentesco en torno al Cáucaso, y quién se la prestó a quién sigue sin resolverse.",
    es_eu: "Vino — zumo de uva fermentado. La palabra cruza tres familias sin parentesco en torno al Cáucaso, y quién se la prestó a quién sigue sin resolverse.",
    es_mx: "Vino — jugo de uva fermentado. La palabra cruza tres familias sin parentesco en torno al Cáucaso, y quién se la prestó a quién sigue sin resolverse.",
    pt: "Vinho — sumo de uva fermentado. A palavra atravessa três famílias sem parentesco em torno do Cáucaso, e quem a emprestou a quem continua por resolver.",
    pt_eu: "Vinho — sumo de uva fermentado. A palavra atravessa três famílias sem parentesco em torno do Cáucaso, e quem a emprestou a quem continua por resolver.",
    pt_br: "Vinho — suco de uva fermentado. A palavra atravessa três famílias sem parentesco em torno do Cáucaso, e quem a emprestou a quem continua sem resposta.",
    ru: "Вино — перебродивший виноградный сок. Слово пересекает три неродственные семьи вокруг Кавказа, и кто у кого его занял — до сих пор не решено.",
    uk: "Вино — перебродивший виноградний сік. Слово перетинає три неспоріднені сім'ї навколо Кавказу, і хто в кого його запозичив — досі не з'ясовано.",
    ar: "نبيذ — عصير عنب مخمَّر. تعبر الكلمة ثلاث عائلات لغوية غير متقاربة حول القوقاز، ولا يزال غير محسوم مَن اقترضها من مَن.",
    he: "יין — מיץ ענבים מותסס. המילה חוצה שלוש משפחות לשוניות בלתי קשורות סביב הקווקז, ועדיין לא ברור מי שאל אותה ממי.",
    sw: "Mvinyo — maji ya zabibu yaliyochachushwa. Neno hili linavuka familia tatu zisizohusiana kuzunguka Kaukasia, na nani alikopa kwa nani bado halijulikani.",
  },
  family: {
    en: "ie",
    ja: "other",
    ko: "other",
    zh: "other",
    yue: "other",
    vi: "other",
    th: "other",
    id: "other",
    hi: "other",
    de: "ie",
    fr: "ie",
    it: "ie",
    es: "ie",
    es_mx: "ie",
    pt: "ie",
    pt_br: "ie",
    ru: "ie",
    uk: "ie",
    ar: "other",
    he: "sem",
    sw: "ie",
    p_ine: "ie",
    la: "ie",
    el_grc: "ie",
    el_kath: "ie",
    el: "ie",
    hit: "ie",
    hy_grab: "ie",
    hy: "ie",
    got: "ie",
    ang: "ie",
    enm: "ie",
    non: "ie",
    goh: "ie",
    gmh: "ie",
    osx: "ie",
    ofs: "ie",
    cu: "ie",
    fro: "ie",
    osp: "ie",
    sga: "ie",
    cy: "ie",
    ga: "ie",
    psem: "sem",
    hbo: "sem",
    he_mis: "sem",
    uga: "sem",
    arc: "sem",
    ar_qur: "sem",
    gez: "sem",
    akk: "sem",
    cop: "sem",
    pkar: "kart",
    ka: "kart",
    xmf: "kart",
    sva: "kart",
    nl: "other",
    af: "other",
    sv: "other",
    no: "other",
    nn: "other",
    da: "other",
    is: "other",
    fo: "other",
    pl: "other",
    cs: "other",
    sk: "other",
    sl: "other",
    hr: "other",
    sr: "other",
    bs: "other",
    bg: "other",
    mk: "other",
    be: "other",
    ro: "other",
    ca: "other",
    gl: "other",
    oc: "other",
    sq: "other",
    lt: "other",
    lv: "other",
    et: "other",
    fi: "other",
    hu: "other",
    eu: "other",
    tr: "other",
    az: "other",
    fa: "other",
    tg: "other",
    ur: "other",
    bn: "other",
    mr: "other",
    ta: "other",
    te: "other",
    ml: "other",
    kn: "other",
    si: "other",
    ne: "other",
    kk: "other",
    uz: "other",
    ky: "other",
    mn: "other",
    ms: "other",
    tl: "other",
    am: "other",
    ha: "other",
    zu: "other",
    mg: "other",
  },
  routes: {
    ie: { color: "#7c2d12", emoji: "🏺", en: "Indo-European *wóyh₁nom", ja: "印欧祖語 *wóyh₁nom", ko: "인도유럽조어 *wóyh₁nom", zh: "原始印欧语 *wóyh₁nom", yue: "原始印歐語 *wóyh₁nom", vi: "Ấn-Âu nguyên thủy *wóyh₁nom", th: "อินโด-ยูโรเปียนดั้งเดิม *wóyh₁nom", id: "Proto-Indo-Eropa *wóyh₁nom", hi: "आद्य-भारोपीय *wóyh₁nom", de: "Urindogermanisch *wóyh₁nom", fr: "indo-européen commun *wóyh₁nom", it: "protoindoeuropeo *wóyh₁nom", es: "protoindoeuropeo *wóyh₁nom", pt: "protoindo-europeu *wóyh₁nom", ru: "праиндоевроп. *wóyh₁nom", uk: "праіндоєвроп. *wóyh₁nom", ar: "الهندية الأوروبية الأم *wóyh₁nom", he: "הודו-אירופית קדומה *wóyh₁nom", sw: "Kihindi-Ulaya cha kale *wóyh₁nom" },
    sem: { color: "#a16207", emoji: "📜", en: "Semitic *wayn-", ja: "セム祖語 *wayn-", ko: "셈조어 *wayn-", zh: "原始闪米特语 *wayn-", yue: "原始閃米特語 *wayn-", vi: "Semit nguyên thủy *wayn-", th: "เซมิติกดั้งเดิม *wayn-", id: "Proto-Semit *wayn-", hi: "आद्य-सामी *wayn-", de: "Ursemitisch *wayn-", fr: "sémitique commun *wayn-", it: "protosemitico *wayn-", es: "protosemítico *wayn-", pt: "protossemítico *wayn-", ru: "прасемитское *wayn-", uk: "прасемітське *wayn-", ar: "السامية الأم *wayn-", he: "שמית קדומה *wayn-", sw: "Kisemiti cha kale *wayn-" },
    kart: { color: "#15803d", emoji: "🍇", en: "Kartvelian ɣvino — oldest wine", ja: "カルトヴェリ語 ɣvino — 最古の醸造地", ko: "카르트벨리어 ɣvino — 가장 오래된 포도주", zh: "卡尔特维尔语 ɣvino — 最早的酿酒地", yue: "卡爾特維爾語 ɣvino — 最早嘅釀酒地", vi: "Kartvel ɣvino — nơi làm rượu cổ nhất", th: "คาร์ตเวเลียน ɣvino — แหล่งทำไวน์เก่าแก่ที่สุด", id: "Kartvelia ɣvino — anggur tertua", hi: "कार्तवेली ɣvino — सबसे पुरानी मदिरा", de: "Kartwelisch ɣvino — ältester Wein", fr: "kartvélien ɣvino — le vin le plus ancien", it: "kartvelico ɣvino — il vino più antico", es: "kartveliano ɣvino — el vino más antiguo", pt: "cartveliano ɣvino — o vinho mais antigo", ru: "картвельское ɣvino — древнейшее вино", uk: "картвельське ɣvino — найдавніше вино", ar: "الكرتفيلية ɣvino — أقدم نبيذ", he: "קרטוולית ɣvino — היין העתיק ביותר", sw: "Kikartveli ɣvino — mvinyo kongwe zaidi" },
    other: { color: "#6b7280", emoji: "🛤️", en: "named locally or borrowed later", ja: "現地語または後代の借用", ko: "현지어 또는 후대의 차용", zh: "本地命名或后世借入", yue: "本地命名或者後世借入", vi: "gọi theo bản địa hoặc vay mượn về sau", th: "ตั้งชื่อในท้องถิ่นหรือยืมภายหลัง", id: "dinamai setempat atau dipinjam kemudian", hi: "स्थानीय नाम या बाद का उधार", de: "einheimisch benannt oder später entlehnt", fr: "nommé localement ou emprunté plus tard", it: "denominato localmente o preso in prestito più tardi", es: "nombrado localmente o tomado más tarde", pt: "nomeado localmente ou tomado mais tarde", ru: "местное название или позднее заимствование", uk: "місцева назва або пізніше запозичення", ar: "تسمية محلية أو اقتراض متأخر", he: "שם מקומי או שאילה מאוחרת", sw: "limepewa jina la kienyeji au limekopwa baadaye" },
  },
  data: {
    // --- UI languages -------------------------------------------------
    en: ["wine", "waɪn"],
    ja: ["ワイン", "waiɴ"],
    ko: ["포도주", "pododʑu"],
    zh: ["葡萄酒", "pʰu˧˥ tʰɑʊ˧˥ tɕjoʊ˨˩˦"],
    yue: ["葡萄酒", "pʰou˨˩ tʰou˨˩ tsɐu˧˥"],
    vi: ["rượu vang", "zɨəw˧ˀ˥ vaŋ˧"],
    th: ["ไวน์", "waj˧"],
    id: ["anggur", "aŋɡur"],
    hi: ["शराब", "ʃəraːb"],
    de: ["Wein", "vaɪ̯n"],
    fr: ["vin", "vɛ̃"],
    it: ["vino", "ˈvino"],
    es: ["vino", "ˈbino"],
    es_mx: ["vino", "ˈbino"],
    pt: ["vinho", "ˈviɲu"],
    pt_br: ["vinho", "ˈviɲu"],
    ru: ["вино", "vʲɪˈno"],
    uk: ["вино", "ʋɪˈnɔ"],
    ar: ["نبيذ", "nabiːð"],
    he: ["יין", "ˈjajin"],
    sw: ["mvinyo", "mˈviɲo"],

    // --- Indo-European *wóyh₁nom --------------------------------------
    p_ine: ["*wóyh₁nom", "wójhnom"],
    la: ["vīnum", "ˈwiːnum"],
    el_grc: ["οἶνος", "óînos"],
    el_kath: ["οἶνος", "ˈinos"],
    el: ["κρασί", "kraˈsi"],
    hit: ["𒉿𒅀𒈾𒀸", "wijanas"],
    hy_grab: ["գինի", "ɡini"],
    hy: ["գինի", "ɡiˈni"],
    got: ["𐍅𐌴𐌹𐌽", "wiːn"],
    ang: ["wīn", "wiːn"],
    enm: ["wyn", "wiːn"],
    non: ["vín", "viːn"],
    goh: ["wīn", "wiːn"],
    gmh: ["wīn", "viːn"],
    osx: ["wīn", "wiːn"],
    ofs: ["wīn", "wiːn"],
    cu: ["вино", "vino"],
    fro: ["vin", "vin"],
    osp: ["vino", "ˈbino"],
    sga: ["fín", "fiːn"],
    cy: ["gwin", "ɡwiːn"],
    ga: ["fíon", "ˈfʲiːn̪ˠ"],

    // --- Semitic *wayn- ------------------------------------------------
    psem: ["*wayn-", "wajn"],
    hbo: ["יין", "ˈjajin"],
    he_mis: ["יין", "ˈjajin"],
    uga: ["𐎊𐎐", "jenu"],
    arc: ["ܚܡܪܐ", "ħamraː"],
    ar_qur: ["خمر", "xamr"],
    gez: ["ወይን", "wɐjn"],
    akk: ["karānu", "karaːnu"],
    cop: ["ⲏⲣⲡ", "eːrp"],

    // --- Kartvelian ɣvino ----------------------------------------------
    pkar: ["*ɣwino-", "ɣwino"],
    ka: ["ღვინო", "ɣvino"],
    xmf: ["ღვინი", "ɣvini"],
    sva: ["ღვინელ", "ɣvinel"],

    // --- Modern Europe --------------------------------------------------
    nl: ["wijn", "ʋɛin"],
    af: ["wyn", "vəin"],
    sv: ["vin", "viːn"],
    no: ["vin", "viːn"],
    nn: ["vin", "viːn"],
    da: ["vin", "viːˀn"],
    is: ["vín", "viːn"],
    fo: ["vín", "vʊin"],
    pl: ["wino", "ˈvinɔ"],
    cs: ["víno", "ˈviːno"],
    sk: ["víno", "ˈviːno"],
    sl: ["vino", "ˈʋiːno"],
    hr: ["vino", "ʋino"],
    sr: ["вино", "ʋino"],
    bs: ["vino", "ʋino"],
    bg: ["вино", "viˈno"],
    mk: ["вино", "ˈvino"],
    be: ["віно", "vʲiˈno"],
    ro: ["vin", "vin"],
    ca: ["vi", "bi"],
    gl: ["viño", "ˈbiɲo"],
    oc: ["vin", "vi"],
    sq: ["verë", "ˈvɛɾə"],
    lt: ["vynas", "ˈviːnɐs"],
    lv: ["vīns", "viːns"],
    et: ["vein", "ʋein"],
    fi: ["viini", "ˈʋiːni"],
    hu: ["bor", "bor"],
    eu: ["ardo", "ardo"],

    // --- Asia, Africa ----------------------------------------------------
    tr: ["şarap", "ʃaˈɾap"],
    az: ["şərab", "ʃæˈɾab"],
    fa: ["شراب", "ʃæˈɾɒːb"],
    tg: ["шароб", "ʃarob"],
    ur: ["شراب", "ʃəraːb"],
    bn: ["মদ", "mɔd̪"],
    mr: ["वाईन", "ʋaːiːn"],
    ta: ["மது", "mad̪u"],
    te: ["ద్రాక్షారసం", "d̪raːkʂaːrasam"],
    ml: ["വീഞ്ഞ്", "ʋiːɲːɨ"],
    kn: ["ವೈನ್", "ʋain"],
    si: ["වයින්", "ʋajin"],
    ne: ["मदिरा", "məd̪iɾaː"],
    kk: ["шарап", "ʃarap"],
    uz: ["sharob", "ʃarob"],
    ky: ["шарап", "ʃarap"],
    mn: ["дарс", "dars"],
    ms: ["wain", "wain"],
    tl: ["alak", "ˈʔalak"],
    am: ["ወይን", "wɐjn"],
    ha: ["giya", "ɡija"],
    zu: ["iwayini", "iwaˈjini"],
    mg: ["divay", "divaj"],
  },
};
